ch15 = [
    ("25% of 80?", ["15","20","25","30"], "b", "20.", "Easy"),
    ("40% of a number is 24. Number?", ["60","96","36","48"], "a", "60.", "Easy"),
    ("$50 item 20% off. Sale price?", ["$10","$30","$40","$35"], "c", "$40.", "Easy"),
    ("What % of 200 is 50?", ["10%","20%","25%","50%"], "c", "25%.", "Easy"),
    ("Increase 60 by 25%.", ["72","75","80","85"], "b", "75.", "Easy"),
    ("Decrease 80 by 15%.", ["64","68","72","76"], "b", "68.", "Easy"),
    ("15% tip on $40?", ["$4","$6","$8","$10"], "b", "$6.", "Easy"),
    ("$200 increased by 10%?", ["$210","$220","$200","$240"], "b", "$220.", "Easy"),
    ("10% of 10% of 100?", ["1","10","0.1","100"], "a", "1.", "Easy"),
    ("x is 30% of 50. x?", ["10","15","20","25"], "b", "15.", "Easy"),
    ("$80 to $100. % increase?", ["20%","25%","30%","40%"], "b", "25%.", "Medium"),
    ("$150 to $120. % decrease?", ["15%","20%","25%","30%"], "b", "20%.", "Medium"),
    ("Population 800 to 1000. % increase?", ["20%","25%","200%","80%"], "b", "25%.", "Medium"),
    ("After 20% increase = $72. Original?", ["$57.60","$60","$58","$64"], "b", "$60.", "Medium"),
    ("After 10% decrease = $90. Original?", ["$99","$100","$81","$110"], "b", "$100.", "Medium"),
    ("45/60 = what %?", ["65%","70%","75%","80%"], "c", "75%.", "Medium"),
    ("40 to 50 is what % change?", ["10%","20%","25%","50%"], "c", "25%.", "Medium"),
    ("$500 at 6% for 2 years. Total?", ["$530","$560","$600","$550"], "b", "$560.", "Medium"),
    ("A value triples. % increase?", ["100%","200%","300%","50%"], "b", "200%.", "Medium"),
    ("35% of number = 140. Number?", ["350","400","490","280"], "b", "400.", "Medium"),
    ("Increase 20%, then decrease 20%. Net change?", ["No change","Decrease 4%","Decrease 2%","Increase 4%"], "b", "Decrease 4%.", "Hard"),
    ("A is 50% more than B. B is what % less than A?", ["25%","33.3%","40%","50%"], "b", "33.3%.", "Hard"),
    ("Tax $200 item at 8%. Rate to 10%. Extra tax?", ["$2","$4","$6","$10"], "b", "$4.", "Hard"),
    ("Number is 40% less than 200. % less from 150?", ["6.67%","33.3%","20%","N/A"], "a", "6.67%.", "Hard"),
    ("Oil +25%. Consumption decrease for same cost?", ["20%","25%","16.67%","33.3%"], "a", "20%.", "Hard"),
    ("Markup 50%, discount 20%. Profit %?", ["0%","12%","10%","20%"], "d", "20%.", "Hard"),
    ("CPI 120 to 150. Inflation rate?", ["20%","25%","30%","33.3%"], "b", "25%.", "Hard"),
    ("Doubles in 5 years simple interest. Rate?", ["10%","15%","20%","25%"], "c", "20%.", "Hard"),
    ("50% in 3 years simple. Annual rate?", ["10%","15%","16.67%","20%"], "c", "16.67%.", "Hard"),
    ("x is 200% of y. y is what % of x?", ["50%","25%","200%","100%"], "a", "50%.", "Hard"),
]
ch16 = [
    ("Best chart for trends over time?", ["Pie","Bar","Line graph","Histogram"], "c", "Line graph.", "Easy"),
    ("Grades by subject displays:", ["Single value","Categorical data","Time series","Correlation"], "b", "Categories.", "Easy"),
    ("To find 'total' in frequency table:", ["Read title","Sum frequencies","Find median","Look at axes"], "b", "Sum all.", "Easy"),
    ("'Mean' represents:", ["Most common","Average","Middle value","Range"], "b", "Arithmetic average.", "Easy"),
    ("'Outliers' are:", ["Average values","Values far from rest","Most common","First values"], "b", "Extreme values.", "Easy"),
    ("'Frequency polygon' shows:", ["Parts of a whole","Distribution of continuous data","Trends","Correlation"], "b", "Distribution.", "Easy"),
    ("'Mode' is:", ["Average","Middle","Most frequent","Range"], "c", "Most frequent.", "Easy"),
    ("'Range' =:", ["Average","Max \u2212 min","Count","Median"], "b", "Max \u2212 min.", "Easy"),
    ("'Cumulative frequency' shows:", ["Individual values","Running total","Only mode","SD"], "b", "Accumulated.", "Easy"),
    ("Mean of {10,20,30}?", ["10","20","30","60"], "b", "20.", "Easy"),
    ("Sales Mon=100,Tue=150,Wed=120. Average?", ["100","120","123.3","150"], "c", "123.3.", "Medium"),
    ("Pie chart 40%,30%,20%,10%. Largest?", ["40/100","30/100","20/100","The whole"], "a", "40%.", "Medium"),
    ("Temp 20\u00b0 to 35\u00b0 over 5 months. Avg increase?", ["2\u00b0","3\u00b0","5\u00b0","15\u00b0"], "b", "3\u00b0.", "Medium"),
    ("Tallest bar in 40\u201350 range means:", ["Below 40","40\u201350 most frequent","Average 45","None above 50"], "b", "Most in that range.", "Medium"),
    ("Points going upward =:", ["Negative","Positive","No","Zero"], "b", "Positive correlation.", "Medium"),
    ("Frequencies: 1(5),2(8),3(3). Mode?", ["1","2","3","5.5"], "b", "2.", "Medium"),
    ("Median of {3,7,8,12,15}?", ["7","8","9","12"], "b", "8.", "Medium"),
    ("Mean=50>median=45>mode=40 suggests:", ["Symmetric","Skewed right","Skewed left","Uniform"], "b", "Right skew.", "Medium"),
    ("Stacked bar chart shows:", ["Individual values","Components of total","Trends","Correlations"], "b", "Composition.", "Medium"),
    ("To identify 'trend' examine:", ["One point","Multiple time periods","Average","Maximum"], "b", "Over time.", "Medium"),
    ("Mean=30>median=28 suggests:", ["Symmetric","Right skew","Left skew","Uniform"], "b", "Right skew.", "Hard"),
    ("Two close bars =:", ["Large difference","Small difference","No data","Error"], "b", "Similar values.", "Hard"),
    ("Box plot: median=50, Q1=35, Q3=65. IQR?", ["15","30","50","65"], "b", "30.", "Hard"),
    ("Pie chart sectors don't sum to 100%:", ["Correct","Data error","Different units","Special type"], "b", "Error.", "Hard"),
    ("Trend line y=3x+5. x=10. y?", ["25","30","35","40"], "c", "35.", "Hard"),
    ("SD=0 when:", ["All different","All same","2 values","Mean=0"], "b", "No variation.", "Hard"),
    ("Stem-and-leaf 'stem' represents:", ["Individual points","Leading digits","Frequency","Units"], "b", "Leading digits.", "Hard"),
    ("Two-way table displays:", ["One variable","Two categorical variables","Trend","Distribution"], "b", "Cross-tabulation.", "Hard"),
    ("'Data triangulation' means:", ["Three variables","Multiple sources or methods","Drawing triangles","Measuring distances"], "b", "Multiple sources.", "Hard"),
    ("Cross-sectional study collects data:", ["Over long period","At one point","Only surveys","Only experiments"], "b", "Snapshot.", "Hard"),
]
ch17 = [
    ("Hypothesis is:", ["Proven fact","Testable prediction","Conclusion","Data"], "b", "Testable guess.", "Easy"),
    ("Controlled experiment changes:", ["Everything","All variables","One variable at a time","Nothing"], "c", "One variable.", "Easy"),
    ("Independent variable is:", ["Measured result","Changed by researcher","Controlled","Constant"], "b", "Manipulated.", "Easy"),
    ("Dependent variable is:", ["Changed by researcher","Measured result","Constant","Irrelevant"], "b", "Outcome.", "Easy"),
    ("'Control group' is:", ["Exposed to treatment","Not exposed, for comparison","The largest","Random"], "b", "Baseline.", "Easy"),
    ("'Data' refers to:", ["Conclusions","Observations and measurements","Hypotheses","Theories"], "b", "Facts collected.", "Easy"),
    ("A 'theory' in science is:", ["Just a guess","Well-supported explanation","Proven absolutely","Irrelevant"], "b", "Well-supported.", "Easy"),
    ("'Peer review' means:", ["Reviewed by students","Reviewed by experts in field","Reviewed by public","Not reviewed"], "b", "Expert evaluation.", "Easy"),
    ("'Replication' means:", ["Copying results once","Repeating experiment to verify","Changing methods","Ignoring results"], "b", "Verification.", "Easy"),
    ("'Correlation does not imply'?", ["Association","Causation","Similarity","Pattern"], "b", "Causation.", "Easy"),
    ("'Variables' in an experiment are:", ["Constants only","Factors that can change","Irrelevant","Always numbers"], "b", "Changeable factors.", "Medium"),
    ("'Sample size' affects:", ["Color","Reliability of results","Speed","Cost only"], "b", "Reliability.", "Medium"),
    ("'Null hypothesis' states:", ["There is an effect","There is no effect","Results are significant","Theory is correct"], "b", "No effect.", "Medium"),
    ("'Statistical significance' means:", ["Results are large","Unlikely due to chance","Results are practical","Everyone agrees"], "b", "Not by chance.", "Medium"),
    ("'Placebo effect' is:", ["Drug works","Improvement from belief not treatment","No effect","Side effect"], "b", "Belief-based improvement.", "Medium"),
    ("'Double-blind' study means:", ["Researchers know group assignments","Neither subjects nor researchers know","Two groups","Double check"], "b", "No bias.", "Medium"),
    ("'Qualitative data' is:", ["Numerical","Descriptive, non-numerical","Always accurate","Unimportant"], "b", "Descriptive.", "Medium"),
    ("'Quantitative data' is:", ["Descriptive","Numerical measurements","Subjective","Rare"], "b", "Numbers.", "Medium"),
    ("'Bias' in research means:", ["Objectivity","Systematic error favoring one outcome","Accuracy","Randomness"], "b", "Skewed results.", "Medium"),
    ("'Confounding variable' is:", ["Independent","Dependent","Unaccounted variable affecting results","Constant"], "c", "Hidden influence.", "Medium"),
    ("'Meta-analysis' combines:", ["One study","Multiple studies' results","Data from one experiment","Theories"], "b", "Multiple studies.", "Hard"),
    ("'Longitudinal study' follows:", ["One group over time","Multiple groups at one time","Only animals","Only surveys"], "a", "Over time.", "Hard"),
    ("'Cross-sectional study' examines:", ["One group over time","Population at one time","Only young people","Only old people"], "b", "Snapshot.", "Hard"),
    ("'Cause and effect' is established by:", ["Correlation","Well-designed controlled experiments","Surveys","Opinions"], "b", "Controlled experiments.", "Hard"),
    ("'Hawthorne effect' is:", ["Lighting effect","Behavior change from being observed","Chemical reaction","Measurement error"], "b", "Observation changes behavior.", "Hard"),
    ("'Anecdotal evidence' is:", ["Statistical data","Personal stories","Peer-reviewed","Experimental"], "b", "Stories, not data.", "Hard"),
    ("'Selection bias' occurs when:", ["Sample is random","Sample isn't representative","Data is clean","Results are clear"], "b", "Unrepresentative sample.", "Hard"),
    ("'Extrapolation' beyond data is:", ["Always valid","Potentially unreliable","Necessary","Forbidden"], "b", "Unreliable.", "Hard"),
    ("'Operationalization' means:", ["Ignoring variables","Defining how variables are measured","Cleaning data","Writing report"], "b", "Precise measurement definitions.", "Hard"),
    ("'Effect size' measures:", ["Statistical significance","Practical significance","Sample size","Duration"], "b", "Magnitude of effect.", "Hard"),
]
ch18 = [
    ("'Empirical' means:", ["Based on theory","Based on observation/experiment","Based on opinion","Based on tradition"], "b", "Observation-based.", "Easy"),
    ("'Bias' in social science means:", ["Objectivity","Systematic skew in data/interpretation","Accuracy","Randomness"], "b", "Skewed results.", "Easy"),
    ("'Demographics' refers to:", ["Opinions","Statistical data about populations","Feelings","Locations"], "b", "Population statistics.", "Easy"),
    ("'Qualitative' research uses:", ["Numbers","Interviews and observations","Only surveys","Only experiments"], "b", "Non-numerical methods.", "Easy"),
    ("'Quantitative' research uses:", ["Descriptions","Statistical analysis","Only interviews","Only observations"], "b", "Numbers.", "Easy"),
    ("'Survey' is best for collecting:", ["Lab data","Opinions and attitudes from many people","Genetic data","Chemical data"], "b", "Opinions.", "Easy"),
    ("'Correlation' in social science means:", ["Cause and effect","Relationship between variables","No relationship","Identical values"], "b", "Association.", "Easy"),
    ("'Case study' examines:", ["Large populations","One individual or small group in depth","Only statistics","Only experiments"], "b", "In-depth study.", "Easy"),
    ("'Variable' in social science:", ["Constant","Anything that can differ between subjects","Irrelevant","Always numerical"], "b", "Differing factor.", "Easy"),
    ("'Sample' refers to:", ["Entire population","Subset studied to represent population","The researcher","The theory"], "b", "Subset.", "Easy"),
    ("'Hypothesis' in social science:", ["Proven conclusion","Testable prediction","Opinion","Irrelevant"], "b", "Testable prediction.", "Medium"),
    ("'Representative sample' means:", ["Biased sample","Reflects population characteristics","Too small","Too large"], "b", "Matches population.", "Medium"),
    ("'Response bias' occurs when:", ["Everyone responds","Answers are influenced by question wording","No one responds","Data is perfect"], "b", "Question influence.", "Medium"),
    ("'Social desirability bias' means:", ["Answering honestly","Answering to seem favorable","Not answering","Random answering"], "b", "Favorable impression.", "Medium"),
    ("'Longitudinal' vs 'cross-sectional':", ["Same thing","Longitudinal follows over time","Cross-sectional follows over time","Neither tracks time"], "b", "Longitudinal = over time.", "Medium"),
    ("'Ethical considerations' in research include:", ["Profit","Informed consent and no harm","Speed","Publication"], "b", "Participant protection.", "Medium"),
    ("'Operational definition' means:", ["Vague description","Precise measurement of abstract concepts","No definition","Legal definition"], "b", "Concrete measurement.", "Medium"),
    ("'Ecological validity' means:", ["Lab-only results","Results applicable to real-world settings","Highly controlled","Theoretical"], "b", "Real-world applicability.", "Medium"),
    ("'Peer-reviewed journal' means:", ["Reviewed by friends","Reviewed by field experts","Not reviewed","Reviewed by students"], "b", "Expert evaluation.", "Medium"),
    ("'Theory' in social science:", ["Just a guess","Well-supported framework explaining phenomena","Irrelevant","Proven fact"], "b", "Framework.", "Medium"),
    ("'Triangulation' in social science:", ["Measuring triangles","Using multiple methods/sources","One method only","No verification"], "b", "Multiple approaches.", "Hard"),
    ("'Grounded theory' develops:", ["From top-down deduction","From data upward into theory","From intuition","From experiments only"], "b", "Inductive from data.", "Hard"),
    ("'Phenomenological' research studies:", ["Statistics only","Lived experiences and perceptions","Chemicals","Animals"], "b", "Subjective experience.", "Hard"),
    ("'Ethnography' involves:", ["Lab experiments","Immersion in a cultural group","Surveys only","Theory only"], "b", "Cultural immersion.", "Hard"),
    ("'Discourse analysis' examines:", ["Numbers","Language use in context","Chemicals","Physics"], "b", "Language patterns.", "Hard"),
    ("'Sampling frame' is:", ["The final sample","The list from which sample is drawn","The questionnaire","The conclusion"], "b", "Source list.", "Hard"),
    ("'Attrition' in longitudinal studies:", ["Starting the study","Participants dropping out over time","Data analysis","Publishing results"], "b", "Participant loss.", "Hard"),
    ("'Confound' vs 'mediator':", ["Same thing","Confounds obscure, mediators explain pathway","Mediators obscure","Confounds explain"], "b", "Different roles.", "Hard"),
    ("'Natural experiment' uses:", ["Lab conditions","Naturally occurring variations","No variables","No data"], "b", "Natural occurrences.", "Hard"),
    ("'Cultural relativism' in research:", ["Judging cultures by one standard","Understanding cultures on their own terms","Ignoring culture","Changing cultures"], "b", "Own terms.", "Hard"),
]
ch19 = [
    ("'Primary sources' in history:", ["Textbooks","Original documents from the period","Encyclopedias","Movies"], "b", "Original documents.", "Easy"),
    ("'Secondary sources' analyze:", ["Nothing","Primary sources","Only opinions","Only images"], "b", "Analyze primary sources.", "Easy"),
    ("'Bias' in historical documents means:", ["Objectivity","Author's perspective influencing account","Accuracy","Irrelevance"], "b", "Perspective influence.", "Easy"),
    ("'Chronological' means:", ["Random order","Time order","Alphabetical","By importance"], "b", "Time sequence.", "Easy"),
    ("'Context' in history refers to:", ["The text itself","Surrounding circumstances and conditions","Only dates","Only people"], "b", "Circumstances.", "Easy"),
    ("'Cause and effect' in history:", ["Rarely exists","Shows how events led to outcomes","Is always clear","Is irrelevant"], "b", "Events leading to outcomes.", "Easy"),
    ("'Periodization' means:", ["Writing periods","Dividing history into eras","Periodic tables","Random division"], "b", "Dividing into eras.", "Easy"),
    ("'Artifact' is:", ["A theory","A historical object from the past","A modern invention","A person"], "b", "Historical object.", "Easy"),
    ("'Treaty' in history is:", ["A battle","A formal agreement between nations","A type of food","A language"], "b", "Formal agreement.", "Easy"),
    ("'Revolution' means:", ["Small change","Fundamental overthrow of system","Gradual reform","Nothing new"], "b", "Fundamental change.", "Easy"),
    ("'Historiography' studies:", ["Battles","How history itself has been written and interpreted","Geography","Languages"], "b", "History of history.", "Medium"),
    ("'Perspective' in a source refers to:", ["The font","The author's viewpoint and position","The page layout","The publication date"], "b", "Viewpoint.", "Medium"),
    ("'Corroboration' means:", ["Contradicting sources","Confirming with multiple sources","Ignoring sources","Destroying sources"], "b", "Multiple confirmation.", "Medium"),
    ("'Anachronism' is:", ["Accurate dating","Something out of its proper time period","A type of ruler","A historical event"], "b", "Out of time.", "Medium"),
    ("'Inference' from a source:", ["Direct statement","Conclusion drawn from evidence","A question","A footnote"], "b", "Conclusion from evidence.", "Medium"),
    ("'Bias' in a photograph:", ["Never present","May be staged, cropped, or selected","Always obvious","Doesn't exist"], "b", "Can be manipulated.", "Medium"),
    ("'Oral history' is:", ["Written records","Accounts from people's memories","Archaeological finds","Government documents"], "b", "Memories.", "Medium"),
    ("'Economic factors' in history:", ["Irrelevant","Include trade, resources, and labor","Only money","Only prices"], "b", "Resource-related.", "Medium"),
    ("'Political context' includes:", ["Only elections","Government systems and power dynamics","Only wars","Only laws"], "b", "Power dynamics.", "Medium"),
    ("'Cultural factors' include:", ["Only art","Beliefs, values, and practices","Only religion","Only language"], "b", "Beliefs and practices.", "Medium"),
    ("'Sourcing' means:", ["Writing the source","Determining origin, purpose, and context of a source","Ignoring the source","Changing the source"], "b", "Origin and purpose.", "Hard"),
    ("'Close reading' of a document:", ["Skimming quickly","Careful, detailed textual analysis","Ignoring text","Only looking at images"], "b", "Detailed analysis.", "Hard"),
    ("'Counterfactual' history asks:", ["What happened?","What might have happened differently?","What will happen?","What didn't happen?"], "b", "Alternative scenarios.", "Hard"),
    ("'Material culture' refers to:", ["Ideas","Physical objects made by humans","Only food","Only buildings"], "b", "Physical objects.", "Hard"),
    ("'Postmodern' approach to history:", ["Accepts single objective truth","Questions grand narratives and objectivity","Ignores evidence","Uses only one source"], "b", "Questions narratives.", "Hard"),
    ("'Agency' in historical analysis:", ["Buildings only","Individuals' capacity to act and make choices","Government","Geography"], "b", "Individual capacity.", "Hard"),
    ("'Structural factors' in history:", ["Personal choices","Larger systems (economic, social, political)","Random events","Only wars"], "b", "Larger systems.", "Hard"),
    ("'Microhistory' focuses on:", ["Large nations","Small-scale events and individuals","Entire continents","Only kings"], "b", "Small-scale.", "Hard"),
    ("'Silences' in archives refer to:", ["No sound","Voices and perspectives absent from records","Loud events","Music"], "b", "Missing perspectives.", "Hard"),
    ("'Turning point' in history:", ["Any event","Moment fundamentally changing trajectory","Boring event","The end"], "b", "Fundamental change.", "Hard"),
]
ch20 = [
    ("'Setting' in literature refers to:", ["The characters","Time and place of the story","The plot","The author"], "b", "Time and place.", "Easy"),
    ("'Protagonist' is:", ["The villain","The main character","The setting","The theme"], "b", "Main character.", "Easy"),
    ("'Antagonist' is:", ["The hero","The opposing force","The narrator","The reader"], "b", "Opposing force.", "Easy"),
    ("'Narrator' is:", ["A character","The voice telling the story","The author always","The reader"], "b", "Telling voice.", "Easy"),
    ("'First person' uses:", ["He/she","I/we","You","They"], "b", "I/we.", "Easy"),
    ("'Third person' uses:", ["I/we","He/she/they","You","It only"], "b", "He/she/they.", "Easy"),
    ("'Metaphor' is:", ["A comparison using 'like'","A direct comparison without like/as","A sound effect","An exaggeration"], "b", "Direct comparison.", "Easy"),
    ("'Simile' is:", ["Direct comparison","Comparison using 'like' or 'as'","Contradiction","A repetition"], "b", "Using like/as.", "Easy"),
    ("'Symbolism' uses:", ["Real objects only","Objects to represent abstract ideas","Nothing","Only colors"], "b", "Representing ideas.", "Easy"),
    ("'Theme' is:", ["The setting","The central message or insight","A character","The plot"], "b", "Central message.", "Easy"),
    ("'Climax' is:", ["The beginning","The turning point of highest tension","The ending","The introduction"], "b", "Highest tension.", "Medium"),
    ("'Resolution' or 'denouement':", ["The beginning","Where conflicts are resolved","The climax","The introduction"], "b", "Conflicts resolved.", "Medium"),
    ("'Alliteration' repeats:", ["Vowel sounds at start","Consonant sounds at start of nearby words","Whole words","Sentences"], "b", "Starting consonants.", "Medium"),
    ("'Personification' gives:", ["Human traits to non-human things","Animal traits to humans","No traits","Mathematical traits"], "a", "Human qualities to non-human.", "Medium"),
    ("'Hyperbole' is:", ["Understatement","Extreme exaggeration","A quiet statement","A question"], "b", "Exaggeration.", "Medium"),
    ("'Understatement' is:", ["Exaggeration","Saying less than is true for effect","Being loud","Nothing"], "b", "Less than true.", "Medium"),
    ("'Oxymoron' combines:", ["Similar words","Contradictory terms","Numbers","Names"], "b", "Contradictions.", "Medium"),
    ("'Paradox' is:", ["A contradiction that reveals truth","A simple statement","A question","A lie"], "a", "Contradicting truth.", "Medium"),
    ("'Stream of consciousness' shows:", ["Organized thoughts","Unfiltered flow of a character's mind","The weather","The plot only"], "b", "Mind flow.", "Medium"),
    ("'Allegory' is:", ["A type of poem","Story where characters/events represent abstract ideas","A type of dialogue","A character type"], "b", "Extended symbolism.", "Medium"),
    ("'Archetype' is:", ["A new idea","A universally recognized symbol or character type","A setting","A font"], "b", "Universal pattern.", "Hard"),
    ("'Unreliable narrator' is:", ["Always truthful","Gives biased or inaccurate account","A robot","An animal"], "b", "Biased account.", "Hard"),
    ("'Intertextuality' refers to:", ["Single text","Relationship between texts and how they reference each other","Internal monologue","The setting"], "b", "Text references.", "Hard"),
    ("'Deconstruction' in literature:", ["Building up","Examining how texts undermine their own meanings","Destroying books","Simple reading"], "b", "Undermining meanings.", "Hard"),
    ("'Postcolonial' literature addresses:", ["Nothing","Legacy of colonialism and its effects","Only the future","Only nature"], "b", "Colonialism's legacy.", "Hard"),
    ("'Magic realism' blends:", ["Only reality","Realistic setting with magical elements","Only fantasy","No setting"], "b", "Real + magical.", "Hard"),
    ("'Narrative voice' refers to:", ["Volume","The perspective from which story is told","Literally speaking","The font"], "b", "Telling perspective.", "Hard"),
    ("'Motif' is:", ["A single symbol","A recurring element throughout a text","The ending","The author"], "b", "Recurring element.", "Hard"),
    ("'Didactic' literature aims to:", ["Entertain only","Teach a moral or lesson","Confuse","Anger"], "b", "Teach.", "Hard"),
    ("'Diegetic' elements exist:", ["Outside the story","Within the story's world","In the reader's mind","In the author's mind"], "b", "Within story world.", "Hard"),
]
ch21 = [
    ("'Revision' focuses on:", ["Spelling only","Big-picture content and structure","Grammar only","Punctuation only"], "b", "Content and structure.", "Easy"),
    ("'Editing' focuses on:", ["Content","Grammar, spelling, punctuation","Structure","Research"], "b", "Surface correctness.", "Easy"),
    ("'Peer review' means:", ["Teacher reads","Other students provide feedback","Self-review","No review"], "b", "Student feedback.", "Easy"),
    ("'Thesis revision' should:", ["Be deleted","Be refined for clarity and specificity","Be ignored","Be lengthened"], "b", "Refine.", "Easy"),
    ("'Topic sentence' revision:", ["Remove all","Ensure each paragraph has a clear focus","Make longer","Change font"], "b", "Clear focus.", "Easy"),
    ("'Transitions' in revision:", ["Remove all","Add to improve flow between ideas","Only use 'and'","Avoid"], "b", "Improve flow.", "Easy"),
    ("'Redundancy' means:", ["New information","Saying same thing twice","Good writing","Required"], "b", "Repetition.", "Easy"),
    ("'Clarity' in writing means:", ["Confusing","Easy to understand","Long sentences","Complex words"], "b", "Understandable.", "Easy"),
    ("'Conciseness' means:", ["Long-winded","Using few words effectively","Vague","Complex"], "b", "Brief.", "Easy"),
    ("'Audience awareness' means:", ["Ignoring readers","Tailoring writing to intended readers","Writing for self only","No audience"], "b", "Tailoring.", "Easy"),
    ("'Sentence variety' means:", ["Same length sentences","Mixing sentence structures and lengths","Only short sentences","Only long sentences"], "b", "Mixed structures.", "Medium"),
    ("'Parallel structure' in revision:", ["Mix forms","Balance grammatical forms in lists","Remove lists","Use one form only"], "b", "Balanced forms.", "Medium"),
    ("'Appropriate register' means:", ["Same for all writing","Matching formality to audience and purpose","Always formal","Always informal"], "b", "Match context.", "Medium"),
    ("'Specific evidence' vs 'vague generalities':", ["Same thing","Specific is better supported","Vague is better","No difference"], "b", "Better support.", "Medium"),
    ("'Strong introduction' strategies:", ["Start with dictionary","Start with hook and context","Start with conclusion","Start with 'I think'"], "b", "Hook + context.", "Medium"),
    ("'Effective conclusion' strategies:", ["Repeat introduction","Synthesize and leave lasting impression","Introduce new evidence","End abruptly"], "b", "Synthesize.", "Medium"),
    ("'Sentence fragment' fix:", ["Leave it","Add subject and/or verb","Remove it","Change font"], "b", "Complete it.", "Medium"),
    ("'Run-on sentence' fix:", ["Make longer","Use punctuation or conjunctions","Remove words","Ignore"], "b", "Punctuate.", "Medium"),
    ("'Comma splice' fix:", ["Add more commas","Use semicolon, conjunction, or period","Remove comma","Ignore"], "b", "Fix with tools.", "Medium"),
    ("'Word choice' revision:", ["Use biggest words","Choose precise, appropriate words","Use same words","Ignore"], "b", "Precise words.", "Medium"),
    ("'Reverse outlining' helps:", ["Add content","Check paragraph organization and flow","Delete everything","Change font"], "b", "Check organization.", "Hard"),
    ("'Rhetorical situation' includes:", ["Only the text","Writer, audience, purpose, and context","Only the reader","Only the topic"], "b", "All four elements.", "Hard"),
    ("'Kairos' in writing refers:", ["The longest word","Timeliness and appropriateness to moment","The font","The title"], "b", "Right moment.", "Hard"),
    ("'Ethos revision' means:", ["Remove credibility","Strengthen writer's credibility and trustworthiness","Add quotes","Change topic"], "b", "Build credibility.", "Hard"),
    ("'Pathos revision' means:", ["Remove emotion","Strengthen emotional connection with audience","Add statistics only","Be boring"], "b", "Emotional connection.", "Hard"),
    ("'Logos revision' means:", ["Add emotion","Strengthen logical reasoning and evidence","Remove evidence","Be vague"], "b", "Logic and evidence.", "Hard"),
    ("'Hedging' in academic writing:", ["Being dishonest","Using cautious language to qualify claims","Being overconfident","Being vague"], "b", "Cautious qualification.", "Hard"),
    ("'Metacommentary' is:", ["Regular text","Writer telling reader how to interpret the text","A comment by others","Nothing"], "b", "Guiding interpretation.", "Hard"),
    ("'Synthesis' in revision:", ["Combine sentences","Integrate multiple sources into coherent argument","Delete sources","Ignore sources"], "b", "Integrate sources.", "Hard"),
    ("'Counterargument integration' means:", ["Ignore opposition","Address and refute opposing views","Agree with all","Delete counterarguments"], "b", "Address and refute.", "Hard"),
]
ch22 = [
    ("'Piece of cake' means:", ["Literal cake","Something very easy","A dessert","Difficult task"], "b", "Very easy.", "Easy"),
    ("'Break a leg' means:", ["Get injured","Good luck","Run fast","Break something"], "b", "Good luck.", "Easy"),
    ("'Bite the bullet' means:", ["Eat metal","Face something difficult bravely","Bite something","Run away"], "b", "Face difficulty.", "Easy"),
    ("'Hit the books' means:", ["Physically hit books","Study hard","Read one book","Ignore studies"], "b", "Study hard.", "Easy"),
    ("'Under the weather' means:", ["Outside in rain","Feeling ill","Cold temperature","Happy"], "b", "Feeling sick.", "Easy"),
    ("'Cost an arm and a leg' means:", ["Physical injury","Very expensive","Cheap","Free"], "b", "Very expensive.", "Easy"),
    ("'Let the cat out of the bag' means:", ["Release a cat","Reveal a secret","Catch a cat","Buy a bag"], "b", "Reveal secret.", "Easy"),
    ("'Burning the midnight oil' means:", ["Starting a fire","Working late at night","Cooking","Sleeping"], "b", "Working late.", "Easy"),
    ("'Actions speak louder than words' means:", ["Being loud","What you do matters more than what you say","Words don't matter","Actions don't matter"], "b", "Doing > saying.", "Easy"),
    ("'The ball is in your court' means:", ["Playing sports","It's your turn to make a decision","Game over","Not your turn"], "b", "Your decision.", "Easy"),
    ("'Spill the beans' means:", ["Drop food","Reveal a secret","Cook beans","Eat quickly"], "b", "Reveal secret.", "Medium"),
    ("'Steal someone's thunder' means:", ["Make noise","Take credit for someone else's achievement","Steal thunder literally","Be loud"], "b", "Take credit.", "Medium"),
    ("'A blessing in disguise' means:", ["Disguised blessing","Something bad that turns out to be good","A costume","Bad luck"], "b", "Good from bad.", "Medium"),
    ("'Beat around the bush' means:", ["Gardening","Avoid getting to the point","Hit a bush","Be direct"], "b", "Avoid the point.", "Medium"),
    ("'Better late than never' means:", ["Never come","Doing something late is better than not at all","Always be late","Punctuality"], "b", "Late is better than never.", "Medium"),
    ("'Bite off more than you can chew' means:", ["Eat too much","Take on more than you can handle","Chew carefully","Small bites"], "b", "Overcommit.", "Medium"),
    ("'Burn bridges' means:", ["Build fires","Destroy relationships/connections","Cross bridges","Rebuild"], "b", "Destroy connections.", "Medium"),
    ("'Cut corners' means:", ["Trim edges","Do something poorly to save time/money","Be perfect","Cut paper"], "b", "Poor quality for speed.", "Medium"),
    ("'Go back to the drawing board' means:", ["Draw again","Start over with a new approach","Quit","Same plan"], "b", "Start over.", "Medium"),
    ("'Hit the nail on the head' means:", ["Use a hammer","Be exactly right","Miss completely","Hit yourself"], "b", "Exactly right.", "Medium"),
    ("'Burning bridges' vs 'mending fences' means:", ["Same thing","Destroying vs repairing relationships","Construction","Painting"], "b", "Opposite actions.", "Hard"),
    ("'Caught between a rock and a hard place' means:", ["Geology","Facing two equally difficult choices","Swimming","Climbing"], "b", "Difficult dilemma.", "Hard"),
    ("'Don't put all your eggs in one basket' means:", ["Cooking","Don't risk everything on one plan","Carry eggs","Buy baskets"], "b", "Diversify risk.", "Hard"),
    ("'Hit the ground running' means:", ["Fall","Start something with energy and competence","Exercise","Be lazy"], "b", "Strong start.", "Hard"),
    ("'Let sleeping dogs lie' means:", ["Pet dogs","Don't stir up trouble by bringing up old issues","Wake dogs","Ignore all problems"], "b", "Don't cause trouble.", "Hard"),
    ("'Nip something in the bud' means:", ["Gardening","Stop something early before it grows","Plant seeds","Ignore problems"], "b", "Stop early.", "Hard"),
    ("'Pull out all the stops' means:", ["Music only","Use every possible resource or effort","Give up","Be minimal"], "b", "Maximum effort.", "Hard"),
    ("'Throw in the towel' means:", ["Do laundry","Give up","Start fighting","Dry off"], "b", "Give up.", "Hard"),
    ("'Wild goose chase' means:", ["Hunting birds","A pointless or impossible pursuit","Easy task","Quick success"], "b", "Pointless pursuit.", "Hard"),
    ("'You can't have your cake and eat it too' means:", ["Baking","You can't have two mutually exclusive things","Dieting","Cooking"], "b", "Can't have both.", "Hard"),
]
