ch7 = [
    ("What does 'extensive' mean in 'extensive research'?", ["Expensive","Limited","Comprehensive","Experimental"], "c", "Extensive means comprehensive.", "Easy"),
    ("Which has a misplaced modifier?", ["Running quickly, the athlete won.","The teacher explained clearly.","Having finished homework, the TV was turned on.","The book on the shelf."], "c", "'Having finished' doesn't modify 'TV'.", "Easy"),
    ("Purpose of a topic sentence?", ["Provide examples","State main idea","Conclude essay","Ask question"], "b", "Introduces main idea.", "Easy"),
    ("'Despite' in 'Despite rain, event succeeded' indicates:", ["Cause","Time","Contrast","Sequence"], "c", "Contrast.", "Easy"),
    ("Synonym for 'benevolent'?", ["Cruel","Kind","Angry","Lazy"], "b", "Kind.", "Easy"),
    ("What is a counterargument?", ["Thesis","Supporting evidence","Opposing viewpoint","Conclusion"], "c", "Opposing view.", "Easy"),
    ("Prefix 'un-' in 'unhappy' means:", ["Again","Not","Before","After"], "b", "Not.", "Easy"),
    ("An 'inference' is:", ["Direct statement","Educated guess from text","Author's name","Page number"], "b", "Conclusion from evidence.", "Easy"),
    ("Which is an opinion not a fact?", ["Water boils at 100\u00b0C","Earth orbits Sun","Chocolate is best","Humans need oxygen"], "c", "Subjective.", "Easy"),
    ("Thesis statement purpose?", ["List sources","State main argument","Provide background","Summarize"], "b", "Central argument.", "Easy"),
    ("'Ambiguous' most likely means:", ["Clear","Vague","Hostile","Generous"], "b", "Multiple interpretations.", "Medium"),
    ("Author's critical tone is:", ["Joyful","Indignant","Indifferent","Humorous"], "b", "Indignant.", "Medium"),
    ("A 'concession' is:", ["Refusing to agree","Acknowledging valid opposing point","Changing thesis","Ignoring opposition"], "b", "Admits opponent's point.", "Medium"),
    ("Which transition signals cause-effect?", ["However","Furthermore","Therefore","Meanwhile"], "c", "Therefore.", "Medium"),
    ("'Elusive' means:", ["Easy to find","Hard to pin down","Aggressive","Transparent"], "b", "Difficult to catch.", "Medium"),
    ("Author's purpose means:", ["Main topic","Why the author wrote","Publication date","Vocabulary"], "b", "Why text exists.", "Medium"),
    ("A 'qualified' claim:", ["Makes no exceptions","Is absolutely asserted","Acknowledges limitations","Ignores evidence"], "c", "Recognizes limits.", "Medium"),
    ("'Tone' in a passage refers to:", ["Plot","Author's attitude","Setting","Font"], "b", "Attitude.", "Medium"),
    ("Textual evidence is:", ["Your opinion","Quote from passage","Dictionary definition","Peer summary"], "b", "Direct quotes.", "Medium"),
    ("A 'central idea' vs 'detail':", ["More specific","Main point","In footnotes","Numerical"], "b", "Main point.", "Medium"),
    ("Both-sided passage with preference is:", ["Purely expository","Comparative with倾向","Narrative","Chronological"], "b", "Compares then favors.", "Hard"),
    ("An 'implicit' assumption:", ["Clearly stated","Required but unstated","Contradicted","Conclusion"], "b", "Unstated but necessary.", "Hard"),
    ("Fallacy of authority:", ["Too many sources","Uncritically accepting expert","Peer-reviewed cites","Paraphrasing"], "b", "Uncritical acceptance.", "Hard"),
    ("Using 'we' and 'our' aims to:", ["Create distance","Build solidarity","Sound objective","Avoid responsibility"], "b", "Shared experience.", "Hard"),
    ("'Subtext' refers to:", ["Title","Implied but unstated meaning","Bibliography","Quotes"], "b", "Underlying meaning.", "Hard"),
    ("Rhetorical appeals are:", ["Grammar errors","Ethos, pathos, logos","Page numbers","Paragraph length"], "b", "Three classical appeals.", "Hard"),
    ("Ironic statement means:", ["Literally true","Means opposite","Well-researched","Written in verse"], "b", "Opposite of surface.", "Hard"),
    ("'Diction' analysis focuses on:", ["Sentence length","Word choice","Paragraph structure","Font"], "b", "Word choices.", "Hard"),
    ("Effective 'synthesis':", ["Lists summaries","Integrates multiple perspectives","Ignores contradiction","Uses one source"], "b", "Weaves sources together.", "Hard"),
    ("'Connotation' vs 'denotation':", ["Dictionary meaning","Emotional associations","Spelling","Grammar"], "b", "Emotional associations.", "Hard"),
]
ch8 = [
    ("Which is a complete sentence?", ["Running through park.","The dog barked loudly.","After rain stopped.","In the morning."], "b", "Subject + predicate.", "Easy"),
    ("Comma splice joins:", ["Two independent clauses","Dep + indep clause","Two nouns","Two adjectives"], "a", "Incorrect comma join.", "Easy"),
    ("'Their/there/they're' are:", ["Homophones","Synonyms","Antonyms","Onomatopoeia"], "a", "Sound alike.", "Easy"),
    ("Correct subject-verb agreement:", ["Group were tired","Neither was ready","Everyone is welcome","Dogs runs"], "c", "'Everyone' singular.", "Easy"),
    ("Semicolon joins:", ["Two related independent clauses","End sentence","List items","Indicate possession"], "a", "Related clauses.", "Easy"),
    ("'Affect' is typically:", ["Noun","Verb","Adjective","Adverb"], "b", "Verb = influence.", "Easy"),
    ("Correct apostrophe:", ["it's tail","childrens' toys","student's book","teacher's are"], "c", "Singular possessive.", "Easy"),
    ("'Who' vs 'whom': ___ did you call?", ["Who","Whom","Whose","Which"], "b", "Object form.", "Easy"),
    ("Thesis statement should be:", ["A question","Vague statement","Clear arguable claim","List of topics"], "c", "Specific debatable.", "Easy"),
    ("Compound sentence:", ["Although it rained...","Cat slept. Dog barked.","I like coffee, and she prefers tea.","Running fast..."], "c", "Two clauses + conjunction.", "Easy"),
    ("'Him and me went' errors in:", ["Spelling","Pronoun case","Verb tense","Punctuation"], "b", "Should be 'He and I'.", "Medium"),
    ("An 'appositive' is:", ["Verb form","Noun phrase renaming nearby noun","Adjective","Conjunction"], "b", "Additional identification.", "Medium"),
    ("Complex sentence:", ["Sun set. Stars appeared.","Went store and bought milk.","When bell rang, students rushed out.","She studied. She passed."], "c", "Dep + indep clause.", "Medium"),
    ("'Which' vs 'that': The book, __ I borrowed, is great.", ["That","Which","Who","Whom"], "b", "Nonrestrictive = which.", "Medium"),
    ("Dangling modifier:", ["Too long","Modified noun missing","Two modifiers conflict","Passive"], "b", "No logical noun.", "Medium"),
    ("Parallel structure:", ["Same word repeatedly","Balanced grammatical forms","Paragraphs","Simple sentences"], "b", "Same form in series.", "Medium"),
    ("'Farther' for:", ["Abstract","Physical distance","Time","Quantity"], "b", "Physical distance.", "Medium"),
    ("Em dash is for:", ["Possession","Range","Emphatic interruption","End sentence"], "c", "Add emphasis.", "Medium"),
    ("Passive voice:", ["Chef cooked meal","Meal was cooked by chef","Cooking took time","She enjoys cooking"], "b", "Subject receives action.", "Medium"),
    ("'i.e.' means:", ["For example","That is","And so forth","In addition"], "b", "That is.", "Medium"),
    ("Anacoluthon is:", ["Metaphor","Break in grammatical sequence","Alliteration","Hyperbole"], "b", "Sudden shift.", "Hard"),
    ("Periodic sentence delays main clause to:", ["Beginning","Middle","End","No main clause"], "c", "End.", "Hard"),
    ("Epanalepsis repeats at:", ["Beginning of clauses","Beginning and end of same clause","End of clauses","Middle"], "b", "Start and end.", "Hard"),
    ("Correct subjunctive?", ["If I was you","If I were you","If I am you","If I be you"], "b", "'Were' is subjunctive.", "Hard"),
    ("Zeugma:", ["Rhyme","One word modifying two differently","Consonant sounds","Rhetorical question"], "b", "Double meaning.", "Hard"),
    ("Chiasmus structure:", ["A-B, A-B","A-B, B-A","A-A, B-B","A-B-C, C-B-A"], "b", "Reversed pattern.", "Hard"),
    ("Gerund phrase functions as:", ["Adjective","Noun","Adverb","Preposition"], "b", "Acts as noun.", "Hard"),
    ("Antithesis contrasts:", ["Similar ideas","Opposite ideas in parallel","Cause-effect","Q and A"], "b", "Opposites balanced.", "Hard"),
    ("Singular 'they' in formal writing:", ["Always incorrect","Increasingly accepted","Only in dialogue","Replaced by he/she"], "b", "Widely accepted now.", "Hard"),
    ("Litotes expresses:", ["Strong negation","Subtle positive via double negative","Confusion","Extreme emphasis"], "b", "Understatement.", "Hard"),
]
ch9 = [
    ("Essay typically has:", ["1 paragraph","2 paragraphs","Intro, body, conclusion","Only thesis"], "c", "Three main parts.", "Easy"),
    ("Introduction should:", ["List evidence first","Grab attention and present thesis","Provide conclusion","Skip background"], "b", "Hook + thesis.", "Easy"),
    ("Thesis statement is:", ["First sentence only","Main claim","Conclusion","Question"], "b", "Central argument.", "Easy"),
    ("Body paragraphs each:", ["Cover multiple topics","Focus on one point","Repeat thesis","One sentence"], "b", "One main idea.", "Easy"),
    ("Conclusion should:", ["Introduce new evidence","Restate thesis in new words","Ask question","Start new argument"], "b", "Summarize.", "Easy"),
    ("Transitions like 'furthermore':", ["Confuse reader","Connect ideas","End essay","Lengthen intro"], "b", "Logical flow.", "Easy"),
    ("Evidence includes:", ["Opinions only","Facts, quotes, examples","Unrelated anecdotes","Nothing"], "b", "Support.", "Easy"),
    ("A 'hook':", ["Concludes essay","Captures attention","Restates thesis","Lists sources"], "b", "Draws readers in.", "Easy"),
    ("Revision involves:", ["Only spelling","Improving content, structure, clarity","Adding pages","Changing font"], "b", "Big picture.", "Easy"),
    ("Persuasive essay aims to:", ["Entertain","Convince of position","Describe process","Narrate story"], "b", "Change minds.", "Easy"),
    ("Expository essay:", ["Tells story","Explains or informs","Convinces","Expresses feelings"], "b", "Explains objectively.", "Medium"),
    ("Counterargument paragraph should:", ["Be omitted","Acknowledge and refute","Agree with opposition","Repeat thesis"], "b", "Address then counter.", "Medium"),
    ("Ethos refers to:", ["Emotional appeal","Author's credibility","Logical reasoning","Imagery"], "b", "Trustworthiness.", "Medium"),
    ("'Showing' means:", ["Stating facts directly","Sensory details and actions","Only dialogue","Avoiding descriptions"], "b", "Let readers experience.", "Medium"),
    ("Analytical essay requires:", ["Summarizing text","Breaking down and interpreting","Retelling plot","Writing review"], "b", "Examines how and why.", "Medium"),
    ("Literary analysis focuses on:", ["Plot summary","Author biography","Techniques and themes","Book reviews"], "c", "Craft and meaning.", "Medium"),
    ("Topic sentences should:", ["Be vague","Clearly state paragraph main point","Be longest","End paragraph"], "b", "Guide reader.", "Medium"),
    ("Argumentative vs expository:", ["Shorter","Defends specific position","No evidence","Fiction"], "b", "Takes and defends claim.", "Medium"),
    ("Integrating quotes:", ["Drop without context","Introduce, cite, explain","Only short quotes","Avoid quotes"], "b", "Quote sandwich.", "Medium"),
    ("Pathos appeals to:", ["Logic","Credibility","Emotions","Grammar"], "c", "Feelings.", "Medium"),
    ("Dialectical essay:", ["One side only","Thesis, antithesis, synthesis","Chronological","Only facts"], "b", "Opposing views toward resolution.", "Hard"),
    ("Synthesis essay:", ["One source","Combines multiple sources into new argument","Book review","Paraphrase"], "b", "New meaning from multiple texts.", "Hard"),
    ("Prolepsis is:", ["Flashback","Anticipating objections in advance","Repeating words","Metaphor"], "b", "Preempts counterarguments.", "Hard"),
    ("Enthymeme:", ["Complete syllogism","Implied premise","Metaphor","Conclusion without evidence"], "b", "Reader supplies premise.", "Hard"),
    ("Rogerian argument:", ["Attack opposition","Find common ground","Ignore opposition","Only emotions"], "b", "Seek compromise.", "Hard"),
    ("Compare/contrast organized:", ["Only point-by-point","Only block","Either method","Neither"], "c", "Both valid.", "Hard"),
    ("Polysyndeton uses:", ["No conjunctions","Multiple conjunctions close together","One long sentence","Only commas"], "b", "Repeated conjunctions.", "Hard"),
    ("Concession-rebuttal:", ["Ignores opposition","Acknowledges then refutes","Agrees completely","Only facts"], "b", "Builds credibility then counters.", "Hard"),
    ("Hedging in academic writing:", ["Dishonest","Cautious language to qualify","Avoids all claims","Overconfident"], "b", "Protects against overgeneralization.", "Hard"),
    ("Apophasis mentions by:", ["Directly stating","Claiming not to mention","Listing alphabetically","Repeating"], "b", "Pretends to avoid.", "Hard"),
]
ch10 = [
    ("'Amiable' means:", ["Hostile","Friendly","Boring","Lazy"], "b", "Friendly.", "Easy"),
    ("'Reluctant' means:", ["Eager","Willing","Unwilling","Excited"], "c", "Unwilling.", "Easy"),
    ("'Generous' is closest to:", ["Stingy","Kind and giving","Selfish","Quiet"], "b", "Giving.", "Easy"),
    ("'Dim' is opposite of:", ["Bright","Dark","Small","Fast"], "a", "Not bright.", "Easy"),
    ("'Vivid' means:", ["Dull","Bright and clear","Small","Soft"], "b", "Clear images.", "Easy"),
    ("'Swift' is synonym for:", ["Slow","Quick","Heavy","Weak"], "b", "Fast.", "Easy"),
    ("'Ample' means:", ["Tiny","Insufficient","More than enough","Exact"], "c", "Plentiful.", "Easy"),
    ("'Gratitude' means:", ["Anger","Thankfulness","Fear","Sadness"], "b", "Being grateful.", "Easy"),
    ("'Harsh' means:", ["Gentle","Cruel or severe","Smooth","Quiet"], "b", "Severe.", "Easy"),
    ("'Vast' means:", ["Tiny","Narrow","Extremely large","Dark"], "c", "Enormous.", "Easy"),
    ("'Ubiquitous' means:", ["Rare","Found everywhere","Hidden","Ancient"], "b", "Everywhere.", "Medium"),
    ("'Pragmatic' means:", ["Idealistic","Practical and realistic","Emotional","Theoretical"], "b", "Practical.", "Medium"),
    ("'Ephemeral' means:", ["Permanent","Lasting a short time","Colorful","Loud"], "b", "Short-lived.", "Medium"),
    ("'Ambiguous' means:", ["Clear-cut","Open to multiple interpretations","Aggressive","Transparent"], "b", "Unclear.", "Medium"),
    ("'Benevolent' means:", ["Cruel","Well-meaning and kindly","Lazy","Angry"], "b", "Kindly.", "Medium"),
    ("'Meticulous' means:", ["Careless","Extremely careful and precise","Messy","Quick"], "b", "Detail-oriented.", "Medium"),
    ("'Resilient' means:", ["Fragile","Able to recover quickly","Weak","Tall"], "b", "Bounces back.", "Medium"),
    ("'Lucid' means:", ["Confused","Clear and easy to understand","Dark","Loud"], "b", "Clearly expressed.", "Medium"),
    ("'Concise' means:", ["Long-winded","Brief and clear","Vague","Complex"], "b", "Brief.", "Medium"),
    ("'Opaque' means:", ["Transparent","Not able to be seen through","Bright","Thin"], "b", "Not see-through.", "Medium"),
    ("'Sycophant' means:", ["Leader","Flatterer","Rebel","Scholar"], "b", "Excessive flatterer.", "Hard"),
    ("'Equivocate' means:", ["State clearly","Use ambiguous language to mislead","Speak loudly","Remain silent"], "b", "Vague deliberately.", "Hard"),
    ("'Perfunctory' means:", ["Thorough","Done without care","Energetic","Detailed"], "b", "Without care.", "Hard"),
    ("'Capricious' means:", ["Steady","Given to sudden mood changes","Brave","Organized"], "b", "Fickle.", "Hard"),
    ("'Obsequious' means:", ["Independent","Excessively obedient","Proud","Rebellious"], "b", "Servile.", "Hard"),
    ("'Enervate' means:", ["Energize","Weaken or drain energy","Excite","Enrage"], "b", "Drains energy.", "Hard"),
    ("'Erudite' means:", ["Ignorant","Having great knowledge","Poor","Tall"], "b", "Scholarly.", "Hard"),
    ("'Soporific' means:", ["Exciting","Inducing sleep","Musical","Bright"], "b", "Causes drowsiness.", "Hard"),
    ("'Perspicacious' means:", ["Dull","Having keen insight","Noisy","Weak"], "b", "Insightful.", "Hard"),
    ("'Magnanimous' means:", ["Petty","Very generous and forgiving","Cruel","Lazy"], "b", "Forgiving.", "Hard"),
]
ch11 = [
    ("Bar chart best for comparing:", ["Trends over time","Categories","Parts of a whole","Data points"], "b", "Discrete categories.", "Easy"),
    ("Line graph shows:", ["Categories","Changes over time","Proportions","Distribution"], "b", "Trends.", "Easy"),
    ("Pie chart represents:", ["Individual values","Parts of a whole as %","Changes","Correlations"], "b", "Proportions.", "Easy"),
    ("Y-axis typically represents:", ["Categories","Dependent variable","Time","Labels"], "b", "Measured variable.", "Easy"),
    ("'Scale' on graph refers to:", ["Title","Range and intervals","Legend","Source"], "b", "Value range.", "Easy"),
    ("Histogram differs from bar chart by:", ["Colors","Frequency of continuous data","Circles","Only averages"], "b", "Continuous data.", "Easy"),
    ("'Legend' explains:", ["Title","Symbols or colors","X-axis","Source"], "b", "Visual symbols.", "Easy"),
    ("'Scatter plot' shows:", ["Parts of a whole","Relationships between variables","Trends only","Frequencies"], "b", "Correlations.", "Easy"),
    ("To find value on graph, check:", ["Title only","Axes and gridlines","Legend","Border"], "b", "Axes.", "Easy"),
    ("'Trend line' shows:", ["Exact points","General direction","Maximum","Minimum"], "b", "Overall pattern.", "Easy"),
    ("Y-axis starting at 50 instead of 0 may:", ["Be more accurate","Exaggerate differences","Show no data","Be simpler"], "b", "Misleading.", "Medium"),
    ("'Compound bar chart' shows:", ["One variable","Multiple variables across categories","Only averages","No labels"], "b", "Multiple series.", "Medium"),
    ("'Rate of change' from line graph:", ["Read title","Find slope","Count points","Check legend"], "b", "Slope = rise/run.", "Medium"),
    ("'Box plot' displays:", ["Individual points","Median, quartiles, range","Only mean","Frequency"], "b", "Five-number summary.", "Medium"),
    ("Comparing graphs, check:", ["Same colors","Comparable scales","Same title","Same data"], "b", "Consistent scales.", "Medium"),
    ("'Double line graph' compares:", ["One variable","Two sets over time","Proportions","Frequency"], "b", "Two variables same period.", "Medium"),
    ("'Slope' represents:", ["Y-intercept","Rate of change","Maximum","Title"], "b", "Change in y / change in x.", "Medium"),
    ("'Cumulative frequency graph' shows:", ["Individual values","Running total of frequencies","Only median","Parts of a whole"], "b", "Accumulated frequencies.", "Medium"),
    ("Close clustering on scatter plot =:", ["Weak","Strong","Negative","Zero"], "b", "Strong relationship.", "Medium"),
    ("'Relative frequency' is:", ["Actual count","Proportion of total","Sum of values","Average"], "b", "Count / total.", "Medium"),
    ("'Logarithmic scale' for data spanning:", ["Same value","Several orders of magnitude","Negative","Categorical"], "b", "Large ranges.", "Hard"),
    ("'Spurious correlation' means:", ["Proven cause-effect","Appear related but not causal","Perfect correlation","Missing data"], "b", "No causation.", "Hard"),
    ("Box plot outlier:", ["Inside box","Beyond 1.5\u00d7IQR","The median","The mean"], "b", "Outside whiskers.", "Hard"),
    ("Dual-axis graph caution:", ["No axes","Different scales distort","Only averages","No legend"], "b", "Scale distortion.", "Hard"),
    ("Normal distribution is:", ["Skewed left","Symmetric bell-shaped","Flat","Irregular"], "b", "Bell curve.", "Hard"),
    ("Pearson coefficient ranges:", ["0 to 1","\u22121 to 1","0 to 100","\u2212100 to 100"], "b", "\u22121 to 1.", "Hard"),
    ("Stacked area chart shows:", ["One variable","Parts contributing to whole over time","Individual points","Correlations"], "b", "Cumulative contributions.", "Hard"),
    ("Bubble chart adds third variable by:", ["Colors only","Varying bubble size","Changing axis","Text labels"], "b", "Bubble size.", "Hard"),
    ("'Data dredging' means:", ["Cleaning carefully","Finding patterns in noise","Too few variables","Reporting honestly"], "b", "p-hacking.", "Hard"),
    ("Time series decomposition separates into:", ["One component","Trend, seasonal, cyclical, irregular","Mean and variance","Two variables"], "b", "Four components.", "Hard"),
]
ch12 = [
    ("A 'claim' is:", ["Evidence","Statement requiring support","Conclusion only","Question"], "b", "Debatable assertion.", "Easy"),
    ("'Evidence' supports by:", ["Contradicting","Providing facts or examples","Ignoring","Changing topic"], "b", "Backs assertions.", "Easy"),
    ("An 'inference' is:", ["Stated fact","Conclusion from evidence","Direct quote","Question"], "b", "Beyond what's stated.", "Easy"),
    ("'Reliable source' is:", ["Personal blog","Peer-reviewed or authoritative","Anonymous","Outdated"], "b", "Credible.", "Easy"),
    ("'Correlation' means:", ["Cause and effect","Relationship between variables","Identical values","No relationship"], "b", "Association.", "Easy"),
    ("A thesis is supported by:", ["More theses","Reasons and evidence","Questions","Longer theses"], "b", "Supporting points.", "Easy"),
    ("'Reasoning' connects:", ["Unrelated ideas","Evidence to claim","Title to conclusion","Author to reader"], "b", "Evidence to argument.", "Easy"),
    ("A 'counterargument' is:", ["Support for thesis","Opposing viewpoint","Conclusion","Repetition"], "b", "Other side.", "Easy"),
    ("Citing sources is important because:", ["Looks impressive","Gives credit and allows verification","Fills pages","Required"], "b", "Acknowledges authors.", "Easy"),
    ("'Logical fallacy' is:", ["Strong evidence","Flaw in reasoning","Good argument","Type of evidence"], "b", "Error in logic.", "Easy"),
    ("Appeal to authority fallacy:", ["Experts cited properly","Irrelevant authority used","No sources","Evidence strong"], "b", "Wrong authority.", "Medium"),
    ("'Confirmation bias' means:", ["Being objective","Only seeking confirming info","Changing mind","Multiple sources"], "b", "Favors confirming evidence.", "Medium"),
    ("Strong vs weak argument:", ["More words","Evidence directly supports claim","More paragraphs","Emotional language"], "b", "Relevant evidence.", "Medium"),
    ("'Primary sources' are:", ["Summaries","Original documents or data","Textbook explanations","Wikipedia"], "b", "Firsthand accounts.", "Medium"),
    ("'Corroborating evidence' means:", ["Contradicting","Supporting from another source","First piece","Footnote"], "b", "Independent confirmation.", "Medium"),
    ("'Hasty generalization':", ["Large sample conclusion","Too few examples conclusion","Overwhelming evidence","No conclusion"], "b", "Insufficient evidence.", "Medium"),
    ("'Relevance' means evidence:", ["Is longest","Directly relates to claim","Famous author","Most recent"], "b", "Connects to argument.", "Medium"),
    ("'Slippery slope' assumes:", ["Logical middle ground","One event leads to extreme consequences","Nothing changes","Irrelevant evidence"], "b", "Unstoppable chain.", "Medium"),
    ("'Sufficient evidence' means:", ["One example","Enough to reasonably support claim","All possible evidence","No evidence"], "b", "Adequate amount.", "Medium"),
    ("'Objective' analysis:", ["Ignores evidence","Treats all evidence fairly","Only supports one side","Uses opinions"], "b", "Fair treatment.", "Medium"),
    ("'Burden of proof' lies with:", ["Audience","Person making the claim","Opposition","Nobody"], "b", "The claimant.", "Hard"),
    ("'Red herring' fallacy:", ["Strengthens argument","Diverts attention from main issue","Provides evidence","Concedes point"], "b", "Irrelevant diversion.", "Hard"),
    ("'Anecdotal evidence' is:", ["Statistical data","Personal story as proof","Research study","Controlled experiment"], "b", "Stories aren't proof.", "Hard"),
    ("'Straw man' fallacy:", ["Refutes actual argument","Misrepresents opponent's position","Agrees with opposition","Uses evidence"], "b", "Weakened version attack.", "Hard"),
    ("'Equivocation' fallacy:", ["Being clear","Using word with different meanings","Being silent","Using statistics"], "b", "Switching definitions.", "Hard"),
    ("'Necessary' condition:", ["Can be avoided","Must be present for outcome","Only condition","Guarantees outcome"], "b", "Without it, no outcome.", "Hard"),
    ("'Sufficient' condition:", ["Is optional","Alone guarantees outcome","Always needed","Prevents outcome"], "b", "Enough by itself.", "Hard"),
    ("'Abductive reasoning' goes from:", ["General to specific","Observation to best explanation","Specific to general","Cause to effect"], "b", "Most likely explanation.", "Hard"),
    ("Type I error:", ["Accepting true claim","Rejecting true claim","Rejecting false claim","Accepting false claim"], "b", "False positive.", "Hard"),
    ("Occam's Razor prefers:", ["Most complex","Fewest assumptions","Most evidence","Most popular"], "b", "Simplest adequate.", "Hard"),
]
ch13 = [
    ("2 pencils $1. 8 pencils?", ["$2","$4","$6","$8"], "b", "4\u00d7$1 = $4.", "Easy"),
    ("Recipe: 2 cups flour for 12 cookies. 24 cookies?", ["2","3","4","6"], "c", "4 cups.", "Easy"),
    ("Speed 60mph. Distance in 3hrs?", ["120","180","200","150"], "b", "180 miles.", "Easy"),
    ("5 machines make 100 parts. 1 machine?", ["10","20","25","50"], "b", "20 parts.", "Easy"),
    ("$3 for 6 apples. Price each?", ["$0.25","$0.50","$0.75","$1.00"], "b", "$0.50.", "Easy"),
    ("3 workers 4 days. 6 workers?", ["2 days","8 days","6 days","3 days"], "a", "2 days.", "Easy"),
    ("y = 3x, x = 4. y?", ["7","12","8","1"], "b", "12.", "Easy"),
    ("Boys:girls = 3:5. 24 boys. Girls?", ["30","40","45","35"], "b", "40.", "Easy"),
    ("200km, 50km/h. Time?", ["2","4","5","3"], "b", "4 hours.", "Easy"),
    ("Scale 1cm=5km. 8cm on map?", ["20","40","30","80"], "b", "40 km.", "Easy"),
    ("a/b=2/3, b=12. a?", ["6","8","18","24"], "b", "a=8.", "Medium"),
    ("Direct var: y=kx. y=10 when x=5. y when x=8?", ["12","16","14","18"], "b", "y=16.", "Medium"),
    ("Inverse var: y=k/x. y=4 when x=3. y when x=6?", ["2","8","6","4"], "a", "y=2.", "Medium"),
    ("3A=4B, A=16. B?", ["12","8","24","9"], "a", "B=12.", "Medium"),
    ("Map 1:25000. 3cm. Actual in meters?", ["750","1500","3000","75000"], "a", "750m.", "Medium"),
    ("Speed inversely with time. Time triples, speed:", ["Triples","Doubles","Divided by 3","Same"], "c", "1/3.", "Medium"),
    ("y \u221d x\u00b2. y=18 when x=3. y when x=5?", ["30","45","50","60"], "c", "50.", "Medium"),
    ("A \u221d B and \u221d 1/C, then A=k(B/C).", ["Always true","Only if k=1","Never true","Whole numbers only"], "a", "Definition.", "Medium"),
    ("Car uses 8gal for 240mi. Gallons for 360mi?", ["10","12","14","16"], "b", "12.", "Medium"),
    ("2/5 of number = 14. Number?", ["28","35","70","42"], "b", "35.", "Medium"),
    ("a:b=3:4, b:c=2:5. a:c?", ["3:10","6:20","3:5","15:8"], "a", "3:10.", "Hard"),
    ("y jointly as x and z\u00b2. y=24 when x=2,z=2. y when x=3,z=3?", ["54","81","108","162"], "b", "81.", "Hard"),
    ("Resistance \u221d length / area. Double length, halve area:", ["2x","4x","8x","Same"], "b", "4x.", "Hard"),
    ("A \u221d B/C. B doubles, C doubles. A:", ["Doubles","Stays same","Halves","Quadruples"], "b", "Unchanged.", "Hard"),
    ("x\u00b2y=kz\u00b3. x triples, z doubles. y changes by:", ["8/27","4/27","2/3","4/9"], "a", "8/27.", "Hard"),
    ("Gear teeth \u221d radius. A:20 teeth 60rpm. B:30 teeth?", ["40rpm","90rpm","30rpm","120rpm"], "a", "40 rpm.", "Hard"),
    ("Light intensity \u221d 1/d\u00b2. 100 at 2m. At 5m?", ["16","25","40","20"], "a", "16.", "Hard"),
    ("x \u221d y, x \u221d 1/z. x=6 when y=12,z=4. x when y=8,z=2?", ["12","8","6","4"], "a", "12.", "Hard"),
    ("Volume \u221d T/P. V=200 at T=300,P=2. V at T=600,P=4?", ["200","400","100","800"], "a", "200.", "Hard"),
    ("p \u221d q\u00b2r. p=40 when q=2,r=5. p when q=3,r=4?", ["72","90","60","108"], "a", "72.", "Hard"),
]
ch14 = [
    ("Ratio 8:12 simplified?", ["2:3","4:6","3:2","6:4"], "a", "GCF=4. 2:3.", "Easy"),
    ("3:5 = x:20. x?", ["8","12","15","25"], "b", "x=12.", "Easy"),
    ("12 boys, 18 girls. Boys to total?", ["2:3","3:5","2:5","1:2"], "b", "12:30=2:5.", "Easy"),
    ("Scale 1:1000. 5cm on map = ? cm actual", ["500","50","5000","50000"], "c", "5000 cm.", "Easy"),
    ("$15 buys 3kg. Cost per kg?", ["$3","$5","$10","$45"], "b", "$5.", "Easy"),
    ("Divide 60 in ratio 2:3?", ["24 and 36","20 and 40","30 and 30","12 and 48"], "a", "24, 36.", "Easy"),
    ("4 workers $800. 6 workers?", ["$1000","$1200","$1400","$1600"], "b", "$1200.", "Easy"),
    ("Circumference to diameter ratio?", ["\u03c0","2\u03c0","4\u03c0","1"], "a", "\u03c0.", "Easy"),
    ("Ratio 4:7, sum 44. Numbers?", ["16,28","12,32","20,24","8,36"], "a", "16, 28.", "Easy"),
    ("90 km/h = ? m/s", ["15","25","30","9"], "b", "25 m/s.", "Easy"),
    ("5:7 = 15:x. x?", ["18","21","25","35"], "b", "x=21.", "Medium"),
    ("Flour:sugar:butter = 3:1:2. 600g total. Sugar?", ["100g","150g","200g","300g"], "a", "100g.", "Medium"),
    ("y \u221d x. y=8 when x=4. y when x=10?", ["16","20","12","25"], "b", "y=20.", "Medium"),
    ("Triangle angles ratio 2:3:4. Largest?", ["60\u00b0","80\u00b0","100\u00b0","120\u00b0"], "b", "80\u00b0.", "Medium"),
    ("180km in 3hrs. Distance in 5hrs?", ["250","270","300","360"], "c", "300 km.", "Medium"),
    ("3:4:5 totaling 72. Middle part?", ["16","24","18","20"], "b", "24.", "Medium"),
    ("0.5:1.5 to integer form?", ["1:3","5:15","1:2","3:1"], "a", "1:3.", "Medium"),
    ("A:B=2:3, B:C=4:5. A:B:C?", ["8:12:15","2:3:5","6:9:10","4:6:5"], "a", "8:12:15.", "Medium"),
    ("Scale 1:50000. 10cm apart?", ["5km","50km","500km","0.5km"], "a", "5 km.", "Medium"),
    ("x:y=5:3, x+y=40. x?", ["20","25","30","15"], "b", "x=25.", "Medium"),
    ("a:b=3:5, b:c=7:9. a:c?", ["21:45","3:9","5:7","7:15"], "a", "21:45=7:15.", "Hard"),
    ("Sides 5:12:13, perimeter 150. Longest?", ["52","60","65","78"], "c", "65 cm.", "Hard"),
    ("Compound ratio 2:3 and 4:5?", ["6:8","8:15","2:5","4:15"], "b", "8:15.", "Hard"),
    ("AP with mean 11, ratio 5:11:17?", ["7,11,15","5,11,17","8,11,14","9,11,13"], "b", "5,11,17.", "Hard"),
    ("x:y:z=2:3:5, x+z=28. y?", ["10.5","12","14","21"], "b", "y=12.", "Hard"),
    ("Pipe divided 3:7, total 40m. Longer?", ["12m","20m","28m","16m"], "c", "28m.", "Hard"),
    ("4A=5B=6C, A+B+C=74. A?", ["30","24","20","36"], "a", "A=30.", "Hard"),
    ("Similar triangles area 16:25. Side ratio?", ["4:5","16:25","8:10","2:3"], "a", "4:5.", "Hard"),
    ("p:q=3:4, q:r=6:7. p:q:r?", ["9:12:14","3:4:7","18:24:28","6:8:14"], "a", "9:12:14.", "Hard"),
    ("Ratio 3:5. Add 6 to each, new ratio 5:7. Numbers?", ["9,15","6,10","12,20","15,25"], "a", "9, 15.", "Hard"),
]
