import json

questions = []

def add(sid, ch, qt, opts, cor, exp, diff):
    questions.append({
        "id": sid,
        "subject": "History",
        "stream": "Social Science",
        "chapter": ch,
        "yearEC": "2024 E.C.",
        "questionText": qt,
        "hasImage": False,
        "imagePlaceholder": "",
        "options": [
            {"id": "a", "text": opts[0]},
            {"id": "b", "text": opts[1]},
            {"id": "c", "text": opts[2]},
            {"id": "d", "text": opts[3]}
        ],
        "correctOptionId": cor,
        "explanation": exp,
        "difficulty": diff
    })

# ============================================================
# GRADE 10
# ============================================================

# --- Chapter 1: Development of Capitalism and Nationalism 1815-1914 ---
ch10_01 = "Grade 10 - Chapter 1: Development of Capitalism and Nationalism 1815-1914"
add("HIS-10-01-01",ch10_01,"Which event is widely considered the starting point of the Industrial Revolution?",["The invention of the steam engine by James Watt","The signing of the Treaty of Vienna","The French Revolution of 1789","The unification of Germany"],"a","James Watt improvement of the steam engine in the late 18th century was a key catalyst of the Industrial Revolution, transforming manufacturing and transportation.","Easy")
add("HIS-10-01-02",ch10_01,"What was the Congress of Vienna (1815) primarily concerned with?",["Redrawing the map of Europe after the Napoleonic Wars","Establishing the League of Nations","Ending the Atlantic slave trade","Creating the European Economic Community"],"a","The Congress of Vienna (1814-1815) aimed to restore stability and balance of power in Europe following the Napoleonic Wars.","Easy")
add("HIS-10-01-03",ch10_01,"Which ideology emphasizes the rights and identity of a particular nation or people?",["Nationalism","Socialism","Imperialism","Communism"],"a","Nationalism is a political ideology centered on loyalty and devotion to one nation, often driving independence or unification movements.","Easy")
add("HIS-10-01-04",ch10_01,"What type of economic system is characterized by private ownership of the means of production?",["Feudalism","Capitalism","Communism","Socialism"],"b","Capitalism is an economic system where private individuals or businesses own property and means of production, driven by profit motive.","Easy")
add("HIS-10-01-05",ch10_01,"Giuseppe Mazzini and Giuseppe Garibaldi are most associated with the unification of which country?",["Germany","France","Italy","Poland"],"c","Mazzini and Garibaldi were key leaders in the Risorgimento, the movement for Italian unification completed in 1871.","Easy")
add("HIS-10-01-06",ch10_01,"The Meiji Restoration of 1868 led to rapid modernization in which country?",["China","Japan","Korea","Thailand"],"b","The Meiji Restoration ended feudal rule in Japan and initiated sweeping reforms that modernized the economy, military, and political system.","Easy")
add("HIS-10-01-07",ch10_01,"What was the primary goal of the Monroe Doctrine (1823)?",["To promote free trade with Europe","To oppose European colonial intervention in the Americas","To support African independence movements","To establish a pan-European alliance"],"b","The Monroe Doctrine declared that further European colonization or interference in the Western Hemisphere would be viewed as hostile to the United States.","Easy")
add("HIS-10-01-08",ch10_01,"Which Latin American leader is known as the Liberator for his role in independence movements?",["Simon Bolivar","Jose de San Martin","Pedro I of Brazil","Benito Juarez"],"a","Simon Bolivar led the liberation of several South American countries from Spanish colonial rule and is celebrated as El Libertador.","Easy")
add("HIS-10-01-09",ch10_01,"What was the main consequence of the Zollverein (customs union) in Germany?",["It created a unified military force","It promoted economic integration among German states","It abolished serfdom across Germany","It established a common German religion"],"b","The Zollverein, established in 1834, removed trade barriers between German states and created a common market, laying groundwork for political unification.","Easy")
add("HIS-10-01-10",ch10_01,"The Qing Dynasty in China was weakened by which major conflict in the mid-19th century?",["The Franco-Prussian War","The Taiping Rebellion","The Russian Revolution","The Boer War"],"b","The Taiping Rebellion (1850-1864) was one of the deadliest conflicts in history, severely weakening the Qing Dynasty and contributing to the Century of Humiliation.","Easy")
add("HIS-10-01-11",ch10_01,"The Scramble for Africa was formalized at which international conference?",["Congress of Vienna (1815)","Berlin Conference (1884-1885)","Treaty of Versailles (1919)","Geneva Convention (1864)"],"b","The Berlin Conference (1884-1885) established rules for European colonization of Africa, formalizing the Scramble without African participation.","Medium")
add("HIS-10-01-12",ch10_01,"What was the significance of the Haitian Revolution (1791-1804)?",["It was the first successful slave revolt leading to an independent nation","It united all Caribbean islands under one government","It led to French withdrawal from the Americas","It inspired only local uprisings with no broader impact"],"a","The Haitian Revolution was the only successful large-scale slave revolt in history, establishing Haiti as the first independent Black republic.","Medium")
add("HIS-10-01-13",ch10_01,"How did the British East India Company contribute to the colonization of India?",["It acted as a trading company that gradually assumed political and military control","It served as a purely diplomatic mission","It was an Indian-led organization that invited British support","It only traded in spices and textiles without political involvement"],"a","The British East India Company transitioned from a commercial enterprise to a governing body using military force and political manipulation.","Medium")
add("HIS-10-01-14",ch10_01,"Otto von Bismarck policy of Blood and Iron referred to:",["Using diplomacy and cultural unity to unify Germany","Using military force and industrial power to achieve German unification","Establishing a democratic federation of German states","Creating an alliance with France against Austria"],"b","Bismarck believed that German unification would be achieved through wars (blood) and industrial strength (iron), not through parliamentary debate.","Medium")
add("HIS-10-01-15",ch10_01,"What economic concept did Adam Smith promote in The Wealth of Nations (1776)?",["Mercantilism","Free market capitalism","Command economy","Feudalism"],"b","Adam Smith advocated for free market capitalism, arguing that limited government intervention and competition would maximize economic prosperity.","Medium")
add("HIS-10-01-16",ch10_01,"The Sepoy Mutiny of 1857 in India resulted in:",["Indian independence from Britain","The end of Mughal rule and direct British Crown administration","The establishment of a democratic Indian government","The withdrawal of the British East India Company"],"b","The Sepoy Mutiny led to the dissolution of the East India Company, the end of the Mughal Dynasty, and direct British Crown rule (the British Raj).","Medium")
add("HIS-10-01-17",ch10_01,"Which European power controlled the largest colonial empire in Africa by 1914?",["Britain","France","Germany","Belgium"],"b","France controlled the largest colonial empire in Africa by area, with territories spanning West, Central, and North Africa.","Medium")
add("HIS-10-01-18",ch10_01,"The concept of Social Darwinism was used to justify:",["Workers rights and labor unions","European imperialism and racial hierarchies","Womens suffrage movements","Democratic governance in colonies"],"b","Social Darwinism misapplied Darwins theory of natural selection to human societies, claiming European superiority to justify colonial domination.","Medium")
add("HIS-10-01-19",ch10_01,"The Young Turk Revolution of 1908 occurred in which empire?",["The Russian Empire","The Ottoman Empire","The Austro-Hungarian Empire","The Persian Empire"],"b","The Young Turk Revolution of 1908 sought to restore the Ottoman constitution and establish a more modern, constitutional government.","Medium")
add("HIS-10-01-20",ch10_01,"What was the primary cause of the Boer Wars (1880-1881 and 1899-1902)?",["Conflict over diamond and gold deposits in South Africa","Religious differences between Catholics and Protestants","Territorial disputes with Germany","Resistance to French colonial rule"],"a","The Boer Wars were fought between Britain and the Boer republics largely over control of lucrative gold and diamond resources.","Medium")
add("HIS-10-01-21",ch10_01,"How did the Suez Canal (opened 1869) impact European imperialism?",["It reduced European interest in Africa","It created a strategic trade route that increased British and French interests in Egypt and East Africa","It eliminated the need for sea trade between Europe and Asia","It was built entirely by African labor without European involvement"],"b","The Suez Canal dramatically shortened the sea route between Europe and Asia, making Egypt strategically vital and intensifying imperial competition.","Hard")
add("HIS-10-01-22",ch10_01,"The ideology of Pan-Slavism contributed to tensions leading to which major conflict?",["The Napoleonic Wars","World War I","The American Civil War","The Franco-Prussian War"],"b","Pan-Slavism promoted unity among Slavic peoples and intensified rivalries between Russia and Austria-Hungary in the Balkans, contributing to WWI.","Hard")
add("HIS-10-01-23",ch10_01,"What was the significance of the Revolutions of 1848 in Europe?",["They led to immediate unification of all European states","They were widespread liberal and nationalist uprisings that led to long-term political reforms","They resulted in the creation of the European Union","They only affected countries outside Europe"],"b","The Revolutions of 1848 swept across Europe demanding constitutional governments and national self-determination, accelerating political reforms.","Hard")
add("HIS-10-01-24",ch10_01,"Which factor most directly enabled European imperial expansion in the late 19th century?",["Decline in European military technology","Advances in medicine, weaponry, and transportation technology","Loss of European naval power","Decrease in European population and resources"],"b","Technological advances like the Maxim gun, quinine, steamships, and railways gave Europeans overwhelming advantages in colonizing Africa and Asia.","Hard")
add("HIS-10-01-25",ch10_01,"The Berlin Conference of 1884-1885 is significant because it:",["Granted independence to African states","Established rules for the partition of Africa among European powers without African representation","Created the first African parliament","Ended the Atlantic slave trade"],"b","The Berlin Conference established the principle of effective occupation and drew boundaries across Africa without any African input.","Hard")
add("HIS-10-01-26",ch10_01,"What role did Cecil Rhodes play in African colonization?",["He was an African leader who resisted colonization","He was a British imperialist who expanded British territory in southern Africa and founded Rhodesia","He established the first African university","He led the anti-colonial resistance in South Africa"],"b","Cecil Rhodes was a British mining magnate and politician who championed British imperialism in Africa, founding Rhodesia and the De Beers diamond company.","Hard")
add("HIS-10-01-27",ch10_01,"The concept of civilizing mission as used by European imperialists refers to:",["The genuine desire to educate colonized peoples","The ideological justification that Europeans had a duty to spread Western culture and Christianity","A movement led by colonized peoples for self-improvement","An international aid program for developing nations"],"b","The civilizing mission (mission civilisatrice) was a paternalistic ideology used to justify imperialism by claiming Europeans had a moral duty to bring civilization.","Hard")
add("HIS-10-01-28",ch10_01,"How did industrialization affect class structures in Europe during the 19th century?",["It eliminated all social classes","It created a new industrial working class (proletariat) and a wealthy industrial middle class (bourgeoisie)","It made everyone equally wealthy","It strengthened the feudal aristocracy"],"b","Industrialization transformed European society by creating new class divisions: the industrial bourgeoisie who owned factories, and the urban working class.","Hard")
add("HIS-10-01-29",ch10_01,"The Triple Alliance (1882) consisted of which three powers?",["Britain, France, Russia","Germany, Austria-Hungary, Italy","Germany, France, Italy","Britain, Germany, Russia"],"b","The Triple Alliance was formed in 1882 between Germany, Austria-Hungary, and Italy, contributing to the alliance system leading to WWI.","Hard")
add("HIS-10-01-30",ch10_01,"Which event demonstrated the vulnerability of European powers before World War I?",["The Congress of Vienna","The Italian unification","The defeat of Italy by Ethiopia at the Battle of Adwa (1896)","The opening of the Suez Canal"],"c","Ethiopias victory over Italy at Adwa in 1896 demonstrated an African nation could defeat a European colonial power, inspiring anti-colonial movements.","Hard")

# --- Chapter 2: Africa and the Colonial Experience (1880s-1960s) ---
ch10_02 = "Grade 10 - Chapter 2: Africa and the Colonial Experience (1880s-1960s)"
add("HIS-10-02-01",ch10_02,"In which year did the Berlin Conference take place?",["1870","1884-1885","1914","1960"],"b","The Berlin Conference was held from November 1884 to February 1885, establishing rules for the European colonization of Africa.","Easy")
add("HIS-10-02-02",ch10_02,"The Scramble for Africa refers to:",["African nations competing for trade routes","European powers competing to colonize African territories","African independence movements","The internal migration of African peoples"],"b","The Scramble for Africa was the rapid invasion, occupation, and colonization of African territory by European powers during the New Imperialism period.","Easy")
add("HIS-10-02-03",ch10_02,"Which African country successfully resisted European colonization at the Battle of Adwa in 1896?",["Nigeria","Kenya","Ethiopia","Ghana"],"c","Ethiopia defeated Italy at the Battle of Adwa in 1896, remaining one of only two African nations to avoid European colonization.","Easy")
add("HIS-10-02-04",ch10_02,"What was the main purpose of the colonial system of indirect rule?",["To grant full independence to local leaders","To govern through existing local leaders and structures","To eliminate all traditional leadership","To establish democratic elections"],"b","Indirect rule, practiced especially by Britain, governed colonies through existing traditional rulers who acted as intermediaries for the colonial administration.","Easy")
add("HIS-10-02-05",ch10_02,"Which European country primarily used the policy of assimilation in its African colonies?",["Britain","Germany","France","Belgium"],"c","France pursued assimilation, aiming to transform colonized Africans into French citizens who adopted French language, culture, and institutions.","Easy")
add("HIS-10-02-06",ch10_02,"The Mau Mau Uprising (1952-1960) took place in which African colony?",["South Africa","Kenya","Nigeria","Egypt"],"b","The Mau Mau Uprising was an anti-colonial revolt in Kenya against British rule, primarily fought by the Kikuyu people over land rights.","Easy")
add("HIS-10-02-07",ch10_02,"What is the term for the brutal exploitation system used by King Leopold II in the Congo Free State?",["Sharecropping","Corvée labor","The rubber terror","The plantation system"],"c","King Leopold II regime in the Congo Free State used extreme forced labor and brutality to extract rubber and ivory, resulting in millions of deaths.","Easy")
add("HIS-10-02-08",ch10_02,"In which year did Ghana become the first sub-Saharan African country to gain independence?",["1952","1957","1960","1963"],"b","Ghana, formerly the Gold Coast, gained independence on March 6, 1957, under Kwame Nkrumah, becoming the first sub-Saharan African nation to achieve independence.","Easy")
add("HIS-10-02-09",ch10_02,"What economic system did most European powers impose on their African colonies?",["Industrialization","Cash crop and raw material extraction","Free market capitalism","Communal farming"],"b","Colonial economies were structured to extract raw materials and cash crops for European industries, making colonies economically dependent on the metropole.","Easy")
add("HIS-10-02-10",ch10_02,"Which of the following was a method used by colonial powers to maintain control in Africa?",["Establishing democratic parliaments","Creating artificial borders that divided ethnic groups","Promoting African cultural identity","Encouraging trade between African nations"],"b","Colonial powers drew arbitrary borders at the Berlin Conference that often split ethnic groups and forced rival groups together, creating lasting conflicts.","Easy")
add("HIS-10-02-11",ch10_02,"Who was the leader of the anti-colonial movement in Ghana?",["Jomo Kenyatta","Patrice Lumumba","Kwame Nkrumah","Nelson Mandela"],"c","Kwame Nkrumah led Ghana to independence in 1957 and became a prominent advocate for Pan-Africanism and African liberation from colonialism.","Medium")
add("HIS-10-02-12",ch10_02,"The concept of divide and rule in colonial Africa involved:",["Unifying different ethnic groups under one leader","Exploiting ethnic differences to prevent unified resistance","Granting equal rights to all ethnic groups","Encouraging trade between different colonies"],"b","Colonial powers deliberately exploited and exacerbated ethnic divisions to prevent unified African resistance, favoring certain groups over others.","Medium")
add("HIS-10-02-13",ch10_02,"What was the primary impact of colonial education systems in Africa?",["They promoted African indigenous knowledge systems","They produced a westernized elite while limiting access to education for the masses","They provided universal free education to all Africans","They taught entirely in local African languages"],"b","Colonial education was limited in scope, produced a small westernized administrative class, and was conducted in European languages, marginalizing indigenous knowledge.","Medium")
add("HIS-10-02-14",ch10_02,"Which event is known as The Year of Africa?",["1957","1960","1963","1990"],"b","1960 is called The Year of Africa because seventeen African nations gained independence in that single year, marking a peak in decolonization.","Medium")
add("HIS-10-02-15",ch10_02,"What was the Casablanca Groups position on African independence?",["Immediate and total liberation of all African territories","Gradual independence through negotiation with colonial powers","Maintenance of the colonial system","Isolation of African states from world affairs"],"a","The Casablanca Group advocated for immediate and complete liberation of all African territories and a unified African political stance.","Medium")
add("HIS-10-02-16",ch10_02,"The Sharpeville Massacre (1960) occurred in which country?",["Kenya","Nigeria","South Africa","Algeria"],"c","The Sharpeville Massacre on March 21, 1960, saw South African police fire on unarmed protesters, killing 69 and drawing international condemnation of apartheid.","Medium")
add("HIS-10-02-17",ch10_02,"What was the primary objective of the Organization of African Unity (OAU) founded in 1963?",["To promote trade among African countries","To support the liberation of still-colonized African territories and promote unity","To establish a single African government","To create a military alliance against the Soviet Union"],"b","The OAU was founded in Addis Ababa in 1963 with the primary goals of promoting African unity, supporting decolonization, and respecting sovereignty.","Medium")
add("HIS-10-02-18",ch10_02,"Which of the following was a consequence of colonial border drawing in Africa?",["Ethnic groups were perfectly preserved within national boundaries","It created ethnic tensions and border disputes that persist today","It led to the creation of ethnically homogeneous states","It had no lasting impact on African politics"],"b","The arbitrary colonial borders split ethnic groups, created artificial states, and planted seeds of conflict that continue to affect African politics.","Medium")
add("HIS-10-02-19",ch10_02,"The Algerian War of Independence (1954-1962) was fought against which colonial power?",["Britain","Spain","France","Portugal"],"c","Algeria fought a brutal war of independence against France from 1954 to 1962, one of the most violent decolonization struggles in African history.","Medium")
add("HIS-10-02-20",ch10_02,"What was the role of missionary activities in colonial Africa?",["They promoted African traditional religions","They spread Christianity, provided education, and often served as agents of cultural change","They opposed all forms of colonial education","They worked exclusively to protect African land rights"],"b","Missionaries played a complex role: they established schools and hospitals but also promoted European culture and Christianity, sometimes undermining indigenous traditions.","Medium")
add("HIS-10-02-21",ch10_02,"How did the colonial cash crop system affect African food security?",["It improved food production across the continent","It diverted land and labor from food production to export crops, increasing food insecurity","It had no effect on food production","It encouraged diversification of African diets"],"b","Colonial cash crop policies prioritized export commodities like cocoa, coffee, and cotton over food crops, reducing local food production and increasing dependency.","Hard")
add("HIS-10-02-22",ch10_02,"The Mau Mau rebellion in Kenya was primarily driven by:",["Religious differences between Christians and Muslims","Kikuyu grievances over land dispossession and political marginalization","Opposition to the English language","Disputes over trade routes with Tanzania"],"b","The Mau Mau Uprising was primarily driven by Kikuyu grievances over loss of ancestral lands to white settlers and exclusion from political power.","Hard")
add("HIS-10-02-23",ch10_02,"Which of the following best describes the impact of the hut tax imposed by colonial governments?",["It encouraged communal living traditions","It forced Africans into the cash economy through wage labor to pay the tax","It reduced the demand for labor in mines and plantations","It had no significant economic impact"],"b","The hut tax required Africans to pay money, not goods, forcing them into wage labor on colonial mines, plantations, and infrastructure projects.","Hard")
add("HIS-10-02-24",ch10_02,"What was the significance of the Bandung Conference (1955) for Africa?",["It was a meeting of European colonial powers","It brought together Asian and African leaders to promote cooperation and oppose colonialism","It established the United Nations","It was a meeting of African chiefs to discuss land rights"],"b","The Bandung Conference of 1955 brought together leaders from 29 Asian and African countries, including Haile Selassie, to promote Afro-Asian solidarity.","Hard")
add("HIS-10-02-25",ch10_02,"What distinguishes the Belgian colonial administration from other colonial powers in Africa?",["It was the most democratic colonial system","It provided extensive education and political training for independence","It offered virtually no education or political preparation for independence","It allowed complete cultural freedom to colonized peoples"],"c","Belgiums colonial administration in the Congo and Ruanda-Urundi provided minimal education and political preparation, leaving territories severely underprepared for independence.","Hard")
add("HIS-10-02-26",ch10_02,"The Union Miniere du Haut-Katanga was significant because it:",["Was an African-owned mining company","Was a Belgian mining corporation that exploited Congos mineral wealth","Was an independence movement in the Congo","Was a farming cooperative in Central Africa"],"b","The Union Miniere du Haut-Katanga was a Belgian mining company that extracted vast mineral wealth from the Congo, exemplifying colonial economic exploitation.","Hard")
add("HIS-10-02-27",ch10_02,"How did the colonial plantation system affect land ownership patterns in Africa?",["It redistributed land equally among all Africans","It alienated communal land to European settlers and corporations","It had no impact on traditional land tenure systems","It strengthened traditional communal land ownership"],"b","Colonial plantation systems alienated communal African lands to European settlers and corporations, displacing communities and undermining traditional land tenure.","Hard")
add("HIS-10-02-28",ch10_02,"What was the significance of the Accra Conference of 1958?",["It was attended by European colonial administrators","It was the first conference of independent African states, organized by Nkrumah","It established the British Empire","It was a meeting about trade with Asia"],"b","The Accra Conference of 1958 was the first All-African Peoples Conference, bringing together leaders of independent nations and independence movements.","Hard")
add("HIS-10-02-29",ch10_02,"What long-term economic structure did colonialism create in Africa?",["Self-sufficient industrial economies","Export-oriented economies dependent on the export of raw materials and import of manufactured goods","Fully diversified economies with balanced trade","Isolated economies with no external trade"],"b","Colonialism created dependent economies in Africa that exported raw materials and imported manufactured goods, a pattern that persists in many countries today.","Hard")
add("HIS-10-02-30",ch10_02,"Which of the following best describes the legacy of colonial language policies in Africa?",["They preserved all indigenous African languages","They created linguistic fragmentation and marginalized indigenous languages while promoting European languages","They had no lasting effect on African languages","They unified all African nations under one language"],"b","Colonial language policies imposed European languages in administration and education, marginalizing indigenous languages and creating linguistic divisions.","Hard")

# --- Chapter 3: Social, Economic and Political Developments in Ethiopia mid 19th C to 1941 ---
ch10_03 = "Grade 10 - Chapter 3: Social, Economic and Political Developments in Ethiopia mid 19th C to 1941"
add("HIS-10-03-01",ch10_03,"Who was the Emperor of Ethiopia during the Battle of Adwa (1896)?",["Menelik II","Haile Selassie","Tewodros II","Yohannes IV"],"a","Emperor Menelik II led Ethiopia to victory against Italy at the Battle of Adwa on March 1, 1896, preserving Ethiopian independence.","Easy")
add("HIS-10-03-02",ch10_03,"The Treaty of Wuchale (1889) was signed between Ethiopia and which country?",["Britain","France","Italy","Germany"],"c","The Treaty of Wuchale (1889) was signed between Ethiopia and Italy. A dispute over its Italian and Amharic versions led to the Italo-Ethiopian War.","Easy")
add("HIS-10-03-03",ch10_03,"Emperor Tewodros II is known for:",["Leading Ethiopia to victory at Adwa","Attempting to modernize Ethiopia and unify the country","Establishing the Italian colony in Ethiopia","Signing the Treaty of Wuchale"],"b","Tewodros II (r. 1855-1868) is remembered as a modernizer who attempted to centralize authority and end the Zemene Mesafint.","Easy")
add("HIS-10-03-04",ch10_03,"What was the Zemene Mesafint (Era of Princes) in Ethiopian history?",["A period of strong centralized imperial rule","A period of regional warlord dominance with weak central authority","The Italian occupation of Ethiopia","The golden age of Ethiopian trade"],"b","The Zemene Mesafint (c. 1769-1855) was a period when regional nobles and warlords held real power while emperors were mere figureheads in Gondar.","Easy")
add("HIS-10-03-05",ch10_03,"Haile Selassie became Emperor of Ethiopia in which year?",["1896","1916","1930","1941"],"c","Haile Selassie was crowned Emperor of Ethiopia on November 2, 1930, following a period as regent from 1916.","Easy")
add("HIS-10-03-06",ch10_03,"The Italian occupation of Ethiopia lasted from 1936 to which year?",["1940","1941","1945","1950"],"b","Italy occupied Ethiopia from 1936 to 1941, when Ethiopian forces with British assistance liberated the country.","Easy")
add("HIS-10-03-07",ch10_03,"Emperor Yohannes IV died in which battle?",["Battle of Adwa","Battle of Gallabat","Battle of Maqdala","Battle of Dogali"],"b","Emperor Yohannes IV died at the Battle of Gallabat in 1889 fighting against Mahdist Sudanese forces.","Easy")
add("HIS-10-03-08",ch10_03,"What was the Arbegnoch (patriot) movement?",["A religious movement in the 19th century","A mass resistance movement against Italian occupation","A trade route between Ethiopia and the Red Sea","A political party founded by Haile Selassie"],"b","The Arbegnoch (patriot) movement was a widespread Ethiopian resistance against Italian occupation from 1936 to 1941.","Easy")
add("HIS-10-03-09",ch10_03,"The Battle of Adwa was significant because:",["It marked the beginning of Italian colonization of Ethiopia","It preserved Ethiopian independence and inspired anti-colonial movements worldwide","It was fought between Ethiopia and Britain","It established the League of Nations"],"b","The Battle of Adwa (1896) was a decisive Ethiopian victory that preserved sovereignty and became a symbol of African resistance to colonialism.","Easy")
add("HIS-10-03-10",ch10_03,"Which emperor ended the Zemene Mesafint and reunified Ethiopia?",["Haile Selassie","Menelik II","Tewodros II","Yohannes IV"],"c","Tewodros II (r. 1855-1868) is credited with ending the Zemene Mesafint by defeating regional warlords and reuniting the Ethiopian empire.","Easy")
add("HIS-10-03-11",ch10_03,"What was Menelik IIs strategy for modernizing Ethiopias military?",["Relying solely on traditional weapons","Importing modern European weapons and training soldiers","Hiring Italian military advisors exclusively","Disbanding the army after Adwa"],"b","Menelik II imported modern European weapons from France, Russia, and other countries and established a modernized army that proved decisive at Adwa.","Medium")
add("HIS-10-03-12",ch10_03,"The Treaty of Addis Ababa (1896) ended which conflict?",["The Mahdist invasion","The First Italo-Ethiopian War","The Italian occupation","The Oromo conflicts"],"b","The Treaty of Addis Ababa (October 26, 1896) officially ended the First Italo-Ethiopian War, recognizing Ethiopias full sovereignty and independence.","Medium")
add("HIS-10-03-13",ch10_03,"What was the significance of Haile Selassies speech to the League of Nations in 1936?",["He announced Ethiopias alliance with Italy","He appealed for international help against Italian aggression and warned of collective security failure","He declared war on Britain","He requested Italian investment in Ethiopia"],"b","Haile Selassies 1936 speech condemned Italian aggression, exposed the failure of collective security, and warned other nations would face similar fates.","Medium")
add("HIS-10-03-14",ch10_03,"The construction of the Djibouti-Addis Ababa railway served which primary purpose?",["To connect Ethiopian churches","To provide Ethiopia with access to the sea for trade","To facilitate Italian military invasion","To transport coffee within Ethiopia only"],"b","The Djibouti-Addis Ababa railway, completed in 1917, was crucial for Ethiopias trade, connecting the capital to the port of Djibouti and the outside world.","Medium")
add("HIS-10-03-15",ch10_03,"What was the role of Ras Alula in Ethiopian history?",["He was an Italian colonial governor","He was a brilliant military commander who fought against the Italians and Mahdists","He was a British diplomat in Ethiopia","He was a French trader in Addis Ababa"],"b","Ras Alula Engida was one of Ethiopias greatest military leaders, fighting against Italian expansion at Dogali (1887) and the Mahdists at Kufit (1885).","Medium")
add("HIS-10-03-16",ch10_03,"How did Ethiopia benefit from modern infrastructure under Menelik II?",["It had no impact on the economy","It improved communication, trade, and facilitated the expansion of Addis Ababa as a capital","It was built entirely by Italian labor","It only benefited foreign traders"],"b","Menelik II built roads, the telegraph, and Addis Ababa as the new capital, improving internal communication and trade and establishing Ethiopia as a modern state.","Medium")
add("HIS-10-03-17",ch10_03,"What was the primary motivation behind Italys invasion of Ethiopia in 1935?",["To spread democracy","To avenge the defeat at Adwa and establish an East African empire","To protect Ethiopian sovereignty","To promote Pan-Africanism"],"b","Mussolinis Italy invaded Ethiopia in 1935 seeking revenge for the humiliating defeat at Adwa in 1896 and to build an East African empire.","Medium")
add("HIS-10-03-18",ch10_03,"What was the significance of the 1931 Constitution of Ethiopia?",["It established a communist government","It was Ethiopias first written constitution, establishing a constitutional monarchy","It granted independence to Eritrea","It created a federal system of government"],"b","The 1931 Constitution was Ethiopias first written constitution, establishing the framework for a constitutional monarchy under Haile Selassie.","Medium")
add("HIS-10-03-19",ch10_03,"Who led the Ethiopian forces in exile during the Italian occupation?",["Ras Imru Haile Selassie","Emperor Haile Selassie","Ras Alula","Menelik II"],"b","Emperor Haile Selassie went into exile in 1936, traveling to Britain and appealing to the League of Nations while patriots continued resistance at home.","Medium")
add("HIS-10-03-20",ch10_03,"The Italian use of chemical weapons during the invasion of Ethiopia was condemned by:",["Only the United States","The League of Nations and international observers","Only the Ethiopian government","Germany and Japan"],"b","Italys use of poison gas against Ethiopian civilians and combatants was condemned by the League of Nations and international observers as a violation of international law.","Medium")
add("HIS-10-03-21",ch10_03,"How did the Battle of Adwa influence Pan-Africanism?",["It had no influence outside Ethiopia","It became a powerful symbol of African resistance and inspired independence movements across the diaspora and continent","It discouraged African resistance movements","It only influenced North African politics"],"b","The Battle of Adwa became a defining symbol of African resistance, inspiring Pan-African leaders like W.E.B. Du Bois and Marcus Garvey.","Hard")
add("HIS-10-03-22",ch10_03,"What was the impact of the Italian occupation on Ethiopian education and infrastructure?",["It dramatically improved education for all Ethiopians","It built infrastructure primarily for colonial administration and military purposes","It had no impact on Ethiopian infrastructure","It established a universal public education system"],"b","The Italian occupation built infrastructure primarily for military and administrative purposes, with limited access to education and modern services for Ethiopians.","Hard")
add("HIS-10-03-23",ch10_03,"What was the significance of the Walwal incident (1934)?",["It was a peaceful trade agreement between Ethiopia and Italy","It was a border clash used as a pretext for the Italian invasion","It was the site of the Battle of Adwa","It was where Haile Selassie signed the treaty with Italy"],"b","The Walwal incident of December 1934 was a border clash in the Ogaden region that Italy exploited as a pretext for its full-scale invasion.","Hard")
add("HIS-10-03-24",ch10_03,"How did the failure of the League of Nations to protect Ethiopia affect international relations?",["It strengthened the League of Nations","It demonstrated the weakness of collective security and encouraged aggressive behavior by expansionist powers","It led to immediate world peace","It had no impact on international relations"],"b","The League failure to take effective action against Italys invasion exposed the weakness of collective security, emboldening aggressive powers like Germany and Japan.","Hard")
add("HIS-10-03-25",ch10_03,"What role did Ethiopian patriots (Arbegnoch) play during the Italian occupation?",["They collaborated with the Italian forces","They conducted guerrilla warfare and sustained resistance that weakened Italian control","They were passive and did not resist","They fought alongside the British only"],"b","Ethiopian patriots maintained continuous guerrilla resistance throughout the occupation, preventing Italy from fully controlling the country.","Hard")
add("HIS-10-03-26",ch10_03,"How did Menelik IIs territorial expansion affect Ethiopias ethnic composition?",["It had no effect on ethnic composition","It incorporated diverse ethnic groups into the empire, creating both unity and potential tensions","It reduced the ethnic diversity of Ethiopia","It only affected Oromo populations"],"b","Menelik IIs expansion southward incorporated diverse peoples including Oromo, Sidama, and Wolayta, creating a multi-ethnic state.","Hard")
add("HIS-10-03-27",ch10_03,"What was the significance of the Battle of Maqdala (1868)?",["It was an Ethiopian victory over Italy","It was a British expedition that defeated Emperor Tewodros II and resulted in the looting of Ethiopian treasures","It was the final battle of the Italian occupation","It was a victory for Emperor Menelik II"],"b","The Battle of Maqdala (1868) was a British expedition against Tewodros II, resulting in his suicide and the looting of Ethiopian cultural treasures.","Hard")
add("HIS-10-03-28",ch10_03,"What was the impact of the Italo-Ethiopian War of 1935-1936 on the concept of collective security?",["It proved collective security was effective","It fundamentally undermined the credibility of the League of Nations and collective security","It had no effect on the League of Nations","It led to the formation of NATO"],"b","The failure of League sanctions against Italy demonstrated that collective security was ineffective, leading to the League decline and eventual replacement by the UN.","Hard")
add("HIS-10-03-29",ch10_03,"What was the role of Empress Taytu Betul in Ethiopian politics?",["She had no political influence","She was a powerful political figure who influenced Menelik IIs policies, including the anti-Italian stance","She was an Italian spy","She was a British advisor"],"b","Empress Taytu was a powerful political figure who influenced Menelik IIs decisions, including the rejection of Italys interpretation of the Treaty of Wuchale.","Hard")
add("HIS-10-03-30",ch10_03,"The liberation of Ethiopia in 1941 was achieved through:",["The Ethiopian army fighting alone","A combination of Ethiopian patriotic resistance and British military assistance","Italian withdrawal without any fighting","League of Nations military intervention"],"b","Ethiopias liberation in 1941 was achieved through the combined efforts of Ethiopian patriots and British military forces from Sudan and Kenya.","Hard")

# --- Chapter 4: Society and Politics in the Age of World Wars 1914-1945 ---
ch10_04 = "Grade 10 - Chapter 4: Society and Politics in the Age of World Wars 1914-1945"
add("HIS-10-04-01",ch10_04,"In which year did World War I begin?",["1912","1914","1916","1918"],"b","World War I began in July 1914, triggered by the assassination of Archduke Franz Ferdinand of Austria-Hungary.","Easy")
add("HIS-10-04-02",ch10_04,"The Treaty of Versailles (1919) officially ended which conflict?",["World War II","World War I","The Korean War","The Napoleonic Wars"],"b","The Treaty of Versailles, signed June 28, 1919, officially ended World War I and imposed heavy reparations on Germany.","Easy")
add("HIS-10-04-03",ch10_04,"What was the League of Nations established to do after World War I?",["To promote trade between nations","To maintain world peace and prevent future wars through collective security","To promote colonial expansion","To govern all European countries"],"b","The League of Nations was established in 1920 to maintain world peace through collective security and disarmament.","Easy")
add("HIS-10-04-04",ch10_04,"World War II began in which year?",["1935","1937","1939","1941"],"c","World War II began on September 1, 1939, when Germany invaded Poland.","Easy")
add("HIS-10-04-05",ch10_04,"The Russian Revolution of 1917 led to the establishment of:",["A democratic republic","A communist state under the Bolsheviks","A constitutional monarchy","A fascist government"],"b","The Russian Revolution of 1917 overthrew the Tsar and led to the establishment of the Soviet Union under Bolshevik (Communist) leadership.","Easy")
add("HIS-10-04-06",ch10_04,"What was the Great Depression?",["A military alliance between European nations","A severe worldwide economic downturn that began in 1929","A religious movement in the 1930s","A scientific discovery in the 1920s"],"b","The Great Depression was a severe global economic crisis beginning with the 1929 stock market crash, causing widespread unemployment and political instability.","Easy")
add("HIS-10-04-07",ch10_04,"Who led the fascist regime in Italy during World War II?",["Adolf Hitler","Benito Mussolini","Joseph Stalin","Winston Churchill"],"b","Benito Mussolini founded and led the fascist regime in Italy from 1922 until his removal from power in 1943.","Easy")
add("HIS-10-04-08",ch10_04,"The atomic bomb was first used in warfare during:",["World War I","The Korean War","World War II against Japan","The Vietnam War"],"c","Atomic bombs were dropped on Hiroshima (August 6, 1945) and Nagasaki (August 9, 1945), leading to Japans surrender and the end of WWII.","Easy")
add("HIS-10-04-09",ch10_04,"The United Nations was founded in which year?",["1919","1939","1945","1950"],"c","The United Nations was founded on October 24, 1945, to replace the failed League of Nations and promote international peace.","Easy")
add("HIS-10-04-10",ch10_04,"Which alliance was known as the Allies in World War II?",["Germany, Italy, Japan","Britain, France, United States, Soviet Union, and others","Germany, Austria-Hungary, Ottoman Empire","Japan, China, Korea"],"b","The Allies in WWII included Britain, France, the United States, the Soviet Union, China, and many other nations.","Easy")
add("HIS-10-04-11",ch10_04,"What was the mandate system created after World War I?",["A system of direct colonial administration","A system where former Ottoman and German colonies were administered by Allied powers under League of Nations supervision","A democratic voting system","A military alliance system"],"b","The mandate system placed former German and Ottoman territories under Allied administration with the stated goal of preparing them for self-governance.","Medium")
add("HIS-10-04-12",ch10_04,"What was the significance of the 1917 Balfour Declaration?",["It declared independence for India","It expressed British support for a national home for the Jewish people in Palestine","It established the League of Nations","It ended World War I"],"b","The Balfour Declaration (1917) expressed British support for a Jewish national home in Palestine, contributing to the Israeli-Palestinian conflict.","Medium")
add("HIS-10-04-13",ch10_04,"The Holocaust refers to:",["The bombing of Hiroshima","The systematic genocide of six million Jews and millions of others by Nazi Germany","The Armenian Genocide","The Rwandan Genocide"],"b","The Holocaust was the systematic, state-sponsored murder of approximately six million Jews and millions of others by Nazi Germany during WWII.","Medium")
add("HIS-10-04-14",ch10_04,"What was the New Deal in the United States?",["A military buildup program","President Roosevelts program of economic recovery and reform during the Great Depression","A trade agreement with Japan","A peace treaty with Germany"],"b","The New Deal was a series of programs by President Roosevelt to combat the Great Depression through economic recovery, relief, and reform.","Medium")
add("HIS-10-04-15",ch10_04,"What was the D-Day invasion?",["The Japanese attack on Pearl Harbor","The Allied invasion of Normandy, France on June 6, 1944","The atomic bombing of Hiroshima","The Italian invasion of Ethiopia"],"b","D-Day (June 6, 1944) was the largest amphibious military invasion in history, landing Allied forces on Normandy beaches to liberate Western Europe.","Medium")
add("HIS-10-04-16",ch10_04,"How did World War I affect African colonial subjects?",["They were not affected at all","Many were conscripted to fight for colonial powers, and post-war promises raised expectations","They gained immediate independence","They were all freed from colonial rule"],"b","African soldiers were conscripted to fight for European powers, and Wilson principle of self-determination raised hopes largely unfulfilled after the war.","Medium")
add("HIS-10-04-17",ch10_04,"The Nuremberg Trials (1945-1946) were significant because:",["They established the precedent of holding individuals accountable for war crimes and crimes against humanity","They were held in Ethiopia","They were trials of Allied soldiers","They established the United Nations"],"a","The Nuremberg Trials prosecuted prominent Nazi leaders for war crimes, establishing important precedents in international law.","Medium")
add("HIS-10-04-18",ch10_04,"What was the Pan-African Congress of 1919?",["A meeting of European colonial powers","A conference in Paris organized by W.E.B. Du Bois to advocate for African rights","An Ethiopian diplomatic mission","A United Nations meeting"],"b","The Pan-African Congress of 1919, organized by W.E.B. Du Bois in Paris, demanded political rights, land rights, and self-determination for Africans.","Medium")
add("HIS-10-04-19",ch10_04,"Which of the following best describes fascism?",["A democratic political system","An authoritarian nationalist ideology emphasizing ultranationalism, militarism, and suppression of opposition","An economic theory promoting free trade","A religious movement"],"b","Fascism is a far-right authoritarian ideology characterized by ultranationalism, dictatorial power, militarism, and suppression of opposition.","Medium")
add("HIS-10-04-20",ch10_04,"What was the Atlantic Charter (1941)?",["A military alliance between Germany and Japan","A joint declaration by the US and UK outlining post-war goals including self-determination and free trade","A peace treaty ending World War I","A trade agreement with African nations"],"b","The Atlantic Charter (August 1941) was a joint declaration by Roosevelt and Churchill outlining post-war goals including self-determination and international cooperation.","Medium")
add("HIS-10-04-21",ch10_04,"How did World War II accelerate decolonization in Africa and Asia?",["It had no effect on colonialism","It weakened European powers, empowered independence movements, and exposed the contradiction of fighting for freedom abroad while denying it in colonies","It strengthened colonial rule","It led to new colonial territories"],"b","WWII weakened European colonial powers economically and militarily, while colonial subjects who fought for freedom abroad demanded the same rights at home.","Hard")
add("HIS-10-04-22",ch10_04,"What was the significance of Haile Selassies 1936 declaration from Harar?",["It was a peace treaty with Italy","It reaffirmed Ethiopias sovereignty and rejected Italian claims of colonial domination","It was an alliance with Britain","It declared war on the United States"],"b","From Harar during the Italian occupation, Haile Selassie made declarations reaffirming Ethiopian sovereignty and rallying resistance against Italian rule.","Hard")
add("HIS-10-04-23",ch10_04,"What role did Ethiopia play in the formation of the United Nations?",["Ethiopia opposed the creation of the UN","Ethiopia was a founding member and Haile Selassie addressed the UN General Assembly","Ethiopia was not involved in the UNs creation","Ethiopia only joined as an observer"],"b","Ethiopia was among the founding members of the United Nations in 1945, and Haile Selassie addressed the General Assembly, cementing Ethiopias international role.","Hard")
add("HIS-10-04-24",ch10_04,"How did the Great Depression impact colonial Africa?",["It improved conditions for all Africans","It caused economic hardship, reduced export prices, and increased exploitation of African labor","It had no impact on Africa","It led to immediate independence for African colonies"],"b","The Great Depression reduced global demand for African raw materials, causing economic hardship, while colonial governments increased taxes and forced labor.","Hard")
add("HIS-10-04-25",ch10_04,"What was the Cairo Conference of 1943?",["A meeting of Axis powers","A meeting of Allied leaders (Roosevelt, Churchill, Chiang Kai-shek) to discuss the war against Japan","A Pan-African independence conference","An Ethiopian peace negotiation"],"b","The Cairo Conference (November 1943) brought together Roosevelt, Churchill, and Chiang Kai-shek to plan strategy against Japan and discuss post-war Asia.","Hard")
add("HIS-10-04-26",ch10_04,"How did World War I contribute to the collapse of empires?",["It strengthened all European empires","It led to the collapse of the Ottoman, Austro-Hungarian, Russian, and German empires","It had no effect on empires","It only weakened the British Empire"],"b","World War I caused the collapse of four major empires: Ottoman, Austro-Hungarian, Russian, and German, redrawing the map of Europe and the Middle East.","Hard")
add("HIS-10-04-27",ch10_04,"What was the Battle of Stalingrad (1942-1943) significant for?",["It was the first use of atomic weapons","It was a turning point in WWII, marking the beginning of the German retreat on the Eastern Front","It ended World War I","It was a naval battle in the Pacific"],"b","The Battle of Stalingrad was one of the deadliest battles in history and marked a crucial turning point, halting the German advance into the Soviet Union.","Hard")
add("HIS-10-04-28",ch10_04,"How did the experience of World War I affect African soldiers who served in European armies?",["They became more loyal to colonial governments","Many returned with military skills, political awareness, and heightened demands for rights","They had no significant political impact","They were all imprisoned after the war"],"b","African veterans returned with military training, exposure to European ideas of freedom, and determination to demand political rights and self-governance.","Hard")
add("HIS-10-04-29",ch10_04,"What was the significance of the Yalta Conference (1945)?",["It ended World War I","It was a meeting of the Big Three (Roosevelt, Churchill, Stalin) to plan the post-war reorganization of Europe","It established the League of Nations","It was a meeting of African leaders"],"b","The Yalta Conference (February 1945) brought together Roosevelt, Churchill, and Stalin to discuss the post-war reorganization of Europe and the defeat of Germany.","Hard")
add("HIS-10-04-30",ch10_04,"How did World War I create conditions for future conflicts in the Middle East?",["It had no impact on the Middle East","The arbitrary borders drawn by colonial powers, the mandate system, and the Balfour Declaration created lasting tensions","It unified the Middle East","It granted full independence to all Middle Eastern countries"],"b","WWI led to the breakup of the Ottoman Empire, the mandate system, arbitrary borders, and the Balfour Declaration, creating lasting tensions in the Middle East.","Hard")

print(f"Chapters 1-4 of Grade 10: {len(questions)} questions")
print("Done writing Grade 10 chapters 1-4")
# Write intermediate result to verify
with open(r"C:\Users\kal3n\Desktop\Projects\AceMatric\AceMatric\temp_history_all.json", "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)
print("Intermediate file written")
