$out = "C:\Users\kal3n\Desktop\Projects\AceMatric\AceMatric\temp_sat_g10.json"
$allQuestions = @()

$chapters = @(
  @("NO","Numbers and Operations"),
  @("AF","Algebra and Functions"),
  @("GM","Geometry and Measurement"),
  @("DP","Data Analysis and Probability"),
  @("AM","Advanced Mathematics"),
  @("PS","Problem Solving Strategies"),
  @("CR","Critical Reading"),
  @("WL","Writing and Language"),
  @("EW","Essay Writing"),
  @("VC","Vocabulary in Context"),
  @("IG","Informational Graphics"),
  @("ER","Evidence-Based Reasoning"),
  @("PQ","Pairs of Quantities"),
  @("RP","Ratios and Proportional Relationships"),
  @("PC","Percentage and Percent Change"),
  @("DI","Data Interpretation"),
  @("SA","Science Passage Analysis"),
  @("SS","Social Science Passage Analysis"),
  @("HA","Historical Passage Analysis"),
  @("LA","Literary Passage Analysis"),
  @("WR","Writing Revision"),
  @("IC","Idioms and Common Expressions")
)

$bank = @{}
$bank["NO"] = @(
@("What is 3 + 4?","7","8","9","10","a","3+4=7","Easy"),
@("What is 12 - 5?","7","8","6","9","a","12-5=7","Easy"),
@("What is 6 x 7?","42","48","36","49","a","6*7=42","Easy"),
@("What is 56 / 8?","6","7","8","9","b","56/8=7","Easy"),
@("What is 15% of 200?","20","25","30","35","c","0.15*200=30","Easy"),
@("What is sqrt(64)?","6","8","10","12","b","8*8=64","Easy"),
@("If x=5, what is 2x+3?","10","13","15","8","b","2(5)+3=13","Easy"),
@("Sum of first 5 positive integers?","10","12","15","20","c","1+2+3+4+5=15","Easy"),
@("Which fraction equals 0.75?","1/4","3/4","2/3","4/5","b","0.75=3/4","Easy"),
@("What is 2^3 x 2^2?","8","32","64","16","b","2^5=32","Easy"),
@("Simplify (3^2+4^2)/(2+3)","4","5","6","7","b","(9+16)/5=5","Medium"),
@("If 3x-7=14, x=?","5","6","7","8","c","3x=21,x=7","Medium"),
@("GCF of 24 and 36?","6","8","12","18","c","GCF=12","Medium"),
@("20% discount on $75, sale price?","$55","$58","$60","$62","c","75-15=60","Medium"),
@("What is |-8|+|3|?","5","11","-5","-11","b","8+3=11","Medium"),
@("If 5a=3b and a=6, b=?","8","10","12","15","b","30=3b,b=10","Medium"),
@("5 more than twice n is:","2n+5","5n+2","2(n+5)","n+10","a","2n+5","Medium"),
@("Product of two negatives is:","Negative","Positive","Zero","Undetermined","b","Neg*neg=positive","Medium"),
@("What is 1/3+1/6?","1/2","2/9","1/9","2/6","a","2/6+1/6=3/6=1/2","Medium"),
@("Train at 80 km/h for 2.5 hrs, distance?","160km","180km","200km","220km","c","80*2.5=200","Medium"),
@("Solve 2(x-3)+4=3x-5","3","5","7","9","a","2x-2=3x-5,x=3","Hard"),
@("What is 2^-3?","8","-8","1/8","-1/8","c","1/2^3=1/8","Hard"),
@("x^2-5x+6=0, x=?","1,6","2,3","-2,-3","-1,-6","b","(x-2)(x-3)=0","Hard"),
@("Number increased by 20% is 72, original?","54","58","60","62","c","1.2x=72,x=60","Hard"),
@("Simplify (4^3 x 2^2)/2^5","2","4","8","16","c","256/32=8","Hard"),
@("f(x)=2x^2-3x+1, f(-2)?","3","7","15","19","c","8+6+1=15","Hard"),
@("Sum of all factors of 36?","55","60","72","91","d","1+2+3+4+6+9+12+18+36=91","Hard"),
@("4^(x+1)=64, x=?","1","2","3","4","b","4^3=64,x+1=3,x=2","Hard"),
@("P(not green) if 5 red 3 blue 2 green?","1/5","2/5","3/5","4/5","d","8/10=4/5","Hard"),
@("Avg of 5 nums=18. Remove one, avg=16. Removed?","24","26","28","30","b","90-64=26","Hard")
)

$bank["AF"] = @(
@("Slope of y=3x+2?","2","3","5","6","b","m=3","Easy"),
@("f(x)=x+7, f(3)?","3","7","10","21","c","3+7=10","Easy"),
@("Y-intercept of y=-2x+5?","-2","2","5","-5","c","b=5","Easy"),
@("Solve x+9=15","4","5","6","7","c","x=15-9=6","Easy"),
@("Which is linear?","y=x^2","y=3x+1","y=1/x","y=x^3","b","y=mx+b","Easy"),
@("4x=28, x=?","5","6","7","8","c","x=7","Easy"),
@("g(x)=5x-3, g(0)?","-3","0","3","5","a","g(0)=-3","Easy"),
@("Parallel lines have same:","y-intercept","slope","x-intercept","length","b","Equal slopes","Easy"),
@("Simplify 3x+5x","8x","15x","8x^2","2x","a","3x+5x=8x","Easy"),
@("Domain of f(x)=sqrt(x-2)?","x>=0","x>=2","x>2","All reals","b","x-2>=0","Easy"),
@("f(x)=2x+1,g(x)=x-3, f(g(5))?","3","5","7","9","b","g(5)=2,f(2)=5","Medium"),
@("Vertex of y=(x-3)^2+4?","(3,4)","(-3,4)","(3,-4)","(-3,-4)","a","h=3,k=4","Medium"),
@("x+y=10,x-y=4, x=?","5","6","7","8","c","2x=14,x=7","Medium"),
@("Factored form of x^2-9?","(x-3)^2","(x+3)^2","(x-3)(x+3)","(x-9)(x+1)","c","Diff of squares","Medium"),
@("Slope perpendicular to y=4x-1?","4","-4","1/4","-1/4","d","Neg reciprocal=-1/4","Medium"),
@("h(x)=x^2+2x-5, h(2)?","1","3","5","7","b","4+4-5=3","Medium"),
@("Line through (0,3) slope 2?","y=2x+3","y=3x+2","y=2x-3","y=-2x+3","a","y=2x+3","Medium"),
@("Range of f(x)=x^2?","All reals","x>=0","y>=0","y>0","c","x^2>=0","Medium"),
@("Expand (2x+3)(x-1)","2x^2+x-3","2x^2-x-3","2x^2+5x-3","2x^2-5x+3","a","2x^2+x-3","Medium"),
@("y=60x, distance 180km, time?","2","3","4","6","b","180=60x,x=3","Medium"),
@("2x^2-5x-3=0, x=?","3,-1/2","-3,1/2","3,1/2","-3,-1/2","a","(2x+1)(x-3)=0","Hard"),
@("f(x)=(x+2)/(x-1), undefined at?","-2","0","1","2","c","x-1=0,x=1","Hard"),
@("Axis of symmetry x^2-6x+8?","x=2","x=3","x=4","x=6","b","x=6/2=3","Hard"),
@("f(x)=3x^2-2x+1, f'(x)?","6x-2","3x-2","6x+1","6x^2-2","a","Power rule","Hard"),
@("x^2+kx+9=0 one solution, k=?","k=3","k=+/-6","k=+/-9","k=+/-18","b","k^2-36=0","Hard"),
@("Solve 3x-7>2x+5","x>12","x>2","x<12","x<2","a","x>12","Hard"),
@("f(x)=log2(x), f(8)?","2","3","4","8","b","2^3=8","Hard"),
@("Inverse of f(x)=2x+6?","(x-6)/2","(x+6)/2","2x-6","x/2+3","a","x=(y-6)/2","Hard"),
@("|x-4| min at?","x=-4","x=0","x=4","x=8","c","Min=0 at x=4","Hard"),
@("f(x)=x^3-x, real zeros?","1","2","3","4","c","x(x-1)(x+1)=0, 3 zeros","Hard")
)

$bank["GM"] = @(
@("Area of triangle base=10 height=6?","30cm2","60cm2","16cm2","120cm2","a","0.5*10*6=30","Easy"),
@("Perimeter of rect l=8 w=5?","13m","26m","40m","20m","b","2(8+5)=26","Easy"),
@("Circumference r=7, pi=22/7?","14cm","22cm","44cm","154cm","c","2*22/7*7=44","Easy"),
@("Degrees in a right angle?","45","60","90","180","c","90 degrees","Easy"),
@("Area of square side=5?","10","15","20","25","d","5^2=25","Easy"),
@("Sum of interior angles of triangle?","90","180","270","360","b","180 degrees","Easy"),
@("Volume of cube edge=3?","9","18","27","54","c","3^3=27","Easy"),
@("Degrees in a straight line?","90","180","270","360","b","180 degrees","Easy"),
@("Area of circle r=5, pi=3.14?","15.7","25","31.4","78.5","d","3.14*25=78.5","Easy"),
@("Pythagorean theorem?","a+b=c","a^2+b^2=c^2","a^2-b^2=c^2","a*b=c^2","b","a^2+b^2=c^2","Easy"),
@("Right triangle legs 6,8, hypotenuse?","9","10","12","14","b","sqrt(36+64)=10","Medium"),
@("Volume cylinder r=3 h=10, pi=3.14?","94.2","188.4","282.6","565.2","c","3.14*9*10=282.6","Medium"),
@("Supplementary angle to 65?","25","115","295","65","b","180-65=115","Medium"),
@("Area trapezoid b1=8 b2=12 h=5?","25","40","50","60","c","0.5*20*5=50","Medium"),
@("Diagonal of square side=6?","6sqrt2","6sqrt3","12","8","a","6*sqrt2","Medium"),
@("Sum of interior angles of hexagon?","540","600","720","900","c","(6-2)*180=720","Medium"),
@("Lateral area cone r=5 slant=13?","65pi","90pi","130pi","204pi","a","pi*5*13=65pi","Medium"),
@("Similar triangles ratio 2:5, small perimeter=14, large?","28","35","42","50","b","14*5/2=35","Medium"),
@("Sector area r=8 angle=60?","16pi/3","32pi/3","16pi","64pi","b","60/360*pi*64=32pi/3","Medium"),
@("Sphere volume=36pi, radius?","2","3","4","6","b","4/3*pi*r^3=36pi,r=3","Hard"),
@("Triangle A=40 B=75, C=?","55","65","75","115","b","180-40-75=65","Hard"),
@("Surface area cube edge=4?","48","64","96","128","c","6*16=96","Hard"),
@("Circles r=3 and r=7, area ratio?","3:7","9:49","6:14","21:49","b","(3/7)^2=9/49","Hard"),
@("Regular polygon ext angle=30, sides?","8","10","12","15","c","360/30=12","Hard"),
@("Distance (1,2) to (4,6)?","3","4","5","7","c","sqrt(9+16)=5","Hard"),
@("Cylinder C=12pi h=8, volume?","96pi","144pi","288pi","576pi","c","r=6,V=pi*36*8=288pi","Hard"),
@("Area parallelogram base=10 height=7?","17","35","70","100","c","10*7=70","Hard"),
@("Triangle 5,12,13 right?","Yes","No","Cannot tell","Only if isosceles","a","25+144=169=13^2","Hard"),
@("Sphere diameter=12, volume?","288pi","576pi","864pi","1152pi","a","4/3*pi*216=288pi","Hard"),
@("Area circle diameter=10, pi=3.14?","31.4","78.5","153.86","314","b","r=5,A=pi*25=78.5","Hard")
)

$bank["DP"] = @(
@("Mean of 4,8,6,10,12?","6","8","10","12","b","40/5=8","Easy"),
@("Median of 3,7,9,1,5?","3","5","7","9","b","Ordered:5","Easy"),
@("Mode of 2,3,3,5,7?","2","3","5","7","b","Most frequent=3","Easy"),
@("P(rolling 4 on die)?","1/2","1/3","1/4","1/6","d","1/6","Easy"),
@("Range of 2,5,8,12,15?","7","10","13","15","c","15-2=13","Easy"),
@("P(two heads, 2 flips)?","1/2","1/3","1/4","1/8","c","1/4","Easy"),
@("Most affected by outliers?","Mean","Median","Mode","Range","a","Mean","Easy"),
@("60% of 200 prefer chocolate, how many?","100","120","140","160","b","0.6*200=120","Easy"),
@("P(red card from deck)?","1/4","1/3","1/2","2/3","c","26/52=1/2","Easy"),
@("Best graph for parts of whole?","Bar","Line","Pie","Scatter","c","Pie chart","Easy"),
@("Mean of 2,4,4,6,8,10,12?","5","6","7","8","c","46/7 approx 7","Medium"),
@("P(A)=0.3,P(B)=0.5 independent, P(A&B)?","0.15","0.2","0.6","0.8","a","0.3*0.5=0.15","Medium"),
@("4 red 6 blue, 2 drawn w/o replace, P(both red)?","2/15","4/25","6/25","16/100","a","4/10*3/9=2/15","Medium"),
@("IQR of 1,3,5,7,9,11,13?","4","6","8","10","c","11-3=8","Medium"),
@("Num 1-20, P(divisible by 3)?","1/5","3/20","7/20","1/4","c","6/20=3/10","Medium"),
@("Variance of 2,4,4,4,5,5,7,9?","2","4","5","6","b","Variance=4","Medium"),
@("Two dice, P(sum=7)?","1/6","1/12","7/36","1/9","a","6/36=1/6","Medium"),
@("Box plot Q1=15 median=22 Q3=30, IQR?","7","15","18","30","b","30-15=15","Medium"),
@("A,B mutually exclusive, P(A)=0.4 P(B)=0.3, P(AorB)?","0.12","0.58","0.7","1","c","0.4+0.3=0.7","Medium"),
@("Weighted average used when:","All equal","Some count more","Outliers","Categorical","b","Different weights","Medium"),
@("Std dev of 5,5,5,5,5?","0","1","5","25","a","No spread=0","Hard"),
@("P(A)=0.6, P(not A)?","0.4","0.6","0.36","1.6","a","1-0.6=0.4","Hard"),
@("Avg 5 nums=20, remove one avg=18, removed?","24","26","28","30","c","100-72=28","Hard"),
@("3 coins, P(exactly 2 heads)?","1/4","3/8","1/2","5/8","b","3/8","Hard"),
@("Std dev=5, variance?","sqrt5","5","10","25","d","5^2=25","Hard"),
@("5 men 4 women, 3-person committee, P(2 women)?","10/21","20/63","5/21","1/3","a","C(4,2)*C(5,1)/C(9,3)=30/84=5/14 approx 10/21","Hard"),
@("Normal dist, % within 2 std devs?","50%","68%","95%","99%","c","95%","Hard"),
@("Ages 12,14,14,15,16,18,20, best center?","Mean","Median","Mode","All equal","b","Median for skewed","Hard"),
@("3 red 5 blue 2 green, odds favor blue?","1:2","1:1","5:2","5:5","b","5:5=1:1","Hard"),
@("Correlation -0.9 means?","Strong pos","Strong neg","Weak neg","No corr","b","Strong negative","Hard")
)

$bank["AM"] = @(
@("Simplify (2+3i)+(4-i)","6+2i","6+4i","2+2i","8+2i","a","6+2i","Easy"),
@("What is i^2?","1","-1","i","-i","b","i^2=-1","Easy"),
@("What is 5!?","25","60","100","120","d","120","Easy"),
@("Ways to arrange 3 books?","3","6","9","27","b","3!=6","Easy"),
@("Conjugate of 3+2i?","3-2i","-3+2i","-3-2i","3+2i","a","3-2i","Easy"),
@("log10(1000)?","2","3","10","100","b","10^3=1000","Easy"),
@("Simplify (1+i)^2?","2i","1+2i","2+2i","-2i","a","2i","Easy"),
@("C(5,2)?","5","10","20","25","b","10","Easy"),
@("|3+4i|?","3","4","5","7","c","5","Easy"),
@("C(7,4)?","28","35","840","210","b","35","Easy"),
@("log2(32)?","3","4","5","6","c","2^5=32","Medium"),
@("Expand (x+2)^3?","x^3+6x^2+12x+8","x^3+8","x^3+6x^2+8","x^3+2x^2+4x+8","a","Binomial expansion","Medium"),
@("Sum 1+2+4+8+16?","15","31","32","64","b","2^5-1=31","Medium"),
@("x^4-1=0, solutions?","+-1","+-1,+-i","1,-1,2,-2","+-i","b","Four roots","Medium"),
@("P(6,3)=120, P(5,2)?","10","20","30","60","b","20","Medium"),
@("10th term of 3,7,11,15...?","35","39","43","47","b","3+36=39","Medium"),
@("log3(81)?","3","4","9","27","b","3^4=81","Medium"),
@("Det of [[2,3],[1,4]]?","5","7","11","14","a","8-3=5","Medium"),
@("Simplify (3i)(4i)?","12i","12","-12","7i","c","12i^2=-12","Medium"),
@("Geo seq: a2=6, a3=12, a1?","2","3","4","6","b","r=2,a1=3","Medium"),
@("4-digit from 1-6 no repeat?","120","360","1296","30","b","P(6,4)=360","Hard"),
@("(2+i)(2-i)?","3","4","5","2i","c","4+1=5","Hard"),
@("Sum first 6 of 2,6,18...?","242","486","728","1458","c","728","Hard"),
@("(1+i)^4?","4","-4","4i","-4i","b","(2i)^2=-4","Hard"),
@("Coeff of x^3 in (x+2)^5?","10","20","40","80","c","40","Hard"),
@("|2x-3|=7, x?","5,-2","5,2","-5,2","5,-5","a","5 and -2","Hard"),
@("Recursive 5,11,23,47?","2an-1+1","2an-1-1","an-1+6","3an-1-4","a","2a(n-1)+1","Hard"),
@("Remainder 2^10/7?","1","2","4","6","b","1024 mod 7=2","Hard"),
@("15th term a1=2 d=3?","42","44","46","48","b","2+42=44","Hard"),
@("Arrange 5 books, 2 together?","24","48","120","240","b","4!*2!=48","Hard")
)

$bank["PS"] = @(
@("3 apples $6, 5 apples?","$8","$9","$10","$12","c","5*2=10","Easy"),
@("Rectangle 12x5, area?","17","35","60","120","c","60","Easy"),
@("3 pens $2 each, change from $10?","$2","$3","$4","$6","c","10-6=4","Easy"),
@("60mph for 3.5 hrs, distance?","180","200","210","240","c","210","Easy"),
@("25% of 80?","15","20","25","30","b","20","Easy"),
@("x+y=10, x=3, y=?","3","5","7","10","c","7","Easy"),
@("Pizza 8 slices, eat 3, fraction left?","3/8","5/8","3/5","5/3","b","5/8","Easy"),
@("Minutes in 2.5 hours?","120","140","150","160","c","150","Easy"),
@("Shirt $25, 20% off, sale price?","$15","$18","$20","$22","c","$20","Easy"),
@("Triangle base=10 height=8, area?","18","40","80","180","b","40","Easy"),
@("Two trains 300mi apart, 60+40mph, meet when?","1.5","2","2.5","3","d","3 hrs","Medium"),
@("Tank fills 6hrs drains 8hrs, fill time?","14","24","24/7","7","b","24 hrs","Medium"),
@("5 workers 8 days, workers for 4 days?","5","8","10","12","c","10","Medium"),
@("Map 1:50000, 4cm apart, real distance?","1km","2km","4km","10km","b","2km","Medium"),
@("3 consecutive ints sum=42, largest?","12","13","14","15","c","14","Medium"),
@("Wheel diameter 26in, circumference?","40.8","81.6","163.2","530.4","b","81.6","Medium"),
@("John twice Mary's age, Mary=12, John in 5 years?","24","29","34","49","b","29","Medium"),
@("Recipe 4 serves 3 cups, 10 serves?","6","7","7.5","12","c","7.5","Medium"),
@("Markup 40% on $50, selling price?","$60","$65","$70","$90","c","$70","Medium"),
@("2^4 * 2^x = 2^7, x?","1","2","3","4","c","3","Medium"),
@("Boat 15mph water 3mph current, 10mi round trip time?","1.25","1.4","1.5","2","b","1.4 hrs","Hard"),
@("Two pipes 4hrs 6hrs, together?","2","2.4","5","10","b","2.4 hrs","Hard"),
@("f(x)=2x+3,g(x)=x^2-1, f(g(2))?","9","11","13","15","a","g(2)=3,f(3)=9","Hard"),
@("Number doubled plus 7 is 21, number?","5","7","9","14","b","7","Hard"),
@("Circle same perimeter as square side=14, circle area?","616","154","484","308","a","784/pi approx 616","Hard"),
@("5 test scores avg need 88, scores 80,85,90,75,95, 6th?","88","90","92","95","c","92","Hard"),
@("3x=5y, x+y=16, x?","6","8","10","12","c","10","Hard"),
@("20% red, 8 red, total?","24","32","40","50","c","40","Hard"),
@("3-digit all odd digits, how many?","27","64","100","125","d","5^3=125","Hard"),
@("Clock 3:15, angle between hands?","0","7.5","15","22.5","b","7.5 degrees","Hard")
)

$bank["CR"] = @(
@("Findings were ___ by others. Best word:","confirmed","refuted","ignored","questioned","a","Confirmed=validated","Easy"),
@("Main idea of climate change causes/effects paragraph?","Definition","Causes and effects","Solutions","History","b","Causes and effects","Easy"),
@("Author tone describing disaster?","Cheerful","Objective","Angry","Sarcastic","b","Objective","Easy"),
@("'Benevolent' means:","Cruel","Kind","Generous","Brave","b","Kind","Easy"),
@("'Ambivalent' means:","Excited","Indifferent","Mixed feelings","Determined","c","Mixed feelings","Easy"),
@("Correct semicolon use?","I went home; and slept.","I went home; I slept.","I went home,; I slept.","I; went home I slept.","b","Two independent clauses","Easy"),
@("'Ephemeral' means:","Permanent","Brief","Eternal","Important","b","Brief","Easy"),
@("'The author argues' suggests:","Angry","Presents position","Confused","Agrees","b","Presents position","Easy"),
@("Transition showing contrast:","Furthermore","However","Therefore","Moreover","b","However","Easy"),
@("Passage with examples is primarily:","Narrating","Persuading","Explaining","Comparing","c","Explaining","Easy"),
@("'Ubiquitous' means:","Rare","Found everywhere","Unique","Ancient","b","Found everywhere","Medium"),
@("Shift from facts to opinions:","Dishonest","Rhetorical shift","Changing subject","Ending essay","b","Rhetorical shift","Medium"),
@("'Author's purpose' refers to:","What to achieve","When wrote","Where lives","Who is","a","What to achieve","Medium"),
@("Evidence in persuasive essay used to:","Entertain","Support claims","Describe","Introduce chars","b","Support claims","Medium"),
@("'Pragmatic' means:","Idealistic","Practical","Creative","Lazy","b","Practical","Medium"),
@("'Laudatory' tone is:","Critical","Praising","Neutral","Humorous","b","Praising","Medium"),
@("Counterexample is:","Restating thesis","Opposing view","More evidence","Concluding","b","Opposing view","Medium"),
@("'Meticulous' means:","Careless","Very careful","Slightly interested","Very fast","b","Very careful","Medium"),
@("'It follows that' signals:","Example","Conclusion","Doubt","Topic change","b","Conclusion","Medium"),
@("Effective timed test strategy:","Read slowly","Skim then close read","Read first para only","Ignore question","b","Skim then close read","Medium"),
@("'Sycophant' is someone who:","Leads","Flatters for gain","Works alone","Seeks truth","b","Flatters for gain","Hard"),
@("'Premise' in argument is:","Conclusion","Evidence","Title","Counterpoint","b","Evidence","Hard"),
@("'Reductio ad absurdum' is:","Humor","Proving by contradiction","Story","Comparison","b","Proving by contradiction","Hard"),
@("'Dilettante' is someone who:","Expert","Pursues superficially","Teaches","Works hard","b","Superficially","Hard"),
@("Ad hominem attack targets:","Evidence","Logic","Person not argument","Data","c","Person not argument","Hard"),
@("Tone 'sardonic' means:","Gentle","Mockingly cynical","Cheerful","Formal","b","Mockingly cynical","Hard"),
@("Rhetorical question aims to:","Get answer","Provoke thought","Express doubt","Change topic","b","Provoke thought","Hard"),
@("'Juxtaposition' means:","Comparison by placing side by side","Ignoring","Repeating","Exaggerating","a","Side by side","Hard"),
@("Ethos in argument refers to:","Logic","Emotion","Credibility","Evidence","c","Credibility","Hard"),
@("'Cacophony' in literature means:","Harmony","Harsh sounds","Silence","Repetition","b","Harsh sounds","Hard")
)

$bank["WL"] = @(
@("Which is a complete sentence?","Running fast.","The dog barked loudly.","In the garden.","After the rain.","b","Has subject and verb","Easy"),
@("Identify the subject: The cat sat on the mat.","cat","sat","mat","on","a","Subject=cat","Easy"),
@("Which uses correct punctuation?","Its raining.","Its' raining.","It's raining.","It is' raining.","c","It's=it is","Easy"),
@("Which is an active voice sentence?","The cake was eaten.","John ate the cake.","The cake is being eaten.","The cake had been eaten.","b","Active voice","Easy"),
@("Which is a compound sentence?","I went home.","I went home and slept.","Although I went home.","Going home.","b","Two clauses with conjunction","Easy"),
@("Which word is a noun?","Quickly","Happy","Book","Run","c","Book is a noun","Easy"),
@("Which is a comma splice?","I went; she stayed.","I went, she stayed.","I went. She stayed.","I went and she stayed.","b","Comma splice error","Easy"),
@("Which uses 'their' correctly?","Their going home.","Their car is red.","Their is nice.","They're car is red.","b","Their=possessive","Easy"),
@("Which is past perfect tense?","I walked.","I had walked.","I will walk.","I am walking.","b","Had + past participle","Easy"),
@("Which is a thesis statement?","What is a dog?","Dogs make great pets because they are loyal.","I like dogs.","Dogs are animals.","b","States a claim with reason","Easy"),
@("Which transition shows addition?","However","Therefore","Moreover","Nevertheless","c","Moreover=addition","Medium"),
@("Which sentence is parallel?","She likes swimming and to run.","She likes swimming and running.","She likes to swim and running.","She likes swim and run.","b","Parallel structure","Medium"),
@("Which is a dependent clause?","I went home.","Because it rained.","She ran fast.","They played.","b","Depends on main clause","Medium"),
@("Which uses a semicolon correctly?","I went; home.","I went; she stayed.","I; went home.","I went home; and.","b","Two independent clauses","Medium"),
@("Which is formal writing?","Hey guys! What's up?","Furthermore, the data suggests.","OMG that's so cool!","Yo, check this out.","b","Formal academic register","Medium"),
@("Which is a misplaced modifier?","Running quickly, the bus was caught.","Quickly, the bus was caught running.","The bus was caught running quickly.","Caught the bus running quickly.","a","Modifier should be near subject","Medium"),
@("Which sentence shows conciseness?","Due to the fact that","Because","In spite of the fact that","At this point in time","b","Because is concise","Medium"),
@("Which word is an adjective?","Beautifully","Beautiful","Beauty","Beautify","b","Beautiful=adjective","Medium"),
@("Which is a complex sentence?","I ran. She walked.","I ran and she walked.","When I ran, she walked.","Running, walking.","c","Complex sentence","Medium"),
@("Which uses 'who' correctly?","Who did this?","Whom is there?","Who did you see?","Whom went home?","a","Who=subject","Medium"),
@("Which is a dangling modifier?","Walking to school, the rain started.","The rain started walking to school.","Walking to school, I saw rain.","I started rain walking.","a","No clear subject","Hard"),
@("Which sentence is most effective?","The thing was good.","The product excelled.","It was really very good.","The item performed well.","b","Specific and clear","Hard"),
@("Which uses colon correctly?","I need: eggs, milk.","I need: eggs and milk.","I need eggs: and milk.","I need three items: eggs, milk, bread.","d","Colon introduces list","Hard"),
@("Which is an Oxford comma example?","I like cats, dogs and birds.","I like cats, dogs, and birds.","I like cats and dogs and birds.","I like: cats, dogs, birds.","b","Oxford comma before 'and'","Hard"),
@("Which is an example of tone shift?","The essay changes from formal to casual.","The essay stays the same.","The essay has no tone.","The essay is always casual.","a","Tone shift detected","Hard"),
@("Which word is a preposition?","Quickly","Under","Happy","Run","b","Under=preposition","Hard"),
@("Which uses ellipsis correctly?","I went to...the store.","I went to the store...","I... went to the store.","All of the above.","a","Ellipsis shows pause","Hard"),
@("Which sentence eliminates redundancy?","Free gift","Gift","Free present","Bonus gift","b","Gift already implies free","Hard"),
@("Which is an example of parallelism?","She likes to swim, running, and bikes.","She likes swimming, running, and biking.","She likes to swim, run, and biking.","She likes swim, run, bike.","b","All gerunds","Hard"),
@("Which is active voice?","Mistakes were made.","The team made mistakes.","The mistakes are being made.","The mistakes had been made.","b","Active voice has clear subject","Hard")
)

$bank["EW"] = @(
@("A good essay introduction should:","Start with a quote always","Hook the reader","List all arguments","Skip to thesis","b","Hook engages reader","Easy"),
@("The thesis statement should be:","Vague","Specific and arguable","Very long","A question","b","Specific and arguable","Easy"),
@("Each body paragraph should have:","Only one sentence","A topic sentence","No evidence","A conclusion only","b","Topic sentence","Easy"),
@("A conclusion should:","Introduce new ideas","Restate thesis and summarize","Repeat body paragraphs","Ask questions","b","Restate and summarize","Easy"),
@("Which is a strong thesis?","Dogs are animals.","Dogs are the best pets because of loyalty.","I like dogs.","What about dogs?","b","Arguable claim with reason","Easy"),
@("Evidence in an essay includes:","Personal opinions only","Facts, quotes, examples","Random thoughts","No support needed","b","Facts, quotes, examples","Easy"),
@("A hook in an essay can be:","A long definition","A surprising fact or question","A conclusion","A thesis","b","Surprising fact or question","Easy"),
@("Topic sentences:","Appear in conclusions","Introduce paragraph main idea","Are always first word","Repeat the thesis","b","Introduce paragraph idea","Easy"),
@("Transitions between paragraphs:","Are unnecessary","Help flow of ideas","Replace evidence","End paragraphs","b","Help flow of ideas","Easy"),
@("A persuasive essay aims to:","Simply inform","Convince the reader","Tell a story","Entertain only","b","Convince the reader","Easy"),
@("Which strengthens an argument?","Emotional language only","Counterargument and rebuttal","Repetition","Personal attacks","b","Counterargument and rebuttal","Medium"),
@("A rebuttal:","Agrees with opposition","Refutes opposing argument","Ignores opposition","Changes topic","b","Refutes opposing argument","Medium"),
@("Which shows logical reasoning?","I think so","Data shows 75% agree","Everyone knows","It is obvious","b","Data shows 75%","Medium"),
@("An effective conclusion:","Introduces new evidence","Connects back to thesis","Repeats introduction word for word","Ends with a question","b","Connects back to thesis","Medium"),
@("The purpose of a counterargument:","Weakens your essay","Shows balanced thinking","Confuses reader","Replaces evidence","b","Shows balanced thinking","Medium"),
@("Which is a credible source?","Personal blog","Peer-reviewed journal","Wikipedia","Social media post","b","Peer-reviewed journal","Medium"),
@("A call to action in a persuasive essay:","Summarizes the essay","Urges reader to do something","Introduces thesis","Provides counterargument","b","Urges reader to act","Medium"),
@("Anecdotes in essays are used to:","Replace evidence","Illustrate a point","Fill space","Confuse reader","b","Illustrate a point","Medium"),
@("Rhetorical questions in essays:","Are always answered","Engage the reader","Replace evidence","End paragraphs","b","Engage the reader","Medium"),
@("A well-organized essay has:","Random paragraphs","Clear introduction, body, conclusion","Only body paragraphs","No structure","b","Clear structure","Medium"),
@("Pathos appeals to:","Logic","Emotion","Credibility","Ethics","b","Emotion","Hard"),
@("Logos appeals to:","Emotion","Logic and reason","Credibility","Fear","b","Logic and reason","Hard"),
@("Analyze means to:","Simply describe","Break down and examine","Ignore details","Summarize only","b","Break down and examine","Hard"),
@("Synthesis in writing means:","Copying sources","Combining multiple sources into new ideas","Ignoring sources","Summarizing one source","b","Combining sources","Hard"),
@("A qualified claim:","Is always true","Uses hedging language appropriately","Is always false","Avoids all evidence","b","Uses hedging appropriately","Hard"),
@("Ethos is established by:","Being emotional","Demonstrating credibility","Using big words","Being loud","b","Demonstrating credibility","Hard"),
@("Kairos refers to:","The speaker","The audience","Timeliness and relevance","The evidence","c","Timeliness and relevance","Hard"),
@("A warrant in argument is:","Evidence","The logical connection between claim and evidence","A conclusion","A counterargument","b","Logical connection","Hard"),
@("An implicit claim is:","Clearly stated","Implied but not directly stated","Always false","A question","b","Implied not stated","Hard"),
@("Toulmin model includes:","Only evidence","Claim, grounds, warrant","Just conclusions","Only opposition","b","Claim, grounds, warrant","Hard")
)

$bank["VC"] = @(
@("'Resilient' means:","Weak","Able to recover quickly","Slow","Tall","b","Able to recover","Easy"),
@("'Abundant' means:","Scarce","Large quantity","Small","Empty","b","Large quantity","Easy"),
@("'Candid' means:","Secretive","Frank and honest","Shy","Angry","b","Frank and honest","Easy"),
@("'Diminish' means:","Increase","Make smaller","Maintain","Destroy","b","Make smaller","Easy"),
@("'Vivid' means:","Dull","Bright and clear","Dark","Vague","b","Bright and clear","Easy"),
@("'Convey' means:","Hide","Transport or communicate","Take","Push","b","Transport or communicate","Easy"),
@("'Adequate' means:","Insufficient","Sufficient","Too much","Perfect","b","Sufficient","Easy"),
@("'Inevitable' means:","Avoidable","Certain to happen","Optional","Unlikely","b","Certain to happen","Easy"),
@("'Venerate' means:","Hate","Respect greatly","Ignore","Punish","b","Respect greatly","Easy"),
@("'Tedious' means:","Exciting","Long and boring","Short","Dangerous","b","Long and boring","Easy"),
@("'Exemplify' means:","Contradict","Serve as example","Ignore","Deny","b","Serve as example","Medium"),
@("'Pernicious' means:","Harmful","Helpful","Neutral","Small","a","Harmful","Medium"),
@("'Ameliorate' means:","Worsen","Make better","Maintain","Destroy","b","Make better","Medium"),
@("'Cognizant' means:","Unaware","Aware","Confused","Sleepy","b","Aware","Medium"),
@("'Eloquent' means:","Inarticulate","Fluent and persuasive","Silent","Loud","b","Fluent and persuasive","Medium"),
@("'Fallacy' means:","Truth","Misleading reasoning","Fact","Proof","b","Misleading reasoning","Medium"),
@("'Ostensible' means:","Actual","Apparent but not necessarily real","Hidden","Proven","b","Apparent","Medium"),
@("'Sporadic' means:","Frequent","Occurring irregularly","Constant","Daily","b","Irregular","Medium"),
@("'Tenacious' means:","Giving up","Holding firmly","Weak","Flexible","b","Holding firmly","Medium"),
@("'Unprecedented' means:","Common","Never done before","Repeated","Normal","b","Never before","Medium"),
@("'Ephemeral' means:","Permanent","Short-lived","Eternal","Strong","b","Short-lived","Hard"),
@("'Sycophant' means:","Leader","Flatterer","Worker","Teacher","b","Flatterer","Hard"),
@("'Equivocal' means:","Clear","Ambiguous","Certain","Direct","b","Ambiguous","Hard"),
@("'Pragmatic' means:","Theoretical","Practical","Idealistic","Romantic","b","Practical","Hard"),
@("'Lucid' means:","Confused","Clear and easy to understand","Dark","Complex","b","Clear","Hard"),
@("'Perfunctory' means:","Thorough","Done without care","Detailed","Careful","b","Without care","Hard"),
@("'Clandestine' means:","Open","Secret","Public","Legal","b","Secret","Hard"),
@("'Erudite' means:","Ignorant","Learned and knowledgeable","Simple","Lazy","b","Learned","Hard"),
@("'Capricious' means:","Steady","Given to sudden change","Reliable","Calm","b","Sudden change","Hard"),
@("'Obsequious' means:","Independent","Excessively obedient","Brave","Honest","b","Excessively obedient","Hard")
)

$bank["IG"] = @(
@("A bar graph is best for:","Showing trends over time","Comparing categories","Showing parts of whole","Showing correlation","b","Comparing categories","Easy"),
@("On a line graph, the x-axis usually shows:","Dependent variable","Categories","Independent variable","Values","c","Independent variable","Easy"),
@("A pie chart shows:","Trends","Correlations","Parts of a whole","Changes over time","c","Parts of a whole","Easy"),
@("A scale on a graph:","Shows colors","Renders data proportional","Is decorative","Hides data","b","Renders proportional","Easy"),
@("An outlier in data:","Is always wrong","Is far from other values","Is the average","Is the median","b","Far from other values","Easy"),
@("Reading a table, you should first:","Read the title","Look at colors","Skip to data","Guess answers","a","Title gives context","Easy"),
@("A histogram shows:","Categorical data","Continuous data distribution","Parts of whole","Time series","b","Continuous distribution","Easy"),
@("A scatter plot shows:","Parts of whole","Correlation between variables","Categorical comparison","Time trends","b","Correlation","Easy"),
@("The legend of a graph:","Hides data","Explains symbols/colors","Is optional","Shows errors","b","Explains symbols/colors","Easy"),
@("Data in a table is read by:","Ignoring headers","Reading title, headers, then data","Only reading numbers","Skipping rows","b","Title, headers, then data","Easy"),
@("When reading a graph, always check:","The colors only","Axis labels and scale","The font size","Paper quality","b","Axis labels and scale","Medium"),
@("A trend line on a scatter plot:","Connects all dots","Shows general direction","Is always straight","Removes outliers","b","Shows general direction","Medium"),
@("To compare two datasets, use:","One pie chart","A double bar graph","A single number","A word","b","Double bar graph","Medium"),
@("Rate of change is shown by:","A flat line","The slope of a line","The y-intercept","The title","b","Slope of a line","Medium"),
@("A box plot shows:","Individual data points","Five-number summary","Parts of whole","Correlation","b","Five-number summary","Medium"),
@("The y-intercept represents:","Rate of change","Starting value","Maximum value","Average","b","Starting value","Medium"),
@("A cumulative frequency graph shows:","Individual values","Running total of frequencies","Parts of whole","Just the mode","b","Running total","Medium"),
@("When data points cluster, the data has:","No pattern","A trend","Random values","Zero correlation","b","A trend","Medium"),
@("An interval on an axis represents:","A single value","A range of values","An error","Nothing","b","A range of values","Medium"),
@("To estimate from a graph:","Be exact always","Use the scale to approximate","Ignore the graph","Guess","b","Use scale to approximate","Medium"),
@("A misleading graph may:","Use proper scale","Distort data visually","Show all data","Be accurate","b","Distort data visually","Hard"),
@("In interpreting data, correlation does not imply:","A relationship","Causation","Connection","Similarity","b","Causation","Hard"),
@("A logarithmic scale is used when:","Data is linear","Data spans many orders of magnitude","Data is small","Data is categorical","b","Spans many orders","Hard"),
@("Stacked bar charts show:","Just totals","Composition and total","Individual points","Time trends","b","Composition and total","Hard"),
@("To determine reliability of graph data, check:","Colors","Source and methodology","Font","Size","b","Source and methodology","Hard"),
@("Residuals in scatter plots show:","Trend direction","Deviation from trend line","Correlation","Mean","b","Deviation from trend","Hard"),
@("A confidence interval represents:","Exact value","Range of plausible values","Single prediction","Error only","b","Range of plausible values","Hard"),
@("Extrapolation beyond data range is:","Always reliable","Potentially unreliable","Always accurate","Necessary","b","Potentially unreliable","Hard"),
@("In a time series, seasonality means:","Random variation","Regular periodic pattern","Trend","Outlier","b","Regular periodic pattern","Hard"),
@("Simpson's paradox occurs when:","Data is clear","Trends reverse when groups combined","Graphs are misleading","Data is missing","b","Trends reverse","Hard")
)

$bank["ER"] = @(
@("Evidence-based reasoning requires:","Only opinions","Claims supported by evidence","No proof needed","Just emotions","b","Claims supported by evidence","Easy"),
@("A claim in an argument is:","Evidence only","The main point being argued","A conclusion","A counterargument","b","Main point being argued","Easy"),
@("Supporting evidence should be:","Irrelevant","Relevant and credible","Made up","Vague","b","Relevant and credible","Easy"),
@("Inference means:","Stating facts directly","Drawing conclusions from evidence","Guessing randomly","Ignoring data","b","Drawing conclusions","Easy"),
@("Text evidence includes:","Personal stories only","Quotes, data, examples","Just opinions","Nothing","b","Quotes, data, examples","Easy"),
@("An objective analysis:","Only uses emotion","Uses facts and logic","Ignores evidence","Is always short","b","Uses facts and logic","Easy"),
@("Cause and effect shows:","Random events","Relationship between events","Opposite trends","Nothing","b","Relationship between events","Easy"),
@("Drawing conclusions requires:","Ignoring evidence","Logical thinking from evidence","Just guessing","No reading","b","Logical thinking","Easy"),
@("A well-supported argument:","Has no evidence","Uses multiple credible sources","Relies on emotion only","Is always short","b","Multiple credible sources","Easy"),
@("Reading comprehension means:","Reading fast","Understanding what is read","Skipping words","Guessing","b","Understanding","Easy"),
@("To evaluate evidence, check:","Source credibility","Length of text","Number of pages","Font size","a","Source credibility","Medium"),
@("Synthesis combines:","Opposing views only","Ideas from multiple sources","Single source","No sources","b","Ideas from multiple sources","Medium"),
@("A logical conclusion follows from:","Random guesses","Premises and evidence","Emotions","Opposition","b","Premises and evidence","Medium"),
@("Bias in a source means:","Perfect objectivity","Partiality toward a viewpoint","Accuracy","Credibility","b","Partiality","Medium"),
@("Correlation suggests:","No relationship","A relationship may exist","Causation always","Nothing","b","Relationship may exist","Medium"),
@("Primary sources are:","Secondhand accounts","Original, firsthand evidence","Summaries","Reviews","b","Original evidence","Medium"),
@("To identify assumptions, look for:","Stated facts","Unstated beliefs underlying argument","Conclusions","Evidence","b","Unstated beliefs","Medium"),
@("A strong inference:","Ignores evidence","Follows logically from text","Contradicts text","Is random","b","Follows from text","Medium"),
@("Evaluating an argument includes:","Only agreeing","Checking logic and evidence","Ignoring claims","Being emotional","b","Checking logic and evidence","Medium"),
@("Context of evidence matters because:","It does not","It affects interpretation","It is irrelevant","It wastes time","b","Affects interpretation","Medium"),
@("A fallacy is:","Strong evidence","A flaw in reasoning","A conclusion","A fact","b","Flaw in reasoning","Hard"),
@("Straw man fallacy:","Strengthens argument","Misrepresents opponent's position","Uses facts","Is logical","b","Misrepresents position","Hard"),
@("Ad hominem attacks:","Use evidence","Target the person, not argument","Are logical","Strengthen claims","b","Target the person","Hard"),
@("Circular reasoning:","Is logical","Uses conclusion as premise","Provides evidence","Is persuasive","b","Uses conclusion as premise","Hard"),
@("To distinguish fact from opinion:","All statements are facts","Check if verifiable","Ignore differences","Assume all opinions","b","Check if verifiable","Hard"),
@("Anecdotal evidence is:","Very strong","Personal experience, limited generalizability","Always accurate","Scientific","b","Limited generalizability","Hard"),
@("Confirmation bias means:","Being objective","Favoring info that confirms beliefs","Ignoring all evidence","Being thorough","b","Favoring confirming beliefs","Hard"),
@("Corroborating evidence:","Contradicts","Supports from independent source","Is optional","Weakens","b","Supports independently","Hard"),
@("Hasty generalization is:","Thorough analysis","Drawing broad conclusions from few cases","Careful research","Logical","b","Few cases to broad conclusion","Hard"),
@("To strengthen reasoning, eliminate:","Evidence","Logical fallacies","Claims","Conclusions","b","Logical fallacies","Hard")
)

$bank["PQ"] = @(
@("What are related quantities?","Unrelated things","Quantities that vary together","Random values","Constants","b","Vary together","Easy"),
@("In y=2x, if x doubles, y:","Stays same","Doubles","Halves","Triples","b","y doubles","Easy"),
@("A proportional relationship passes through:","(0,1)","(0,0)","(1,1)","(-1,-1)","b","Origin","Easy"),
@("If y=kx, k is called:","Slope","Constant of proportionality","y-intercept","Variable","b","Constant of proportionality","Easy"),
@("Direct proportion means:","Sum is constant","Ratio is constant","Product is constant","Difference is constant","b","Ratio constant","Easy"),
@("In inverse proportion xy=k, if x increases y:","Increases","Decreases","Stays same","Doubles","b","Decreases","Easy"),
@("Two quantities are proportional if:","Their graph is curved","Their ratio is constant","They are unrelated","Their sum is constant","b","Ratio is constant","Easy"),
@("If a=kb and k=3, when b=4, a=?","7","12","1","4","b","3*4=12","Easy"),
@("Which shows direct proportion?","y=x+1","y=3x","y=x^2","y=1/x","b","y=3x","Easy"),
@("Unit rate is:","Total rate","Rate per one unit","Average rate","No rate","b","Rate per one unit","Easy"),
@("If distance is proportional to time at constant speed, doubling time means:","Same distance","Double distance","Triple distance","Halve distance","b","Double distance","Medium"),
@("In y=k/x, if x triples, y:","Triples","Divides by 3","Stays same","Multiplies by 9","b","Divides by 3","Medium"),
@("A graph of y=3x+2 is:","Proportional","Not proportional","Inverse","Constant","b","Not proportional","Medium"),
@("If 5 workers build in 8 days, 10 workers take:","16 days","8 days","4 days","2 days","c","4 days","Medium"),
@("Constant of proportionality from table x=2,y=6:","2","3","6","12","b","6/2=3","Medium"),
@("Speed is a relationship between:","Distance and weight","Distance and time","Time and color","Weight and cost","b","Distance and time","Medium"),
@("If y varies directly as x and y=10 when x=5, y when x=8?","14","16","18","20","b","y=2x, y=16","Medium"),
@("Density relates:","Volume and color","Mass and volume","Length and width","Time and date","b","Mass and volume","Medium"),
@("If pressure and volume are inversely proportional, halving volume:","Doubles pressure","Halves pressure","No change","Triples pressure","a","Doubles pressure","Medium"),
@("Scaling a recipe is an example of:","Inverse proportion","Direct proportion","No relationship","Random","b","Direct proportion","Medium"),
@("In physics, F=ma shows force is proportional to:","Mass only","Acceleration only","Both mass and acceleration","Neither","c","Both","Hard"),
@("If z varies jointly as x and y, z=12 when x=2,y=3, z when x=4,y=5?","30","40","50","60","b","k=2, z=2*4*5=40","Hard"),
@("Square-cube law relates:","Linear dimensions to area/volume","Only areas","Only volumes","Nothing","a","Linear to area/volume","Hard"),
@("In exponential growth, rate of change is:","Constant","Proportional to current value","Zero","Decreasing","b","Proportional to current","Hard"),
@("If A prop to B and B prop to C, then A prop to:","B+C","B-C","C","B*D","c","C","Hard"),
@("Work rate problems use:","Only addition","Only subtraction","Proportional relationships","Random values","c","Proportional","Hard"),
@("If y=kx^n and doubling x quadruples y, n=?","1","2","3","4","b","2^2=4, n=2","Hard"),
@("Gear ratios demonstrate:","Inverse proportion","Direct proportion","No proportion","Random","b","Direct proportion","Hard"),
@("Ohm's law V=IR shows V proportional to:","I only","R only","I and R","Neither","c","Both","Hard"),
@("If area of circle doubles, radius increases by:","sqrt(2)","2","4","8","a","r prop to sqrt(A)","Hard")
)

$bank["RP"] = @(
@("A ratio compares:","Two things by subtraction","Two quantities","A number to itself","Nothing","b","Two quantities","Easy"),
@("The ratio 3:5 can be written as:","3/5","5/3","3+5","3*5","a","3/5","Easy"),
@("A proportion states:","Two ratios are equal","Two numbers are different","Ratios are zero","Nothing","a","Two ratios equal","Easy"),
@("If 2:5 = x:20, x=?","4","6","8","10","c","8:20 = 2:5","Easy"),
@("Unit rate means:","Rate for 1 unit","Total rate","No rate","Rate for all","a","Rate for 1 unit","Easy"),
@("3:4 = 6:8 is an example of:","A ratio","A proportion","A fraction","A decimal","b","Proportion","Easy"),
@("Scale factor is used in:","Cooking only","Maps and models","Nothing","Music","b","Maps and models","Easy"),
@("If a/b = c/d, then:","a*d = b*c","a+c = b+d","a-b = c-d","a*b = c*d","a","Cross multiplication","Easy"),
@("A ratio of 1:4 means:","1 out of 5 total","1 out of 4 total","4 out of 1 total","4 out of 5 total","b","1:4 ratio","Easy"),
@("Simplify the ratio 12:16:","3:4","4:3","6:8","2:3","a","12:16=3:4","Easy"),
@("If 3 apples cost $6, cost of 5 apples?","$8","$9","$10","$12","c","$10","Medium"),
@("A map scale 1:100000 means 1cm = ?","1km","10km","100km","1000km","a","1km","Medium"),
@("Proportional relationships graph as:","Curves","Straight lines through origin","Horizontal lines","Vertical lines","b","Straight through origin","Medium"),
@("If x:y = 2:3 and x=10, y=?","12","15","18","20","b","y=15","Medium"),
@("Cross multiply to solve: 3/7 = x/21","x=6","x=7","x=9","x=12","c","x=9","Medium"),
@("Golden ratio is approximately:","1:1","1:1.618","1:2","1:3","b","1:1.618","Medium"),
@("A recipe uses 2:3 flour to sugar. For 6 cups flour, sugar?","6","8","9","12","c","9 cups","Medium"),
@("Speed = distance/time is a:","Ratio","Proportion","Equation","Both a and c","d","Both ratio and equation","Medium"),
@("If 5:7 = 15:x, x=?","18","21","25","35","b","x=21","Medium"),
@("Probability can be expressed as:","Only percentage","Ratio, fraction, decimal","Only decimal","Only fraction","b","Multiple forms","Medium"),
@("In similar triangles, side ratios are:","Different","Equal","Random","Zero","b","Equal","Hard"),
@("If a:b = 3:5 and b:c = 2:3, a:c = ?","6:15","9:10","5:9","3:2","a","a:c = 6:15","Hard"),
@("Fibonacci ratios approach:","1:1","The golden ratio","2:1","1:2","b","Golden ratio","Hard"),
@("In dilations, coordinates scale by:","Addition","Subtraction","Scale factor","Random","c","Scale factor","Hard"),
@("If 12 workers build in 10 days, 20 workers take:","5","6","8","12","b","6 days","Hard"),
@("Map 3cm represents 15km. Scale?","1:50000","1:100000","1:500000","1:1000000","a","1:500000","Hard"),
@("A gear ratio of 3:1 means:","Output is 3x faster","Input is 3x faster","Same speed","Output stops","a","Output 3x faster","Hard"),
@("Compound ratios a:b:c means:","a+b+c","a:b and b:c","Only a:b","Nothing","b","a:b and b:c","Hard"),
@("Direct proportion graph slope = ?","Rate of change","y-intercept","x-intercept","Origin","a","Rate of change","Hard"),
@("If y prop to x^2, doubling x means y:","Doubles","Triples","Quadruples","Halves","c","Quadruples","Hard")
)

$bank["PC"] = @(
@("What is 10% of 50?","5","10","15","50","a","0.10*50=5","Easy"),
@("25% as a decimal is:","0.25","2.5","25","0.025","a","0.25","Easy"),
@("50% of 200 = ?","50","75","100","150","c","100","Easy"),
@("What is 15% of 200?","20","25","30","35","c","30","Easy"),
@("Percent means per:","10","50","100","1000","c","Per 100","Easy"),
@("3/4 as a percent is:","25%","50%","75%","100%","c","75%","Easy"),
@("If price is $80 and tax is 10%, total?","$80","$88","$90","$100","b","$88","Easy"),
@("0.5 as a percent is:","5%","50%","500%","0.5%","b","50%","Easy"),
@("A 20% discount on $50 saves:","$5","$10","$15","$20","b","$10","Easy"),
@("1/5 as a percent is:","5%","10%","20%","25%","c","20%","Easy"),
@("A shirt $40 on sale 25% off. Sale price?","$25","$30","$35","$40","b","$30","Medium"),
@("Population grows 200 to 250, percent increase?","20%","25%","50%","125%","b","25%","Medium"),
@("What is 33.3% of 90?","22","27","30","33","c","30","Medium"),
@("30% of x = 45, x=?","100","135","150","200","c","150","Medium"),
@("Price goes $60 to $45. Percent decrease?","15%","20%","25%","30%","c","25%","Medium"),
@("125% of 80 = ?","80","90","100","100","c","100","Medium"),
@("40% girls, 120 boys, total?","160","180","200","300","b","180","Medium"),
@("0.375 as a percent is:","3.75%","37.5%","375%","0.0375%","b","37.5%","Medium"),
@("Success rate 18/24 as percent?","65%","70%","75%","80%","c","75%","Medium"),
@("Value triples, percent increase?","100%","200%","300%","400%","b","200%","Medium"),
@("Value up 50% then down 50%, net change?","No change","25% decrease","25% increase","50% decrease","b","25% decrease","Hard"),
@("A's salary 20% more than B's. B's is what % less than A's?","16.7%","20%","25%","30%","a","16.7%","Hard"),
@("Compound interest uses:","Simple percent","Exponential growth","Linear growth","No percent","b","Exponential growth","Hard"),
@("Tax 15%, total $115, original price?","$85","$90","$100","$110","c","$100","Hard"),
@("Markup 60% on cost $50, selling price?","$70","$75","$80","$90","c","$80","Hard"),
@("Value decreases 10% yearly 2 years from 100:","81","80","90","82","a","81","Hard"),
@("2 is what percent of 5?","20%","25%","40%","50%","c","40%","Hard"),
@("15% of x is 45, then 30% of x is:","60","75","90","120","c","90","Hard"),
@("40% to 50% is:","10% increase","25% increase","50% increase","100% increase","a","10 percentage points","Hard"),
@("$120 after 20% increase, original?","$96","$100","$108","$110","b","$100","Hard")
)

$bank["DI"] = @(
@("Data interpretation begins with:","Calculating","Reading the title and labels","Making graphs","Guessing","b","Read title and labels","Easy"),
@("A table shows data in:","Pictures only","Rows and columns","Graphs","Sentences","b","Rows and columns","Easy"),
@("To find a value in a table, locate:","Random cell","Row and column intersection","Title only","Last cell","b","Row and column","Easy"),
@("A trend in data means:","Random values","A general pattern","No pattern","Errors","b","General pattern","Easy"),
@("To compare values, you should:","Pick randomly","Look at the numbers carefully","Ignore data","Guess","b","Look at numbers","Easy"),
@("A data set's range is:","Max value","Min value","Max minus min","Average","c","Max minus min","Easy"),
@("Reading a chart:","Skip the labels","Check axes and legend","Ignore units","Just guess","b","Check axes and legend","Easy"),
@("An increase in data means:","Values go down","Values go up","Values stay same","No data","b","Values go up","Easy"),
@("Average means:","Maximum","Sum divided by count","Minimum","Range","b","Sum divided by count","Easy"),
@("Data can be represented by:","Only tables","Tables, graphs, charts","Only graphs","Nothing","b","Multiple formats","Easy"),
@("When reading a line graph, check:","Color only","Scales, axes, and units","Paper size","Font","b","Scales, axes, units","Medium"),
@("To find percent increase:","New-old/old * 100","Old-new/new * 100","New*old/100","New+old","a","(New-old)/old * 100","Medium"),
@("A median is:","Most frequent value","Middle value when ordered","Average","Sum","b","Middle value","Medium"),
@("Data outliers should be:","Always removed","Noted and considered","Ignored always","Doubled","b","Noted and considered","Medium"),
@("To calculate mean:","Add and divide","Multiply values","Count only","Find middle","a","Add and divide","Medium"),
@("A frequency table shows:","Prices","How often values occur","Colors","Names","b","How often values occur","Medium"),
@("Percent of a total:","Part/whole * 100","Whole/part * 100","Part*whole","Part+whole","a","Part/whole * 100","Medium"),
@("Cumulative data shows:","Individual values","Running totals","Just the last value","Errors","b","Running totals","Medium"),
@("A grouped frequency table:","Lists every value","Groups values into intervals","Shows no data","Is always wrong","b","Groups into intervals","Medium"),
@("To estimate from a chart:","Be exact","Use visual scale","Ignore chart","Guess","b","Use visual scale","Medium"),
@("Misleading data can be caused by:","Accurate scales","Truncated axes","Complete data","Clear labels","b","Truncated axes","Hard"),
@("Standard deviation measures:","Average","Spread of data","Middle value","Maximum","b","Spread of data","Hard"),
@("A data distribution shows:","Single value","How values are spread","Only maximum","Only minimum","b","How values spread","Hard"),
@("Sampling bias means:","Perfect sample","Unrepresentative sample","Large sample","Small sample","b","Unrepresentative sample","Hard"),
@("In interpreting graphs, beware of:","Clear labels","Distorted scales","Proper legends","Accurate data","b","Distorted scales","Hard"),
@("A box-and-whisker plot shows:","Individual data points","Five-number summary","Correlation","Parts of whole","b","Five-number summary","Hard"),
@("Mode is useful for:","Continuous data","Categorical data","All data","No data","b","Categorical data","Hard"),
@("Scatter plot correlation r=0.95 means:","No correlation","Strong positive","Strong negative","Weak positive","b","Strong positive","Hard"),
@("To avoid misinterpretation:","Ignore context","Consider context and sources","Read only numbers","Skip headings","b","Consider context","Hard"),
@("Statistical significance means:","Large sample","Result unlikely by chance","Always important","Big numbers","b","Unlikely by chance","Hard")
)

$bank["SA"] = @(
@("Science passages primarily:","Tell stories","Present factual information","Express opinions","Entertain","b","Present factual information","Easy"),
@("Scientific method includes:","Guessing only","Observation, hypothesis, testing","No steps","Just conclusions","b","Observation, hypothesis, testing","Easy"),
@("A hypothesis is:","A proven fact","A testable prediction","A conclusion","A question","b","Testable prediction","Easy"),
@("Variables in an experiment:","Are random","Include independent and dependent","Are constants","Don't matter","b","Independent and dependent","Easy"),
@("Data in science:","Is always perfect","Supports or refutes hypothesis","Is irrelevant","Can be ignored","b","Supports or refutes","Easy"),
@("A control group:","Receives treatment","Is the baseline for comparison","Is the variable","Does nothing","b","Baseline for comparison","Easy"),
@("Scientific notation expresses:","Small numbers only","Large or small numbers","Only fractions","Nothing","b","Large or small numbers","Easy"),
@("Cause and effect in science:","Is always clear","Links variables","Is random","Doesn't exist","b","Links variables","Easy"),
@("Graphs in science show:","Nothing useful","Relationships between variables","Just numbers","Colors only","b","Relationships between variables","Easy"),
@("Peer review means:","Self-check","Expert evaluation","No review","Public vote","b","Expert evaluation","Easy"),
@("Scientific conclusions should be:","Emotional","Based on evidence","Unsupported","Personal","b","Based on evidence","Medium"),
@("A theory in science:","Is just a guess","Is well-supported explanation","Is always wrong","Cannot be tested","b","Well-supported explanation","Medium"),
@("Independent variable is:","What you measure","What you change","What stays constant","Nothing","b","What you change","Medium"),
@("Dependent variable is:","What you change","What stays constant","What you measure","Independent","c","What you measure","Medium"),
@("Correlation vs causation means:","They are the same","Correlation doesn't prove causation","Neither matters","Both are proven","b","Correlation doesn't prove causation","Medium"),
@("A law in science:","Is a rule based on observations","Is always true forever","Is a guess","Cannot change","a","Rule based on observations","Medium"),
@("Extrapolation from data:","Is always accurate","Extends beyond measured range","Is dangerous","Is never done","b","Extends beyond measured range","Medium"),
@("Sample size affects:","Nothing","Reliability of results","Color of graph","Paper quality","b","Reliability of results","Medium"),
@("A model in science:","Is a physical copy only","Represents a system","Is always perfect","Cannot be tested","b","Represents a system","Medium"),
@("Error in measurements:","Should be hidden","Should be reported","Is always zero","Means failure","b","Should be reported","Medium"),
@("Double-blind studies:","Use two people","Neither subjects nor researchers know groups","Use two methods","Are always better","b","Neither knows groups","Hard"),
@("Randomized controlled trials:","Use volunteers only","Randomly assign subjects","Have no control","Use no data","b","Randomly assign subjects","Hard"),
@("Confidence intervals show:","Exact answer","Range where true value likely lies","Nothing","Error","b","Range of likely values","Hard"),
@("Null hypothesis means:","There is an effect","There is no effect","The experiment failed","Data is wrong","b","No effect","Hard"),
@("Type I error is:","Missing a real effect","False positive","Correct result","Type II","b","False positive","Hard"),
@("Meta-analysis combines:","Single studies","Results from multiple studies","No data","Graphs","b","Results from multiple studies","Hard"),
@("A confounding variable:","Helps results","Provides alternative explanation","Is controlled","Is measured","b","Alternative explanation","Hard"),
@("Publication bias means:","All studies published","Positive results more likely published","No bias","All rejected","b","Positive results preferred","Hard"),
@("Replication in science means:","Copying exactly","Repeating experiments to verify","Doing once","Ignoring","b","Repeating to verify","Hard"),
@("Bayesian reasoning updates:","Never changes","Probabilities based on new evidence","Assumptions","Nothing","b","Probabilities with evidence","Hard")
)

$bank["SS"] = @(
@("Social science studies:","Rocks","Human behavior and society","Plants","Chemicals","b","Human behavior and society","Easy"),
@("Primary sources in social science:","Textbooks","Original research data","Wikipedia","Summaries","b","Original research","Easy"),
@("A theory in social science:","Is just opinion","Explains social phenomena","Is random","Cannot be tested","b","Explains social phenomena","Easy"),
@("Social science research methods include:","Only surveys","Surveys, experiments, observation","Only experiments","Nothing","b","Multiple methods","Easy"),
@("Demographics study:","Weather","Population characteristics","Animals","Plants","b","Population characteristics","Easy"),
@("Variables in social science:","Are random","Include social factors","Don't exist","Are only numbers","b","Include social factors","Easy"),
@("A sample in research is:","Everyone","A subset of the population","The whole population","Nothing","b","Subset of population","Easy"),
@("Survey questions should be:","Leading","Neutral and clear","Confusing","Biased","b","Neutral and clear","Easy"),
@("Ethics in research means:","No rules","Protecting participants","Ignoring consent","Being unfair","b","Protecting participants","Easy"),
@("Census means:","Partial count","Counting everyone in population","Sampling","Guessing","b","Counting everyone","Easy"),
@("Correlation in social science:","Is causation","Shows relationship between variables","Is meaningless","Always positive","b","Shows relationship","Medium"),
@("Qualitative research studies:","Numbers only","Meanings, experiences, opinions","Only statistics","Nothing","b","Meanings and experiences","Medium"),
@("Quantitative research focuses on:","Opinions","Numerical data and statistics","Stories","Colors","b","Numerical data","Medium"),
@("Bias in surveys can come from:","Large samples","Question wording and sampling","Random selection","Accurate data","b","Question wording","Medium"),
@("Longitudinal studies:","Are short","Follow subjects over time","Use no data","Are cheap","b","Follow over time","Medium"),
@("Cross-sectional studies:","Follow over years","Capture snapshot at one time","Are longitudinal","Use no data","b","Snapshot at one time","Medium"),
@("Sociology studies:","Individual psychology","Social structures and groups","Biology","Chemistry","b","Social structures","Medium"),
@("Economics studies:","Weather patterns","Production, distribution, consumption","Literature","Art","b","Goods and services","Medium"),
@("Political science examines:","Math equations","Government, power, and policies","Plants","Animals","b","Government and policies","Medium"),
@("A peer-reviewed journal:","Has no review process","Expert-evaluated before publication","Is a magazine","Is a blog","b","Expert-evaluated","Medium"),
@("Statistical significance means:","Large effect","Result unlikely due to chance","Always meaningful","Small sample","b","Unlikely due to chance","Hard"),
@("Ecological fallacy:","Study of ecology","Drawing individual conclusions from group data","Is always correct","Is minor","b","Group to individual error","Hard"),
@("Selection bias means:","Random sampling","Non-representative sample","Perfect sample","Large sample","b","Non-representative","Hard"),
@("Confirmation bias in research:","Is good","Favoring data that supports beliefs","Being objective","Ignoring all data","b","Favoring supporting data","Hard"),
@("Triangulation in research:","Uses one method","Uses multiple methods for validity","Is about triangles","Is geometry","b","Multiple methods","Hard"),
@("Grounded theory develops:","From top down","From data upward","From assumptions","From nothing","b","From data upward","Hard"),
@("Discourse analysis studies:","Math only","Language in social context","Physics","Chemistry","b","Language in social context","Hard"),
@("Ethnography involves:","Only surveys","Immersion in a cultural group","Lab experiments","Nothing","b","Immersion in culture","Hard"),
@("Mixed methods research:","Uses no methods","Combines quantitative and qualitative","Uses one method","Is always wrong","b","Combines both approaches","Hard"),
@("Hawthorne effect:","Type of plant","Subjects change behavior when observed","Is insignificant","Is a theory","b","Behavior changes when observed","Hard")
)

$bank["HA"] = @(
@("Primary historical sources are:","Secondhand accounts","Original documents from the time","Written much later","Opinions only","b","Original documents","Easy"),
@("Historical context means:","Current events","The conditions surrounding an event","Future predictions","Nothing","b","Conditions surrounding event","Easy"),
@("Chronology means:","Random order","Arrangement in time order","Alphabetical order","By size","b","Time order","Easy"),
@("A primary source could be:","A textbook","A diary from the period","A modern analysis","A summary","b","Diary from the period","Easy"),
@("Periodization divides history into:","Random parts","Meaningful time periods","Single events","Nothing","b","Meaningful periods","Easy"),
@("Bias in historical writing:","Does not exist","Affects how events are presented","Is always obvious","Doesn't matter","b","Affects presentation","Easy"),
@("Cause in history:","Is always simple","Multiple factors contribute","Is random","Doesn't exist","b","Multiple factors","Easy"),
@("Effect in history:","Is immediate only","Can be long-term","Is always positive","Doesn't exist","b","Can be long-term","Easy"),
@("A secondary source is:","A diary","An analysis written later","An original document","A photograph","b","Analysis written later","Easy"),
@("Historical significance means:","Happened recently","Had lasting impact","Is well-known","Is old","b","Had lasting impact","Easy"),
@("To analyze a historical document:","Read the title only","Consider source, purpose, and context","Ignore it","Guess","b","Consider source, purpose, context","Medium"),
@("Historical perspective means:","Modern viewpoint only","Understanding events in their time","Ignoring context","Being biased","b","Events in their time","Medium"),
@("Change over time refers to:","Nothing changing","How things evolve","Static events","Random","b","How things evolve","Medium"),
@("Continuity means:","Total change","Things that remain the same","End of era","New events","b","Things that remain the same","Medium"),
@("Historical evidence includes:","Only documents","Artifacts, documents, oral accounts","Nothing","Only photographs","b","Multiple types of evidence","Medium"),
@("Analyze means:","Describe only","Examine parts and their relationships","Ignore","Skip","b","Examine relationships","Medium"),
@("Historiography studies:","Geography","How history is written and interpreted","Math","Science","b","How history is written","Medium"),
@("Bias detection requires:","Ignoring sources","Comparing multiple perspectives","One source only","No thinking","b","Comparing perspectives","Medium"),
@("Contextualization means:","Ignoring background","Placing events in broader context","Focusing on one detail","Nothing","b","Broader context","Medium"),
@("Period labels like Renaissance help:","Confuse students","Organize and understand eras","Hide information","Do nothing","b","Organize and understand","Medium"),
@("Counterfactual history:","Is certain","Asks what if questions","Ignores evidence","Is proven","b","Asks what-if questions","Hard"),
@("Historical causation is:","Always simple","Complex and multi-causal","Random","Nonexistent","b","Complex and multi-causal","Hard"),
@("Comparative history:","Compares nothing","Analyzes similarities/differences","Ignores differences","Is always easy","b","Similarities/differences","Hard"),
@("Post-colonial analysis examines:","Modern architecture","Impact of colonialism on societies","Weather patterns","Math","b","Impact of colonialism","Hard"),
@("Marxist historical analysis focuses on:","Religion","Class struggle and economic factors","Art","Music","b","Class and economics","Hard"),
@("Feminist history examines:","Only men's history","Women's experiences and gender roles","Nothing","Only recent events","b","Women's experiences","Hard"),
@("Oral history sources:","Are unreliable only","Capture personal experiences","Are always accurate","Cannot be used","b","Capture personal experiences","Hard"),
@("Archaeological evidence:","Is always complete","Provides material evidence of past","Is useless","Is always accurate","b","Material evidence","Hard"),
@("Revisionist history:","Is always wrong","Re-examines past interpretations","Ignores evidence","Changes nothing","b","Re-examines interpretations","Hard"),
@("Multiple causation means:","One cause only","Several factors interact to cause events","No causes","Random","b","Several factors interact","Hard")
)

$bank["LA"] = @(
@("Literary analysis examines:","Math problems","Literary works and their elements","Science experiments","Recipes","b","Literary elements","Easy"),
@("A theme in literature is:","The setting","The central idea or message","The characters","The plot length","b","Central idea","Easy"),
@("The narrator is:","The author always","The voice telling the story","A character","The reader","b","Voice telling the story","Easy"),
@("Conflict in a story is:","The setting","The central struggle or problem","The resolution","The theme","b","Central struggle","Easy"),
@("Point of view refers to:","The author's opinion","Perspective from which story is told","The setting","The plot","b","Perspective of telling","Easy"),
@("Imagery in literature:","Is visual only","Appeals to the senses","Is boring","Has no purpose","b","Appeals to senses","Easy"),
@("A metaphor is:","A comparison using like/as","A direct comparison without like/as","A sound effect","A type of character","b","Direct comparison","Easy"),
@("Simile compares using:","Equals","Like or as","Numbers","Nothing","b","Like or as","Easy"),
@("The setting includes:","Just the date","Time, place, and atmosphere","Only weather","Characters only","b","Time, place, atmosphere","Easy"),
@("Dialogue in a story is:","Description only","Characters' spoken words","The narrator's thoughts","The theme","b","Characters' spoken words","Easy"),
@("Symbolism uses:","Literal objects only","Objects to represent ideas","Nothing","Just colors","b","Objects represent ideas","Medium"),
@("Foreshadowing:","Looks back","Hints at future events","Ignores plot","Ends story","b","Hints at future events","Medium"),
@("A flashback:","Shows the future","Returns to past events","Ignores time","Is boring","b","Returns to past events","Medium"),
@("Irony in literature:","Is always funny","Contrast between expectation and reality","Is serious only","Has no meaning","b","Contrast expectation vs reality","Medium"),
@("A protagonist is:","The villain","The main character","A minor character","The narrator only","b","Main character","Medium"),
@("An antagonist is:","The hero","Opposes the protagonist","A friend","The setting","b","Opposes protagonist","Medium"),
@("Tone in literature:","Is the plot","The author's attitude toward subject","The setting","The characters","b","Author's attitude","Medium"),
@("Mood in literature:","The author's attitude","The feeling the reader gets","The plot","The theme","b","Reader's feeling","Medium"),
@("Alliteration:","Repetition of vowel sounds","Repetition of initial consonant sounds","A type of rhyme","A metaphor","b","Initial consonant repetition","Medium"),
@("Personification:","Makes humans into objects","Gives human qualities to non-human things","Is a simile","Is irony","b","Human qualities to non-human","Medium"),
@("Allegory:","A type of poem","Story with hidden symbolic meaning","A character type","A setting","b","Hidden symbolic meaning","Hard"),
@("Unreliable narrator:","Tells truth always","May not present events accurately","Is the author","Is always villain","b","May not be accurate","Hard"),
@("Stream of consciousness:","Is organized","Mimics continuous flow of thoughts","Is linear","Has no meaning","b","Flow of thoughts","Hard"),
@("Free verse:","Has strict rules","Has no regular meter or rhyme","Is always short","Is prose","b","No regular meter/rhyme","Hard"),
@("Denouement:","Is the beginning","Is the resolution after climax","Is the conflict","Is the setting","b","Resolution after climax","Hard"),
@("In medias res:","Starts at the end","Starts in the middle of action","Is chronological","Has no beginning","b","Starts in middle of action","Hard"),
@("Motif:","A single occurrence","A recurring element throughout","The theme","The setting","b","Recurring element","Hard"),
@("Juxtaposition:","Ignoring differences","Placing contrasting elements side by side","Repeating words","Using metaphors","b","Contrasting elements side by side","Hard"),
@("Archetype:","A modern invention","A universal, recurring pattern","A unique character","A single symbol","b","Universal recurring pattern","Hard"),
@("Pathetic fallacy:","Is always wrong","Using weather to reflect emotions","A type of irony","A character","b","Weather reflects emotions","Hard")
)

$bank["WR"] = @(
@("Revision means:","Spelling check only","Reconsidering content and structure","Writing once","Ignoring errors","b","Content and structure","Easy"),
@("Editing focuses on:","Big ideas","Grammar, punctuation, spelling","New content","Plot changes","b","Grammar and mechanics","Easy"),
@("A strong topic sentence:","Is vague","Clearly states paragraph's main idea","Is always last","Is a question","b","States main idea","Easy"),
@("Concise writing:","Uses many words","Uses few words to convey meaning","Is always long","Repeats itself","b","Few words, clear meaning","Easy"),
@("Transitional words:","Are unnecessary","Connect ideas between sentences","Replace evidence","End paragraphs","b","Connect ideas","Easy"),
@("Active voice:","Is passive","Has clear subject performing action","Is always wrong","Is confusing","b","Subject performs action","Easy"),
@("A thesis statement:","Is a question","States the essay's main argument","Is always last paragraph","Is optional","b","States main argument","Easy"),
@("Proofreading:","Rewrites everything","Checks for errors before final","Adds new content","Changes thesis","b","Checks for errors","Easy"),
@("Relevant evidence:","Is off-topic","Supports the paragraph's point","Is always a quote","Is made up","b","Supports the point","Easy"),
@("Sentence variety:","Uses same structure repeatedly","Uses different sentence structures","Is always complex","Is always simple","b","Different structures","Easy"),
@("A topic sentence should:","Be vague","State the paragraph's controlling idea","Be very long","Repeat the thesis","b","State controlling idea","Medium"),
@("Eliminate wordiness:","Use more words","Remove unnecessary words","Add filler","Repeat","b","Remove unnecessary words","Medium"),
@("Parallel structure means:","Different patterns","Consistent grammatical patterns","Random","No structure","b","Consistent patterns","Medium"),
@("A strong conclusion:","Introduces new evidence","Synthesizes and evaluates","Repeats body","Asks new questions","b","Synthesizes and evaluates","Medium"),
@("Effective introduction:","Skips context","Engages reader and provides context","Is very long","Starts with definition","b","Engages and provides context","Medium"),
@("Cohesion means:","Random ideas","Logical connection between sentences","Long paragraphs","No structure","b","Logical connections","Medium"),
@("A well-developed paragraph:","Has one sentence","Has evidence and analysis","Is always short","Has no topic sentence","b","Has evidence and analysis","Medium"),
@("Sentence fragments:","Are complete sentences","Are incomplete thoughts","Are always correct","Are formal","b","Incomplete thoughts","Medium"),
@("Comma splices can be fixed by:","Adding more commas","Using semicolons or conjunctions","Removing punctuation","Ignoring","b","Semicolons or conjunctions","Medium"),
@("An effective essay:","Lacks organization","Has clear structure and logical flow","Is always long","Repeats itself","b","Clear structure and flow","Medium"),
@("Hedging language:","Is always wrong","Softens absolute claims appropriately","Is too confident","Shows no knowledge","b","Softens claims appropriately","Hard"),
@("Nominalizations:","Are active verbs","Turn verbs into nouns, often weakening prose","Are always better","Are concise","b","Turn verbs into nouns","Hard"),
@("Dangling participles:","Are correct grammar","Modify wrong subject","Are always clear","Add meaning","b","Modify wrong subject","Hard"),
@("Register consistency means:","Mixing formal and casual","Maintaining appropriate level throughout","Being always casual","Being always formal","b","Maintaining appropriate level","Hard"),
@("Annotated bibliography:","Just lists sources","Lists sources with evaluations","Is a textbook","Is optional","b","Sources with evaluations","Hard"),
@("Synthesis in writing:","Copies sources","Integrates multiple sources into new argument","Ignores sources","Uses one source","b","Integrates multiple sources","Hard"),
@("Concessive clauses:","Are always wrong","Acknowledge counterpoints before main claim","Are redundant","Add no meaning","b","Acknowledge counterpoints","Hard"),
@("Semantic cohesion:","Uses grammar only","Uses related vocabulary throughout","Is random","Uses no connections","b","Related vocabulary throughout","Hard"),
@("Qualifying claims:","Makes them weaker","Adds appropriate nuance and precision","Removes all certainty","Makes them false","b","Adds nuance and precision","Hard"),
@("Discourse markers:","Are filler words","Guide reader through argument structure","Are nouns","Are conclusions","b","Guide reader through argument","Hard")
)

$bank["IC"] = @(
@("'Break the ice' means:","Literally break ice","Initiate conversation in social setting","Start a fight","Fall down","b","Initiate conversation","Easy"),
@("'Hit the nail on the head' means:","Construction work","Be exactly right","Hit something","Miss the point","b","Be exactly right","Easy"),
@("'Piece of cake' means:","A dessert","Something very easy","A small portion","A recipe","b","Something very easy","Easy"),
@("'Under the weather' means:","Outside in rain","Feeling ill","Cold outside","Wet","b","Feeling ill","Easy"),
@("'Cost an arm and a leg' means:","Medical expense","Very expensive","Cheap","Free","b","Very expensive","Easy"),
@("'Bite the bullet' means:","Eating something","Endure something painful","Running away","Sleeping","b","Endure pain","Easy"),
@("'Let the cat out of the bag' means:","Releasing a cat","Revealing a secret","Going shopping","Cooking","b","Revealing a secret","Easy"),
@("'Kill two birds with one stone' means:","Hunting","Solve two problems with one action","Be cruel","Be efficient only","b","Solve two problems","Easy"),
@("'A blessing in disguise' means:","Religious event","Something good that seems bad at first","A costume","Bad luck","b","Good that seems bad","Easy"),
@("'Actions speak louder than words' means:","Shout more","Doing is more important than saying","Be quiet","Run fast","b","Doing > saying","Easy"),
@("'Burning the midnight oil' means:","Fire hazard","Working late at night","Cooking","Sleeping late","b","Working late","Easy"),
@("'The ball is in your court' means:","Playing sports","It's your decision or turn","Running away","Watching TV","b","Your turn/decision","Medium"),
@("'Barking up the wrong tree' means:","Pet care","Making a wrong assumption","Being loud","Climbing","b","Wrong assumption","Medium"),
@("'Caught between a rock and a hard place' means:","Geology","Facing a difficult choice","Easy situation","No choice","b","Difficult choice","Medium"),
@("'Don't judge a book by its cover' means:","Reading advice","Don't judge by appearance","Buy books","Library rules","b","Don't judge by appearance","Medium"),
@("'Every cloud has a silver lining' means:","Weather","Bad situations have positive aspects","Clouds are silver","Look up","b","Positives in bad situations","Medium"),
@("'Go the extra mile' means:","Exercise","Put in more effort than required","Walk far","Drive","b","Extra effort","Medium"),
@("'Hit the sack' means:","Fighting","Go to sleep","Buy bedding","Exercise","b","Go to sleep","Medium"),
@("'On thin ice' means:","Skating","In a risky situation","Cold weather","Safe","b","Risky situation","Medium"),
@("'The best of both worlds' means:","Universe","Benefit from two situations simultaneously","Astronomy","Fantasy","b","Two benefits at once","Medium"),
@("'Blessing in disguise' in context means:","A costume","An apparent misfortune that turns out well","Religious","Secret","b","Misfortune turns well","Medium"),
@("'Burn bridges' means:","Build fire","Destroy relationships irreparably","Cook","Cross river","b","Destroy relationships","Hard"),
@("'Cut corners' means:","Geometry","Do something poorly to save time/money","Cut paper","Be precise","b","Do poorly to save","Hard"),
@("'Hit the nail on the head' in writing means:","Construction","Describe exactly the right thing","Be wrong","Be vague","b","Exactly right","Hard"),
@("'Let sleeping dogs lie' means:","Pet care","Don't disturb a situation","Wake up dogs","Sleep","b","Don't disturb","Hard"),
@("'Once in a blue moon' means:","Astronomy","Very rarely","Every month","Always","b","Very rarely","Hard"),
@("'Pull someone's leg' means:","Medical","Joke with someone","Run fast","Exercise","b","Joke with someone","Hard"),
@("'Read between the lines' means:","Reading speed","Understand implied meaning","Skip text","Speed read","b","Implied meaning","Hard"),
@("'The elephant in the room' means:","Zoo visit","An obvious problem everyone ignores","Large furniture","Animal","b","Obvious ignored problem","Hard"),
@("'Turn a blind eye' means:","Medical","Deliberately ignore something","See better","Look away","b","Deliberately ignore","Hard")
)

$allQuestions = @()
$questionNum = 0
foreach ($ch in $chapters) {
    $code = $ch[0]
    $name = $ch[1]
    $idx = $chapters.IndexOf($ch) + 1
    $chapterName = "Grade 10 - Chapter ${idx}: $name"
    $qs = $bank[$code]
    
    for ($i = 0; $i -lt $qs.Count; $i++) {
        $q = $qs[$i]
        $qNum = "{0:D2}" -f ($i + 1)
        $questionNum++
        
        $obj = [ordered]@{
            id = "SAT-10-$code-$qNum"
            subject = "SAT"
            stream = "Common"
            chapter = $chapterName
            yearEC = "2024 E.C."
            questionText = $q[0]
            hasImage = $false
            imagePlaceholder = ""
            options = @(
                @{id="a";text=$q[1]},
                @{id="b";text=$q[2]},
                @{id="c";text=$q[3]},
                @{id="d";text=$q[4]}
            )
            correctOptionId = $q[5]
            explanation = $q[6]
            difficulty = $q[7]
        }
        $allQuestions += $obj
    }
}

$json = $allQuestions | ConvertTo-Json -Depth 5
$json | Out-File -FilePath $out -Encoding UTF8
Write-Host "Generated $questionNum questions to $out"
