import json

questions = []

# ============================================================
# CHAPTER 1: Atomic Structure and Periodic Properties
# ============================================================
ch1_name = "Grade 11 - Chapter 1: Atomic Structure and Periodic Properties of the Elements"

ch1 = [
    {"id":"CHM-11-01-01","questionText":"How many electrons can the third shell (n=3) hold at maximum?","options":[{"id":"a","text":"2"},{"id":"b","text":"8"},{"id":"c","text":"18"},{"id":"d","text":"32"}],"correctOptionId":"c","explanation":"The maximum number of electrons in shell n is 2n\u00b2. For n=3, 2(3\u00b2) = 18 electrons.","difficulty":"Easy"},
    {"id":"CHM-11-01-02","questionText":"The principal quantum number (n) determines:","options":[{"id":"a","text":"The shape of the orbital"},{"id":"b","text":"The size and energy of the orbital"},{"id":"c","text":"The orientation of the orbital"},{"id":"d","text":"The spin of the electron"}],"correctOptionId":"b","explanation":"The principal quantum number (n) determines the size and energy level of the orbital.","difficulty":"Easy"},
    {"id":"CHM-11-01-03","questionText":"What is the maximum number of electrons that can occupy a p subshell?","options":[{"id":"a","text":"2"},{"id":"b","text":"6"},{"id":"c","text":"10"},{"id":"d","text":"14"}],"correctOptionId":"b","explanation":"A p subshell has 3 orbitals, and each orbital holds 2 electrons, giving a maximum of 6 electrons.","difficulty":"Easy"},
    {"id":"CHM-11-01-04","questionText":"Which quantum number describes the shape of an orbital?","options":[{"id":"a","text":"Principal quantum number (n)"},{"id":"b","text":"Azimuthal quantum number (l)"},{"id":"c","text":"Magnetic quantum number (ml)"},{"id":"d","text":"Spin quantum number (ms)"}],"correctOptionId":"b","explanation":"The azimuthal quantum number (l) determines the shape of the orbital (s, p, d, f).","difficulty":"Easy"},
    {"id":"CHM-11-01-05","questionText":"According to the Aufbau principle, electrons fill orbitals starting from:","options":[{"id":"a","text":"Highest energy to lowest energy"},{"id":"b","text":"Lowest energy to highest energy"},{"id":"c","text":"Randomly"},{"id":"d","text":"Outermost shell inward"}],"correctOptionId":"b","explanation":"The Aufbau principle states that electrons fill orbitals starting from the lowest energy level to the highest.","difficulty":"Easy"},
    {"id":"CHM-11-01-06","questionText":"Hund's rule states that:","options":[{"id":"a","text":"No two electrons can have the same set of four quantum numbers"},{"id":"b","text":"Electrons fill degenerate orbitals singly before pairing"},{"id":"c","text":"Electrons always pair up in the same orbital"},{"id":"d","text":"Only two electrons can occupy an atom"}],"correctOptionId":"b","explanation":"Hund's rule states that electrons fill degenerate (equal energy) orbitals singly with parallel spins before pairing.","difficulty":"Easy"},
    {"id":"CHM-11-01-07","questionText":"How many orbitals are in the d subshell?","options":[{"id":"a","text":"1"},{"id":"b","text":"3"},{"id":"c","text":"5"},{"id":"d","text":"7"}],"correctOptionId":"c","explanation":"The d subshell has 5 orbitals (ml values: -2, -1, 0, +1, +2), each holding up to 2 electrons.","difficulty":"Easy"},
    {"id":"CHM-11-01-08","questionText":"The electron configuration of carbon (Z=6) is:","options":[{"id":"a","text":"1s\u00b2 2s\u00b2 2p\u00b2"},{"id":"b","text":"1s\u00b2 2s\u00b2 2p\u2076"},{"id":"c","text":"1s\u00b2 2s\u00b9 2p\u00b3"},{"id":"d","text":"1s\u00b2 2s\u00b2 3s\u00b2"}],"correctOptionId":"a","explanation":"Carbon has 6 electrons: 1s\u00b2 (2) + 2s\u00b2 (2) + 2p\u00b2 (2) = 6 electrons.","difficulty":"Easy"},
    {"id":"CHM-11-01-09","questionText":"Ionization energy generally increases across a period because:","options":[{"id":"a","text":"Atomic radius increases"},{"id":"b","text":"Nuclear charge increases and shielding remains roughly constant"},{"id":"c","text":"Number of neutrons increases"},{"id":"d","text":"Electronegativity decreases"}],"correctOptionId":"b","explanation":"Across a period, nuclear charge increases while shielding stays relatively constant, making it harder to remove electrons.","difficulty":"Easy"},
    {"id":"CHM-11-01-10","questionText":"Which of the following has the smallest atomic radius?","options":[{"id":"a","text":"Na"},{"id":"b","text":"Mg"},{"id":"c","text":"Al"},{"id":"d","text":"Si"}],"correctOptionId":"d","explanation":"Atomic radius decreases across a period from left to right. Si is furthest to the right, so it has the smallest radius.","difficulty":"Easy"},
    {"id":"CHM-11-01-11","questionText":"The Pauli exclusion principle states that:","options":[{"id":"a","text":"Electrons fill the lowest energy orbitals first"},{"id":"b","text":"No two electrons in the same atom can have the same set of four quantum numbers"},{"id":"c","text":"Electrons occupy degenerate orbitals singly first"},{"id":"d","text":"Each orbital can hold a maximum of 4 electrons"}],"correctOptionId":"b","explanation":"The Pauli exclusion principle states that no two electrons in an atom can have identical sets of all four quantum numbers.","difficulty":"Medium"},
    {"id":"CHM-11-01-12","questionText":"What is the electron configuration of Fe (Z=26)?","options":[{"id":"a","text":"[Ar] 3d\u2076 4s\u00b2"},{"id":"b","text":"[Ar] 3d\u2078"},{"id":"c","text":"[Ar] 3d\u2075 4s\u00b2 4p\u00b9"},{"id":"d","text":"[Ar] 3d\u2077 4s\u00b9"}],"correctOptionId":"a","explanation":"Iron (Z=26) has the configuration [Ar] 3d\u2076 4s\u00b2. The 4s orbital fills before 3d.","difficulty":"Medium"},
    {"id":"CHM-11-01-13","questionText":"The set of quantum numbers n=3, l=2, ml=+1, ms=+\u00bd represents:","options":[{"id":"a","text":"A 3s electron"},{"id":"b","text":"A 3p electron"},{"id":"c","text":"A 3d electron"},{"id":"d","text":"An impossible set of quantum numbers"}],"correctOptionId":"c","explanation":"l=2 corresponds to a d orbital. With n=3, this is a 3d electron. ml=+1 is within the allowed range.","difficulty":"Medium"},
    {"id":"CHM-11-01-14","questionText":"Which element has the highest first ionization energy in period 3?","options":[{"id":"a","text":"Na"},{"id":"b","text":"Mg"},{"id":"c","text":"Al"},{"id":"d","text":"Ar"}],"correctOptionId":"d","explanation":"Ionization energy generally increases across a period. Ar, a noble gas with a complete octet, has the highest first IE in period 3.","difficulty":"Medium"},
    {"id":"CHM-11-01-15","questionText":"Which element is the most electronegative on the periodic table?","options":[{"id":"a","text":"Fluorine"},{"id":"b","text":"Chlorine"},{"id":"c","text":"Oxygen"},{"id":"d","text":"Nitrogen"}],"correctOptionId":"a","explanation":"Fluorine is the most electronegative element (EN = 4.0), located at the top right (excluding noble gases).","difficulty":"Medium"},
    {"id":"CHM-11-01-16","questionText":"Which of the following ions has the same electron configuration as Ar?","options":[{"id":"a","text":"K\u207a"},{"id":"b","text":"Na\u207a"},{"id":"c","text":"Li\u207a"},{"id":"d","text":"Be\u00b2\u207a"}],"correctOptionId":"a","explanation":"Ar has 18 electrons. K\u207a has lost one electron from K (19), giving 18 electrons, same as Ar.","difficulty":"Medium"},
    {"id":"CHM-11-01-17","questionText":"Cr adopts [Ar] 3d\u2075 4s\u00b9 instead of [Ar] 3d\u2074 4s\u00b2 because:","options":[{"id":"a","text":"Half-filled d subshell provides extra stability"},{"id":"b","text":"Chromium is a transition metal"},{"id":"c","text":"The 4s orbital is higher in energy than 3d"},{"id":"d","text":"Copper displaces chromium"}],"correctOptionId":"a","explanation":"Half-filled and fully filled d subshells have extra stability. Cr adopts [Ar] 3d\u2075 4s\u00b9 to achieve a half-filled 3d subshell.","difficulty":"Medium"},
    {"id":"CHM-11-01-18","questionText":"Atomic radius decreases across a period because:","options":[{"id":"a","text":"More electron shells are added"},{"id":"b","text":"Increased nuclear charge pulls electrons closer"},{"id":"c","text":"Shielding increases significantly"},{"id":"d","text":"Mass number decreases"}],"correctOptionId":"b","explanation":"Across a period, protons are added to the nucleus and electrons to the same shell. The increased nuclear charge pulls the electron cloud closer.","difficulty":"Medium"},
    {"id":"CHM-11-01-19","questionText":"Which quantum numbers are allowed for a 4f orbital?","options":[{"id":"a","text":"n=4, l=3"},{"id":"b","text":"n=4, l=4"},{"id":"c","text":"n=4, l=2"},{"id":"d","text":"n=3, l=3"}],"correctOptionId":"a","explanation":"For an f orbital, l=3. With n=4, this gives a 4f orbital. l must be less than n, so l=3 is valid.","difficulty":"Medium"},
    {"id":"CHM-11-01-20","questionText":"The second ionization energy of sodium is much higher than its first because:","options":[{"id":"a","text":"The second electron is removed from a noble gas configuration"},{"id":"b","text":"Sodium has only one electron"},{"id":"c","text":"The second electron is heavier"},{"id":"d","text":"Nuclear charge decreases after first ionization"}],"correctOptionId":"a","explanation":"After losing one electron, Na\u207a has the stable neon configuration [Ne]. Removing a second electron requires breaking this stable configuration.","difficulty":"Hard"},
    {"id":"CHM-11-01-21","questionText":"Which pair shows an anomaly in the trend of first ionization energies across period 2?","options":[{"id":"a","text":"Li to Be increases"},{"id":"b","text":"Be to B decreases"},{"id":"c","text":"N to O increases"},{"id":"d","text":"F to Ne increases"}],"correctOptionId":"b","explanation":"B has a lower first IE than Be because B's outermost electron is in a higher-energy 2p orbital, easier to remove than Be's 2s electron.","difficulty":"Hard"},
    {"id":"CHM-11-01-22","questionText":"The total number of possible values of ml for l=3 is:","options":[{"id":"a","text":"3"},{"id":"b","text":"5"},{"id":"c","text":"7"},{"id":"d","text":"9"}],"correctOptionId":"c","explanation":"For l=3, ml ranges from -3 to +3: -3, -2, -1, 0, +1, +2, +3 = 7 values.","difficulty":"Hard"},
    {"id":"CHM-11-01-23","questionText":"The correct order of increasing first ionization energy is:","options":[{"id":"a","text":"Na < Al < Mg < Si"},{"id":"b","text":"Na < Mg < Al < Si"},{"id":"c","text":"Al < Na < Mg < Si"},{"id":"d","text":"Na < Al < Si < Mg"}],"correctOptionId":"a","explanation":"Mg (3s\u00b2, full subshell) has higher IE than Al (3s\u00b2 3p\u00b9), so the order is Na < Al < Mg < Si.","difficulty":"Hard"},
    {"id":"CHM-11-01-24","questionText":"The electron configuration of Cu (Z=29) is:","options":[{"id":"a","text":"[Ar] 3d\u2079 4s\u00b2"},{"id":"b","text":"[Ar] 3d\u00b9\u2070 4s\u00b9"},{"id":"c","text":"[Ar] 3d\u2078 4s\u00b2 4p\u00b9"},{"id":"d","text":"[Ar] 3d\u00b9\u2070 4s\u00b2"}],"correctOptionId":"b","explanation":"Cu adopts [Ar] 3d\u00b9\u2070 4s\u00b9 because a fully filled d subshell provides extra stability.","difficulty":"Hard"},
    {"id":"CHM-11-01-25","questionText":"Which of the following sets of quantum numbers is NOT possible?","options":[{"id":"a","text":"n=2, l=1, ml=-1, ms=+\u00bd"},{"id":"b","text":"n=3, l=3, ml=0, ms=-\u00bd"},{"id":"c","text":"n=4, l=2, ml=+2, ms=+\u00bd"},{"id":"d","text":"n=1, l=0, ml=0, ms=-\u00bd"}],"correctOptionId":"b","explanation":"For any orbital, l must be less than n. Here n=3 and l=3 violates this rule (l must be 0 to n-1).","difficulty":"Hard"},
    {"id":"CHM-11-01-26","questionText":"The electronegativity difference between Na and Cl in NaCl is approximately:","options":[{"id":"a","text":"0.5"},{"id":"b","text":"1.0"},{"id":"c","text":"2.1"},{"id":"d","text":"3.0"}],"correctOptionId":"c","explanation":"Na has EN ~0.9 and Cl has EN ~3.0. The difference is 3.0 - 0.9 = 2.1, indicating an ionic bond.","difficulty":"Hard"},
    {"id":"CHM-11-01-27","questionText":"Which period 3 element has the highest electron affinity?","options":[{"id":"a","text":"Na"},{"id":"b","text":"Si"},{"id":"c","text":"S"},{"id":"d","text":"Cl"}],"correctOptionId":"d","explanation":"Chlorine has the highest electron affinity in period 3, readily gaining one electron to achieve Ar configuration.","difficulty":"Hard"},
    {"id":"CHM-11-01-28","questionText":"How many unpaired electrons are in the ground state of Mn (Z=25)?","options":[{"id":"a","text":"1"},{"id":"b","text":"3"},{"id":"c","text":"5"},{"id":"d","text":"7"}],"correctOptionId":"c","explanation":"Mn is [Ar] 3d\u2075 4s\u00b2. The 3d subshell has 5 electrons, each in a separate orbital (Hund's rule), giving 5 unpaired electrons.","difficulty":"Hard"},
    {"id":"CHM-11-01-29","questionText":"The third ionization energy of Mg is much higher than the second because:","options":[{"id":"a","text":"Mg\u00b3\u207a has more protons"},{"id":"b","text":"The third electron is removed from a core shell (1s\u00b2 2s\u00b2 2p\u2076)"},{"id":"c","text":"Magnesium becomes a nonmetal"},{"id":"d","text":"Neutrons shield the third electron"}],"correctOptionId":"b","explanation":"After losing 2 electrons, Mg\u00b2\u207a has [Ne] configuration. The third electron must be removed from the stable 2p core, requiring far more energy.","difficulty":"Hard"},
    {"id":"CHM-11-01-30","questionText":"Which element has the electron configuration [Kr] 4d\u00b9\u2070 5s\u00b2 5p\u2075?","options":[{"id":"a","text":"Iodine"},{"id":"b","text":"Bromine"},{"id":"c","text":"Tellurium"},{"id":"d","text":"Xenon"}],"correctOptionId":"a","explanation":"The configuration has 53 electrons (Kr=36 + 10 + 2 + 5 = 53), which corresponds to Iodine, a halogen in period 5.","difficulty":"Hard"},
]

for q in ch1:
    questions.append({
        "id": q["id"],
        "subject": "Chemistry",
        "stream": "Natural Science",
        "chapter": ch1_name,
        "yearEC": "2024 E.C.",
        "questionText": q["questionText"],
        "hasImage": False,
        "imagePlaceholder": "",
        "options": q["options"],
        "correctOptionId": q["correctOptionId"],
        "explanation": q["explanation"],
        "difficulty": q["difficulty"]
    })

print(f"Chapter 1: {len(ch1)} questions added")

# ============================================================
# CHAPTER 2: Chemical Bonding
# ============================================================
ch2_name = "Grade 11 - Chapter 2: Chemical Bonding"

ch2 = [
    {"id":"CHM-11-02-01","questionText":"What type of bond forms between sodium and chlorine?","options":[{"id":"a","text":"Covalent bond"},{"id":"b","text":"Ionic bond"},{"id":"c","text":"Metallic bond"},{"id":"d","text":"Hydrogen bond"}],"correctOptionId":"b","explanation":"Na is a metal and Cl is a nonmetal with a large electronegativity difference, resulting in an ionic bond.","difficulty":"Easy"},
    {"id":"CHM-11-02-02","questionText":"A covalent bond is formed by:","options":[{"id":"a","text":"Transfer of electrons"},{"id":"b","text":"Sharing of electrons between atoms"},{"id":"c","text":"Attraction between positive and negative ions"},{"id":"d","text":"Attraction between delocalized electrons and metal ions"}],"correctOptionId":"b","explanation":"Covalent bonds form when two atoms share one or more pairs of valence electrons.","difficulty":"Easy"},
    {"id":"CHM-11-02-03","questionText":"How many lone pairs are on the oxygen atom in H\u2082O?","options":[{"id":"a","text":"0"},{"id":"b","text":"1"},{"id":"c","text":"2"},{"id":"d","text":"3"}],"correctOptionId":"c","explanation":"Oxygen in H\u2082O has 6 valence electrons: 2 used in bonding, leaving 4 electrons = 2 lone pairs.","difficulty":"Easy"},
    {"id":"CHM-11-02-04","questionText":"Which of the following is an ionic compound?","options":[{"id":"a","text":"CO\u2082"},{"id":"b","text":"H\u2082O"},{"id":"c","text":"NaCl"},{"id":"d","text":"CH\u2084"}],"correctOptionId":"c","explanation":"NaCl is formed between a metal (Na) and a nonmetal (Cl) with a large electronegativity difference, making it ionic.","difficulty":"Easy"},
    {"id":"CHM-11-02-05","questionText":"In metallic bonding:","options":[{"id":"a","text":"Electrons are localized between two atoms"},{"id":"b","text":"Electrons are transferred from metal to nonmetal"},{"id":"c","text":"Valence electrons are delocalized over a lattice of metal ions"},{"id":"d","text":"Hydrogen bonds hold the structure together"}],"correctOptionId":"c","explanation":"In metallic bonding, valence electrons are delocalized and shared among all metal ions in a sea of electrons.","difficulty":"Easy"},
    {"id":"CHM-11-02-06","questionText":"The Lewis symbol for magnesium (Mg) shows:","options":[{"id":"a","text":"Two dots"},{"id":"b","text":"Four dots"},{"id":"c","text":"Six dots"},{"id":"d","text":"Eight dots"}],"correctOptionId":"a","explanation":"Mg is in Group 2 and has 2 valence electrons, represented as two dots in its Lewis symbol.","difficulty":"Easy"},
    {"id":"CHM-11-02-07","questionText":"The molecular shape of CH\u2084 is:","options":[{"id":"a","text":"Linear"},{"id":"b","text":"Trigonal planar"},{"id":"c","text":"Tetrahedral"},{"id":"d","text":"Bent"}],"correctOptionId":"c","explanation":"CH\u2084 has 4 bonding pairs and 0 lone pairs around C, giving a tetrahedral geometry with bond angles of 109.5\u00b0.","difficulty":"Easy"},
    {"id":"CHM-11-02-08","questionText":"A single covalent bond consists of:","options":[{"id":"a","text":"One shared pair of electrons"},{"id":"b","text":"Two shared pairs of electrons"},{"id":"c","text":"Three shared pairs of electrons"},{"id":"d","text":"One transferred electron"}],"correctOptionId":"a","explanation":"A single covalent bond involves the sharing of one pair (2 electrons) between two atoms.","difficulty":"Easy"},
    {"id":"CHM-11-02-09","questionText":"Which type of intermolecular force exists between all molecules?","options":[{"id":"a","text":"Hydrogen bonding"},{"id":"b","text":"Dipole-dipole forces"},{"id":"c","text":"London dispersion forces"},{"id":"d","text":"Ionic bonding"}],"correctOptionId":"c","explanation":"London dispersion forces are present in all molecules due to temporary dipoles from electron movement.","difficulty":"Easy"},
    {"id":"CHM-11-02-10","questionText":"The electronegativity difference between bonded atoms determines:","options":[{"id":"a","text":"The molecular weight"},{"id":"b","text":"Whether the bond is ionic, polar covalent, or nonpolar covalent"},{"id":"c","text":"The number of atoms in the molecule"},{"id":"d","text":"The color of the compound"}],"correctOptionId":"b","explanation":"The electronegativity difference determines bond type: >1.7 is ionic, 0.4-1.7 is polar covalent, <0.4 is nonpolar covalent.","difficulty":"Easy"},
    {"id":"CHM-11-02-11","questionText":"According to VSEPR theory, the shape of NH\u2083 is:","options":[{"id":"a","text":"Trigonal planar"},{"id":"b","text":"Trigonal pyramidal"},{"id":"c","text":"Tetrahedral"},{"id":"d","text":"Linear"}],"correctOptionId":"b","explanation":"NH\u2083 has 4 electron pairs (3 bonding + 1 lone pair). The lone pair pushes the bonding pairs down, giving a trigonal pyramidal shape.","difficulty":"Medium"},
    {"id":"CHM-11-02-12","questionText":"The hybridization of the central carbon in ethene (C\u2082H\u2084) is:","options":[{"id":"a","text":"sp"},{"id":"b","text":"sp\u00b2"},{"id":"c","text":"sp\u00b3"},{"id":"d","text":"sp\u00b3d"}],"correctOptionId":"b","explanation":"Each carbon in ethene is bonded to 3 atoms (2 H and 1 C) with no lone pairs, requiring sp\u00b2 hybridization.","difficulty":"Medium"},
    {"id":"CHM-11-02-13","questionText":"Which molecule exhibits hydrogen bonding?","options":[{"id":"a","text":"CH\u2084"},{"id":"b","text":"HCl"},{"id":"c","text":"HF"},{"id":"d","text":"Br\u2082"}],"correctOptionId":"c","explanation":"HF has H bonded to F (a highly electronegative atom), enabling hydrogen bonding between HF molecules.","difficulty":"Medium"},
    {"id":"CHM-11-02-14","questionText":"The Lewis structure of CO\u2082 shows:","options":[{"id":"a","text":"Two single bonds"},{"id":"b","text":"Two double bonds"},{"id":"c","text":"One single and one triple bond"},{"id":"d","text":"Two triple bonds"}],"correctOptionId":"b","explanation":"CO\u2082 has two C=O double bonds (O=C=O) to satisfy the octet rule for all atoms.","difficulty":"Medium"},
    {"id":"CHM-11-02-15","questionText":"In BF\u2083, the boron atom is:","options":[{"id":"a","text":"sp hybridized with linear geometry"},{"id":"b","text":"sp\u00b2 hybridized with trigonal planar geometry"},{"id":"c","text":"sp\u00b3 hybridized with tetrahedral geometry"},{"id":"d","text":"Unhybridized with angular geometry"}],"correctOptionId":"b","explanation":"BF\u2083 has 3 bonding pairs and 0 lone pairs around B, requiring sp\u00b2 hybridization with trigonal planar shape.","difficulty":"Medium"},
    {"id":"CHM-11-02-16","questionText":"Which of the following molecules is nonpolar?","options":[{"id":"a","text":"H\u2082O"},{"id":"b","text":"NH\u2083"},{"id":"c","text":"CCl\u2084"},{"id":"d","text":"HCl"}],"correctOptionId":"c","explanation":"CCl\u2084 has a tetrahedral shape with symmetric C-Cl bond dipoles that cancel out, making it nonpolar.","difficulty":"Medium"},
    {"id":"CHM-11-02-17","questionText":"The bond angle in water (H\u2082O) is approximately:","options":[{"id":"a","text":"180\u00b0"},{"id":"b","text":"120\u00b0"},{"id":"c","text":"109.5\u00b0"},{"id":"d","text":"104.5\u00b0"}],"correctOptionId":"d","explanation":"H\u2082O has 4 electron pairs (2 bonding + 2 lone pairs). The lone pairs compress the bond angle to about 104.5\u00b0.","difficulty":"Medium"},
    {"id":"CHM-11-02-18","questionText":"VSEPR theory predicts molecules adjust their shape to:","options":[{"id":"a","text":"Maximize electron pair repulsion"},{"id":"b","text":"Minimize electron pair repulsion"},{"id":"c","text":"Maximize bond length"},{"id":"d","text":"Minimize the number of bonds"}],"correctOptionId":"b","explanation":"VSEPR theory states that electron pairs arrange themselves to minimize repulsion, determining molecular geometry.","difficulty":"Medium"},
    {"id":"CHM-11-02-19","questionText":"The hybridization of nitrogen in NH\u2083 is:","options":[{"id":"a","text":"sp"},{"id":"b","text":"sp\u00b2"},{"id":"c","text":"sp\u00b3"},{"id":"d","text":"sp\u00b3d"}],"correctOptionId":"c","explanation":"N in NH\u2083 has 3 bonding pairs and 1 lone pair = 4 electron pairs, requiring sp\u00b3 hybridization.","difficulty":"Medium"},
    {"id":"CHM-11-02-20","questionText":"Which intermolecular force is the strongest?","options":[{"id":"a","text":"London dispersion forces"},{"id":"b","text":"Dipole-dipole forces"},{"id":"c","text":"Hydrogen bonding"},{"id":"d","text":"Covalent bonding"}],"correctOptionId":"c","explanation":"Among intermolecular forces, hydrogen bonding is the strongest. Covalent bonding is an intramolecular force.","difficulty":"Medium"},
    {"id":"CHM-11-02-21","questionText":"The molecular geometry of SF\u2086 is:","options":[{"id":"a","text":"Trigonal bipyramidal"},{"id":"b","text":"Octahedral"},{"id":"c","text":"Square planar"},{"id":"d","text":"Pentagonal bipyramidal"}],"correctOptionId":"b","explanation":"SF\u2086 has 6 bonding pairs and 0 lone pairs around S, giving an octahedral geometry.","difficulty":"Hard"},
    {"id":"CHM-11-02-22","questionText":"The hybridization of carbon in ethyne (C\u2082H\u2082) is:","options":[{"id":"a","text":"sp"},{"id":"b","text":"sp\u00b2"},{"id":"c","text":"sp\u00b3"},{"id":"d","text":"sp\u00b3d"}],"correctOptionId":"a","explanation":"Each carbon in ethyne (H-C\u2261C-H) is bonded to 2 atoms with no lone pairs, requiring sp hybridization.","difficulty":"Hard"},
    {"id":"CHM-11-02-23","questionText":"Which of the following has the highest lattice energy?","options":[{"id":"a","text":"NaCl"},{"id":"b","text":"KCl"},{"id":"c","text":"MgO"},{"id":"d","text":"CaO"}],"correctOptionId":"c","explanation":"Lattice energy increases with higher charges and smaller ionic radii. MgO has 2+/2- charges and smaller ions than CaO.","difficulty":"Hard"},
    {"id":"CHM-11-02-24","questionText":"The shape of XeF\u2084 is:","options":[{"id":"a","text":"Tetrahedral"},{"id":"b","text":"Square planar"},{"id":"c","text":"See-saw"},{"id":"d","text":"Square pyramidal"}],"correctOptionId":"b","explanation":"XeF\u2084 has 6 electron pairs (4 bonding + 2 lone pairs). The 2 lone pairs occupy opposite positions, giving square planar geometry.","difficulty":"Hard"},
    {"id":"CHM-11-02-25","questionText":"The dipole moment of a molecule depends on:","options":[{"id":"a","text":"Only bond polarity"},{"id":"b","text":"Only molecular geometry"},{"id":"c","text":"Both bond polarity and molecular geometry"},{"id":"d","text":"Neither bond polarity nor molecular geometry"}],"correctOptionId":"c","explanation":"Dipole moment depends on both bond polarity and molecular geometry, which determines whether bond dipoles cancel.","difficulty":"Hard"},
    {"id":"CHM-11-02-26","questionText":"The hybridization of the central atom in ClF\u2083 is:","options":[{"id":"a","text":"sp\u00b3"},{"id":"b","text":"sp\u00b3d"},{"id":"c","text":"sp\u00b3d\u00b2"},{"id":"d","text":"sp\u00b2"}],"correctOptionId":"b","explanation":"ClF\u2083 has 5 electron pairs (3 bonding + 2 lone pairs) around Cl, requiring sp\u00b3d hybridization.","difficulty":"Hard"},
    {"id":"CHM-11-02-27","questionText":"Which has the shortest bond length?","options":[{"id":"a","text":"C-C (single bond)"},{"id":"b","text":"C=C (double bond)"},{"id":"c","text":"C\u2261C (triple bond)"},{"id":"d","text":"All are equal"}],"correctOptionId":"c","explanation":"Triple bonds are shorter than double bonds, which are shorter than single bonds, because more shared electrons pull atoms closer.","difficulty":"Hard"},
    {"id":"CHM-11-02-28","questionText":"The molecular geometry of PCl\u2085 is:","options":[{"id":"a","text":"Trigonal planar"},{"id":"b","text":"Trigonal bipyramidal"},{"id":"c","text":"Square pyramidal"},{"id":"d","text":"Pentagonal planar"}],"correctOptionId":"b","explanation":"PCl\u2085 has 5 bonding pairs and 0 lone pairs around P, giving a trigonal bipyramidal geometry.","difficulty":"Hard"},
    {"id":"CHM-11-02-29","questionText":"Which molecule has the highest boiling point?","options":[{"id":"a","text":"CH\u2084"},{"id":"b","text":"H\u2082O"},{"id":"c","text":"H\u2082S"},{"id":"d","text":"HCl"}],"correctOptionId":"b","explanation":"H\u2082O has hydrogen bonding (the strongest intermolecular force among these), giving it the highest boiling point.","difficulty":"Hard"},
    {"id":"CHM-11-02-30","questionText":"The formal charge on the central atom in ozone (O\u2083) is:","options":[{"id":"a","text":"+1"},{"id":"b","text":"-1"},{"id":"c","text":"0"},{"id":"d","text":"+2"}],"correctOptionId":"a","explanation":"In the dominant Lewis structure of O\u2083, the central O has 1 lone pair, 1 single bond, and 1 double bond. Formal charge = 6 - 2 - 3 = +1.","difficulty":"Hard"},
]

for q in ch2:
    questions.append({
        "id": q["id"],
        "subject": "Chemistry",
        "stream": "Natural Science",
        "chapter": ch2_name,
        "yearEC": "2024 E.C.",
        "questionText": q["questionText"],
        "hasImage": False,
        "imagePlaceholder": "",
        "options": q["options"],
        "correctOptionId": q["correctOptionId"],
        "explanation": q["explanation"],
        "difficulty": q["difficulty"]
    })

print(f"Chapter 2: {len(ch2)} questions added")
print(f"Total so far: {len(questions)}")

# Write partial result so far
with open(r"C:\Users\kal3n\Desktop\Projects\AceMatric\AceMatric\temp_chemistry_g11.json", "w", encoding="utf-8") as f:
    json.dump(questions, f, indent=2, ensure_ascii=False)

print("Part 1 written successfully")
