const fs = require('fs');
const path = require('path');

const ch19 = {
  chapterNumber: 19,
  title: "Reading Comprehension",
  overview: "Reading comprehension questions test your ability to understand, interpret, and analyze written passages. You will be presented with passages and asked questions about main ideas, supporting details, vocabulary in context, author's purpose, and logical inferences.",
  corePoints: ["Read the passage actively: underline key ideas","Identify the main idea and author's purpose","Distinguish between facts and opinions","Make logical inferences based on evidence","Understand vocabulary in context","Recognize passage structure: cause/effect, compare/contrast","Eliminate obviously wrong answers","Use the passage to support every answer"],
  examTips: "Reading comprehension passages typically appear as 2-3 passages with 3-5 questions each. They cover a range of topics: science, history, literature, and social studies.",
  youtubeVideoId: "placeholder",
  videoDuration: "16:30",
  materials: [
    {name:"Main Idea",formula:"",description:"The central point or argument of the passage. Often in the first or last paragraph."},
    {name:"Supporting Detail",formula:"",description:"Specific facts, examples, or evidence that support the main idea."},
    {name:"Inference",formula:"",description:"A conclusion drawn from the passage but not explicitly stated."},
    {name:"Vocabulary in Context",formula:"",description:"The meaning of a word as used in the passage. Use context clues."},
    {name:"Author's Purpose",formula:"",description:"The reason the author wrote the passage: to inform, persuade, entertain, or explain."},
    {name:"Tone and Attitude",formula:"",description:"The author's emotional stance: objective, critical, supportive, skeptical."},
    {name:"Passage Structure",formula:"",description:"How the passage is organized: compare/contrast, cause/effect, chronological."}
  ],
  subtopics: [
    {title:"19.1 Active Reading Strategies",content:"<p>Active reading is the key to success. Read carefully, underline key ideas, pay attention to transition words, and summarize each paragraph.</p><div class='formula-box'><strong>Active Reading Steps</strong><br/>1. Skim for overall meaning<br/>2. Read carefully, noting main ideas<br/>3. Underline key terms and transitions<br/>4. Summarize each paragraph<br/>5. Review passage structure</div>",examInsight:"Active reading saves time and improves accuracy.",practiceProblems:[{question:"What is the main idea of a passage about the Industrial Revolution's positive and negative effects?",options:["It started in Britain","It had both positive and negative effects","It caused social problems","It began in the 18th century"],answer:"B",solution:"<p>The main idea covers both positive and negative effects.</p>"},{question:"Which sentence best states the author's concern about the Amazon rainforest?",options:["It produces 20% of oxygen","It is home to diverse species","Deforestation threatens it","It is called the lungs of the Earth"],answer:"C",solution:"<p>The concern is about deforestation.</p>"},{question:"What is the author's purpose in describing a novel's plot and themes?",options:["To entertain","To inform about a novel","To persuade readers","To analyze a literary work"],answer:"B",solution:"<p>The purpose is to inform the reader about the novel.</p>"}]},
    {title:"19.2 Main Idea and Central Theme Questions",content:"<p>Main idea questions ask for the primary point. The main idea is often in the first or last paragraph. Eliminate answers that are too broad, too narrow, or just supporting details.</p><div class='formula-box'><strong>Finding the Main Idea</strong><br/>Look for topic sentence in each paragraph<br/>Ask: What is the author's overall point?<br/>Check first and last paragraphs<br/>Eliminate specific examples as answers</div>",examInsight:"Main idea questions are often the first question after a passage.",practiceProblems:[{question:"What is the main idea of a passage about honeybees being essential but declining?",options:["Honeybees pollinate crops","Populations are declining","Honeybees are important and at risk","Scientists are working to help"],answer:"C",solution:"<p>The main idea combines both: important and at risk.</p>"},{question:"What is the main idea of a passage about the Great Wall of China?",options:["It is a famous landmark","It was built for protection","It is made of stone","It is a tourist destination"],answer:"A",solution:"<p>The overall point is that it is a famous landmark.</p>"},{question:"What is the author's likely view on space exploration?",options:["It is wasteful","It is essential","It has pros and cons","It is dangerous"],answer:"B",solution:"<p>The author emphasizes benefits, suggesting support.</p>"}]},
    {title:"19.3 Supporting Detail Questions",content:"<p>Supporting detail questions ask for specific information directly stated in the passage. Locate the relevant section and find the exact answer.</p><div class='formula-box'><strong>Detail Question Strategy</strong><br/>1. Read the question carefully<br/>2. Scan for key words or synonyms<br/>3. Read surrounding sentences<br/>4. Find exact answer in passage</div>",examInsight:"These questions test your ability to locate information quickly.",practiceProblems:[{question:"According to a passage, what is the area of the Amazon rainforest?",options:["5.5 million square kilometers","6,400 square kilometers","9 million square kilometers","5.5 thousand square kilometers"],answer:"A",solution:"<p>Directly stated: 5.5 million square kilometers.</p>"},{question:"Which hemisphere is associated with creativity?",options:["Left","Right","Both","Neither"],answer:"B",solution:"<p>Directly stated: right hemisphere is associated with creativity.</p>"},{question:"How long did the first airplane flight last?",options:["12 seconds","120 seconds","12 minutes","120 minutes"],answer:"A",solution:"<p>Directly stated: it flew for 12 seconds.</p>"}]},
    {title:"19.4 Inference and Implication Questions",content:"<p>Inference questions ask you to draw a conclusion not explicitly stated. The answer must be logically supported by the text.</p><div class='formula-box'><strong>Inference Strategy</strong><br/>1. Read the passage for clues<br/>2. Identify what is implied<br/>3. Eliminate contradicting choices<br/>4. Choose most logical conclusion</div>",examInsight:"Inference questions require careful reading and logical reasoning.",practiceProblems:[{question:"Roman concrete knowledge was lost for centuries. What can be inferred?",options:["It was not durable","It was ahead of its time","It was easy to make","It was used only in aqueducts"],answer:"B",solution:"<p>Lost for centuries implies it was advanced for its time.</p>"},{question:"What can be inferred about the author's view of the internet?",options:["It is entirely harmful","The author is neutral","The author supports it","The author opposes social media"],answer:"C",solution:"<p>Benefits outweigh drawbacks suggests positive view.</p>"},{question:"Profits increased for five quarters. What can be inferred?",options:["It is losing money","It is performing well","It is about to fail","It has no competition"],answer:"B",solution:"<p>Profits increasing means performing well.</p>"}]},
    {title:"19.5 Vocabulary in Context",content:"<p>Vocabulary questions ask for the meaning of a word as used in the passage. Use context clues like restatement, contrast, and examples.</p><div class='formula-box'><strong>Vocabulary Strategy</strong><br/>1. Locate the word in passage<br/>2. Read surrounding sentences<br/>3. Look for definitions or contrasts<br/>4. Substitute each answer choice</div>",examInsight:"The correct answer may not be the most common definition.",practiceProblems:[{question:"'Skepticism' means in the context of doubting findings?",options:["Enthusiasm","Doubt","Acceptance","Curiosity"],answer:"B",solution:"<p>Context: 'who doubted her findings' defines skepticism.</p>"},{question:"'Bombastic' means in the context of exaggerated claims?",options:["Humble","Pompous","Sincere","Brief"],answer:"B",solution:"<p>Exaggerated claims suggests pompous or overblown.</p>"},{question:"'Esoteric' means when only experts understand?",options:["Simple","Obvious","Mysterious","Popular"],answer:"C",solution:"<p>Only experts understand suggests obscure or mysterious.</p>"}]},
    {title:"19.6 Author's Purpose and Tone",content:"<p>Author's purpose: why the passage was written. Tone: the author's attitude. Tone is revealed through word choice and style.</p><div class='formula-box'><strong>Purpose/Tone Strategy</strong><br/>Purpose: Look for persuasive language, facts, or stories<br/>Tone: Look for emotional or judgmental words<br/>Consider audience and context</div>",examInsight:"These questions require you to step back and consider the big picture.",practiceProblems:[{question:"'The policy will lead to disaster. It only serves the wealthy.' Author's purpose?",options:["To inform","To persuade","To entertain","To describe"],answer:"B",solution:"<p>Strong persuasive language suggests the purpose is to persuade.</p>"},{question:"'The exhibit is delightful with vibrant colors.' Author's tone?",options:["Critical","Enthusiastic","Indifferent","Sarcastic"],answer:"B",solution:"<p>Positive words suggest enthusiastic tone.</p>"},{question:"'The study's findings are inconclusive; more research is needed.' Author's purpose?",options:["To persuade","To entertain","To inform","To criticize"],answer:"C",solution:"<p>Neutral factual language suggests purpose is to inform.</p>"}]},
    {title:"19.7 Passage Structure and Organization",content:"<p>Understanding passage structure helps you follow the author's argument. Common structures: cause/effect, compare/contrast, chronological, problem/solution.</p><div class='formula-box'><strong>Common Structures</strong><br/>Cause/Effect: one event leads to another<br/>Compare/Contrast: similarities and differences<br/>Chronological: time order<br/>Problem/Solution: issue and resolution</div>",examInsight:"These questions test your understanding of how the passage is organized.",practiceProblems:[{question:"'First, mix chemicals. Then heat to 100C. Finally cool and filter.' Structure?",options:["Compare/Contrast","Chronological","Problem/Solution","Cause/Effect"],answer:"B",solution:"<p>Sequence of steps in order = chronological.</p>"},{question:"'While some species thrive, others face extinction. In contrast, adaptable species survive.' Structure?",options:["Compare/Contrast","Chronological","Problem/Solution","Cause/Effect"],answer:"A",solution:"<p>'While' and 'In contrast' signal comparison.</p>"},{question:"'Air pollution is a problem. Investing in public transport can reduce it.' Structure?",options:["Compare/Contrast","Chronological","Problem/Solution","Cause/Effect"],answer:"C",solution:"<p>Presents a problem and a solution.</p>"}]},
    {title:"19.8 Full Passage Practice",content:"<p>Practice with a full-length passage and multiple questions. Apply all strategies: active reading, main idea identification, detail location, inference, vocabulary, purpose/tone, and structure analysis.</p><div class='formula-box'><strong>Practice Passage</strong><br/>The invention of the printing press in the 15th century revolutionized the spread of knowledge. Before it, books were copied by hand, making them expensive and rare. The printing press made books more affordable and accessible, leading to a dramatic increase in literacy rates.</div>",examInsight:"Full passage practice is essential. Time yourself to simulate exam conditions.",practiceProblems:[{question:"What was a direct effect of the printing press?",options:["Books became more expensive","Literacy rates increased","Books were copied by hand","Education declined"],answer:"B",solution:"<p>The passage states literacy rates increased dramatically.</p>"},{question:"What was a problem with books before the printing press?",options:["They were too long","They were expensive and rare","They contained errors","They were in Latin"],answer:"B",solution:"<p>The passage states books were expensive and rare.</p>"},{question:"What can be inferred about the printing press's impact?",options:["Limited impact","Only affected religion","Widespread effects","Quickly replaced"],answer:"C",solution:"<p>'Far-reaching effects' implies widespread impact.</p>"},{question:"'Revolutionized' most nearly means:",options:["Slowly changed","Completely transformed","Slightly improved","Temporarily disrupted"],answer:"B",solution:"<p>The context suggests a major transformation.</p>"},{question:"The author's purpose is most likely to:",options:["Persuade readers","Inform about the impact","Entertain with a story","Criticize the printing press"],answer:"B",solution:"<p>Factual information suggests purpose is to inform.</p>"}]},
    {title:"19.9 Quantitative Comparison in Reading",content:"<p>Quantitative comparisons may appear in data-driven passages or questions that ask you to compare amounts, percentages, or trends.</p><div class='formula-box'><strong>Quantitative Reading</strong><br/>Read the data carefully<br/>Compare values from the passage<br/>Use evidence to support comparison</div>",examInsight:"These questions test your ability to interpret numerical data in a passage.",practiceProblems:[{question:"Population: 2000=1M, 2010=1.2M, 2020=1.5M. Quantity A: increase 2000-2010. Quantity B: increase 2010-2020.",options:["A is greater","B is greater","Equal","Cannot determine"],answer:"B",solution:"<p>A: 0.2M. B: 0.3M. B is greater.</p>"},{question:"Survey: 60% support, 30% oppose, 10% undecided. Quantity A: supporters. Quantity B: opponents.",options:["A is greater","B is greater","Equal","Cannot determine"],answer:"A",solution:"<p>60% > 30%. A is greater.</p>"}]}
  ]
};

fs.writeFileSync(path.resolve(__dirname, '..', '_chapter-data.json'), JSON.stringify(ch19, null, 2), 'utf-8');
console.log('Written Ch19');