const fs = require('fs');
const path = require('path');

const ch22 = {
  chapterNumber: 22,
  title: "Idioms and Common Expressions",
  overview: "Idioms and common expressions are phrases whose meanings cannot be understood from the literal definitions of the individual words. They appear frequently in sentence correction, sentence completion, and reading comprehension questions.",
  corePoints: ["Idiom = phrase with non-literal meaning","Prepositional idioms: correct prepositions are tested","Phrasal verbs: verb + particle","Fixed expressions: as...as, not only...but also","Context determines the correct idiom","Common mistakes: using wrong preposition or particle","Reading exposes you to natural idiom usage"],
  examTips: "Idiom questions typically appear in the language usage section. The test frequently focuses on prepositional idioms and correlative conjunctions.",
  youtubeVideoId: "placeholder",
  videoDuration: "11:30",
  materials: [
    {name:"Prepositional Idiom: Capable of",formula:"",description:"Correct: 'capable of doing' (not 'capable to do')."},
    {name:"Prepositional Idiom: Different from",formula:"",description:"Correct: 'different from' (not 'different than' in formal English)."},
    {name:"Correlative Conjunction: Not only...but also",formula:"",description:"Used to connect two parallel items."},
    {name:"Idiom: As...as",formula:"",description:"Used for comparisons. Example: as tall as."},
    {name:"Phrasal Verb: Give up",formula:"",description:"To stop trying or surrender."},
    {name:"Phrasal Verb: Look after",formula:"",description:"To take care of."},
    {name:"Prepositional Idiom: Interested in",formula:"",description:"Correct: 'interested in' (not 'interested on')."},
    {name:"Idiom: The exception proves the rule",formula:"",description:"An exception confirms the rule."}
  ],
  subtopics: [
    {title:"22.1 What is an Idiom?",content:"<p>An idiom is a phrase whose meaning cannot be understood from the literal meanings of its individual words.</p><div class='formula-box'><strong>Idiom Definition</strong><br/>Non-literal meaning<br/>Fixed in form<br/>Often culturally specific<br/>Example: raining cats and dogs = raining heavily</div>",examInsight:"Idiom questions often test preposition usage or fixed expressions.",practiceProblems:[{question:"Which is an idiom?",options:["The sky is blue","She likes cake","I'll hit the hay","He went to school"],answer:"C",solution:"<p>'Hit the hay' means 'go to sleep'.</p>"},{question:"What does 'kick the bucket' mean?",options:["To kick a bucket","To die","To dance","To go to sleep"],answer:"B",solution:"<p>'Kick the bucket' is an idiom meaning 'to die'.</p>"},{question:"What does 'let the cat out of the bag' mean?",options:["To release a cat","To reveal a secret","To lose something","To make a mistake"],answer:"B",solution:"<p>'Let the cat out of the bag' means to reveal a secret.</p>"}]},
    {title:"22.2 Common Prepositional Idioms",content:"<p>Prepositional idioms require specific prepositions after certain words.</p><div class='formula-box'><strong>Essential Prepositional Idioms</strong><br/>capable of<br/>different from<br/>interested in<br/>apologize for<br/>concerned about<br/>responsible for<br/>similar to</div>",examInsight:"This is one of the most common error types.",practiceProblems:[{question:"Identify the error: 'She is capable (A) to complete (B) the project (C) on time. (D) No error.'",options:["A","B","C","D"],answer:"A",solution:"<p>Correct idiom is 'capable of'.</p>"},{question:"Identify the error: 'His opinion (A) is different (B) than (C) mine. (D) No error.'",options:["A","B","C","D"],answer:"C",solution:"<p>Correct idiom is 'different from'.</p>"},{question:"Which sentence is correct?",options:["I am interested in learning.","I am interested on learning.","I am interested of learning.","I am interested with learning."],answer:"A",solution:"<p>'Interested in' is the correct idiom.</p>"}]},
    {title:"22.3 Phrasal Verbs",content:"<p>Phrasal verbs are verbs combined with prepositions or particles to create a new meaning.</p><div class='formula-box'><strong>Common Phrasal Verbs</strong><br/>give up (stop trying)<br/>look after (take care of)<br/>put up with (tolerate)<br/>break down (stop working)<br/>bring up (mention)<br/>come across (find by chance)</div>",examInsight:"The correct meaning depends on the particle.",practiceProblems:[{question:"'He gave up smoking' means:",options:["Started smoking","Stopped smoking","Tried smoking","Forgot about smoking"],answer:"B",solution:"<p>'Give up' means to stop doing something.</p>"},{question:"Which phrasal verb means 'to take care of'?",options:["look after","look for","look into","look up"],answer:"A",solution:"<p>'Look after' means to take care of.</p>"},{question:"'The car broke down' means:",options:["Drove fast","Stopped working","Started working","Went fast"],answer:"B",solution:"<p>'Break down' means to stop working.</p>"}]},
    {title:"22.4 Correlative Conjunctions",content:"<p>Correlative conjunctions are pairs that connect parallel elements: either...or, neither...nor, both...and, not only...but also.</p><div class='formula-box'><strong>Correlative Conjunction Rules</strong><br/>either...or (choice between two)<br/>neither...nor (rejects both)<br/>both...and (includes both)<br/>not only...but also (adds emphasis)</div>",examInsight:"The error is often a parallelism violation.",practiceProblems:[{question:"Identify the error: 'He is (A) not only smart (B) but also (C) he is kind. (D) No error.'",options:["A","B","C","D"],answer:"C",solution:"<p>'He is kind' breaks parallelism. Should be just 'kind'.</p>"},{question:"Which sentence is correct?",options:["Neither he nor I are going.","Neither he nor I am going.","Neither he nor I is going.","Neither he nor I are going."],answer:"B",solution:"<p>Singular verb agreeing with nearest subject: 'am'.</p>"},{question:"Identify the error: 'She can (A) either (B) walk or (C) to run. (D) No error.'",options:["A","B","C","D"],answer:"C",solution:"<p>'To run' breaks parallelism with 'walk'.</p>"}]},
    {title:"22.5 Common Idiomatic Expressions",content:"<p>Some idioms are full phrases with fixed wording. They often appear in reading comprehension.</p><div class='formula-box'><strong>Common Idiomatic Phrases</strong><br/>in a nutshell (in summary)<br/>once in a blue moon (very rarely)<br/>piece of cake (very easy)<br/>bite the bullet (face difficulty)<br/>hit the sack (go to bed)</div>",examInsight:"Understanding them helps with tone and meaning.",practiceProblems:[{question:"What does 'in a nutshell' mean?",options:["In a container","In summary","In a hurry","In a difficult situation"],answer:"B",solution:"<p>'In a nutshell' means in summary.</p>"},{question:"If something happens 'once in a blue moon', it happens:",options:["Frequently","Rarely","Never","Always"],answer:"B",solution:"<p>'Once in a blue moon' means very rarely.</p>"},{question:"'The test was a piece of cake' means:",options:["Difficult","Easy","Tasty","Long"],answer:"B",solution:"<p>'Piece of cake' means very easy.</p>"}]},
    {title:"22.6 Idioms in Context",content:"<p>Understanding idioms in context is essential for reading comprehension. Authors often use idioms to convey tone or attitude.</p><div class='formula-box'><strong>Context Strategy</strong><br/>1. Identify the idiom<br/>2. Consider literal meaning<br/>3. Use context to infer figurative meaning<br/>4. Test with substitution</div>",examInsight:"Reading comprehension passages may contain idioms.",practiceProblems:[{question:"'The project was a piece of cake for the experienced team, but the newcomers struggled.' What does 'piece of cake' mean?",options:["Easy","Difficult","Delicious","Boring"],answer:"A",solution:"<p>Contrast with 'struggled' suggests the experienced team found it easy.</p>"},{question:"'The CEO decided to bite the bullet and announce the layoffs.' What does 'bite the bullet' mean?",options:["Avoid a difficult decision","Face a difficult situation bravely","Eat something quickly","Make a mistake"],answer:"B",solution:"<p>'Bite the bullet' means to face a difficult situation.</p>"},{question:"'The audience saw right through the politician's empty promises.' What does 'saw right through' mean?",options:["Looked past","Understood the truth","Ignored","Agreed with"],answer:"B",solution:"<p>'Saw right through' means to perceive the true nature.</p>"}]},
    {title:"22.7 Avoiding Common Idiom Errors",content:"<p>Many idiom errors occur because the wrong preposition or word is used.</p><div class='formula-box'><strong>Common Errors to Avoid</strong><br/>capable to = capable of<br/>different than = different from<br/>interested on = interested in<br/>superior than = superior to<br/>comprised of = composed of</div>",examInsight:"These are the most frequently tested idiom errors.",practiceProblems:[{question:"Identify the error: 'This product is (A) superior (B) than (C) the competition. (D) No error.'",options:["A","B","C","D"],answer:"C",solution:"<p>Correct idiom is 'superior to'.</p>"},{question:"Which sentence is correct?",options:["The committee is comprised of experts.","The committee comprises of experts.","The committee is composed of experts.","The committee is comprised of experts."],answer:"C",solution:"<p>'Comprised of' is incorrect. 'Composed of' is preferred.</p>"},{question:"Identify the error: 'She is (A) interested (B) of (C) learning Spanish. (D) No error.'",options:["A","B","C","D"],answer:"C",solution:"<p>Correct idiom is 'interested in'.</p>"}]},
    {title:"22.8 Quantitative Comparison with Idioms",content:"<p>Some questions may ask you to compare the appropriateness or formality of two idiomatic expressions.</p><div class='formula-box'><strong>Comparing Idioms</strong><br/>Consider formality (formal vs. informal)<br/>Consider intensity (strong vs. mild)<br/>Consider appropriateness (context)</div>",examInsight:"Less common but appears occasionally.",practiceProblems:[{question:"Quantity A: Formality of 'pass away'. Quantity B: Formality of 'kick the bucket'.",options:["A is more formal","B is more formal","Equal","Cannot determine"],answer:"A",solution:"<p>'Pass away' is more formal. 'Kick the bucket' is slang.</p>"},{question:"Which expression is more appropriate in a formal letter?",options:["Kick the bucket","Pass away","Die","Give up the ghost"],answer:"B",solution:"<p>'Pass away' is a respectful euphemism.</p>"},{question:"Quantity A: Intensity of 'furious'. Quantity B: Intensity of 'annoyed'.",options:["A is greater","B is greater","Equal","Cannot determine"],answer:"A",solution:"<p>'Furious' is much more intense than 'annoyed'.</p>"}]}
  ]
};

fs.writeFileSync(path.resolve(__dirname, '..', '_chapter-data.json'), JSON.stringify(ch22, null, 2), 'utf-8');
console.log('Written Ch22');