const fs = require('fs');
const path = require('path');

const ch20 = {
  chapterNumber: 20,
  title: "Critical Reasoning",
  overview: "Critical reasoning questions test your ability to analyze arguments, identify assumptions, evaluate evidence, and draw logical conclusions. These questions test logical thinking and reasoning skills.",
  corePoints: ["Argument components: premise, conclusion, and assumption","Assumptions are unstated premises that support the conclusion","Strengthening: adding evidence that supports the argument","Weakening: adding evidence that undermines the argument","Inference: drawing a logical conclusion from given information","Evaluate: assessing the quality or validity of an argument","Identify flaws: recognizing logical errors or oversights"],
  examTips: "Critical reasoning questions are typically found in the reading comprehension section. The key is to read the argument carefully and identify the conclusion before looking at the choices.",
  youtubeVideoId: "placeholder",
  videoDuration: "14:50",
  materials: [
    {name:"Premise",formula:"",description:"A statement or evidence that supports the conclusion."},
    {name:"Conclusion",formula:"",description:"The main point or claim the argument tries to prove."},
    {name:"Assumption",formula:"",description:"An unstated premise that must be true for the conclusion to follow."},
    {name:"Strengthen",formula:"",description:"Adding evidence that makes the argument more convincing."},
    {name:"Weaken",formula:"",description:"Adding evidence that makes the argument less convincing."},
    {name:"Inference",formula:"",description:"A logical conclusion drawn from given information."},
    {name:"Flaw",formula:"",description:"A logical error in the argument."}
  ],
  subtopics: [
    {title:"20.1 Identifying Argument Components",content:"<p>Every argument has a conclusion and at least one premise. The conclusion is the main claim. Premises are the evidence supporting it.</p><div class='formula-box'><strong>Argument Components</strong><br/>Conclusion: The claim the author wants you to accept<br/>Premises: Evidence that supports the conclusion<br/>Signal words: therefore, thus, because, since</div>",examInsight:"Frequently tested: identify the conclusion of an argument.",practiceProblems:[{question:"'All birds have feathers. A penguin is a bird. Therefore, a penguin has feathers.' What is the conclusion?",options:["All birds have feathers","A penguin is a bird","A penguin has feathers","Birds are animals"],answer:"C",solution:"<p>'Therefore' introduces the conclusion.</p>"},{question:"'Since the defendant had no alibi, the jury concluded he was guilty.' What is the premise?",options:["The defendant was guilty","The jury concluded he was guilty","The defendant had no alibi","The defendant was innocent"],answer:"C",solution:"<p>'Since' introduces the premise.</p>"},{question:"'Because the economy is strong, the stock market will continue to rise.' What is the conclusion?",options:["The economy is strong","Unemployment is low","The stock market will continue to rise","The economy is strong and unemployment is low"],answer:"C",solution:"<p>The conclusion follows the 'because' clause.</p>"}]},
    {title:"20.2 Identifying Assumptions",content:"<p>An assumption is an unstated premise that must be true for the argument to be valid. Ask: What must the author believe for the conclusion to follow?</p><div class='formula-box'><strong>Assumption Strategy</strong><br/>Identify gap between premises and conclusion<br/>Ask: What must be true for conclusion to follow?<br/>The assumption fills the logical gap</div>",examInsight:"If the assumption is false, the argument falls apart.",practiceProblems:[{question:"'All dogs are friendly. Max is a dog. Therefore, Max is friendly.' What is the assumption?",options:["Max is a cat","Max is friendly","All friendly animals are dogs","The premise is true"],answer:"D",solution:"<p>The argument assumes the premise is true.</p>"},{question:"'Students who study hard get good grades. John got good grades. Therefore, John studied hard.' What is the assumption?",options:["Good grades guarantee studying","John is a student","John studied","Only students can get good grades"],answer:"A",solution:"<p>The argument assumes good grades indicate studying.</p>"},{question:"'The weather forecast predicts rain. Therefore, it will rain.' What is the assumption?",options:["Forecasts are always correct","The forecast is reliable","Rain is common","The forecast is for a specific area"],answer:"B",solution:"<p>The argument assumes the forecast is accurate enough.</p>"}]},
    {title:"20.3 Strengthening Arguments",content:"<p>Strengthening questions ask you to add evidence that makes the argument more convincing.</p><div class='formula-box'><strong>Strengthening Strategy</strong><br/>Identify conclusion and premises<br/>Look for choices that support conclusion<br/>Eliminate choices that weaken or are irrelevant</div>",examInsight:"The correct answer often provides new evidence or eliminates a counterargument.",practiceProblems:[{question:"'Exercise is important. Schools should require PE.' What strengthens this argument?",options:["Many students dislike PE","PE improves health","Schools have limited budgets","Students already get enough exercise"],answer:"B",solution:"<p>PE improving health supports the conclusion.</p>"},{question:"'The drug reduces blood pressure. It should be approved.' What strengthens?",options:["The drug has side effects","Other drugs are more effective","The drug has been tested in multiple studies","The drug is expensive"],answer:"C",solution:"<p>Multiple studies support efficacy and safety.</p>"},{question:"'Profits increased every quarter. The company is well-managed.' What strengthens?",options:["The CEO has experience","The company has no competitors","Profits are due to efficient management","The industry is growing"],answer:"C",solution:"<p>Profits due to management directly supports the conclusion.</p>"}]},
    {title:"20.4 Weakening Arguments",content:"<p>Weakening questions ask you to add evidence that undermines the argument.</p><div class='formula-box'><strong>Weakening Strategy</strong><br/>Identify conclusion and premises<br/>Look for choices that cast doubt<br/>Eliminate choices that strengthen or are irrelevant</div>",examInsight:"The correct answer often provides a counterexample or alternative explanation.",practiceProblems:[{question:"'Exercise is important. Schools should require PE.' What weakens this argument?",options:["Many students enjoy PE","PE improves health","Schools have limited budgets","Students already get enough exercise"],answer:"D",solution:"<p>If students already get enough exercise, the need for required PE is reduced.</p>"},{question:"'The drug reduces blood pressure. It should be approved.' What weakens?",options:["The drug has serious side effects","Other drugs are more effective","Multiple studies tested it","The drug is expensive"],answer:"A",solution:"<p>Serious side effects undermine the case for approval.</p>"},{question:"'Profits increased every quarter. The company is well-managed.' What weakens?",options:["The CEO has experience","The company has no competitors","The industry is growing rapidly","The company has a new product"],answer:"C",solution:"<p>Industry growth provides an alternative explanation for profits.</p>"}]},
    {title:"20.5 Drawing Inferences",content:"<p>Inference questions ask you to draw a logical conclusion not explicitly stated. The answer must follow logically from the given information.</p><div class='formula-box'><strong>Inference Strategy</strong><br/>Identify key information<br/>Consider what logically follows<br/>Avoid choices too broad or extreme<br/>Choose most conservative conclusion</div>",examInsight:"The correct answer is usually a moderate, well-supported conclusion.",practiceProblems:[{question:"'Some students are unhappy about the uniform policy.' What can be inferred?",options:["All students are unhappy","Some support the decision","At least one student is unhappy","The decision will be reversed"],answer:"C",solution:"<p>'Some' implies at least one student is unhappy.</p>"},{question:"'If it rains, the ground gets wet. The ground is wet.' What can be inferred?",options:["It rained","It did not rain","It might have rained","The ground is dry"],answer:"C",solution:"<p>The ground could be wet for other reasons.</p>"},{question:"'The company has been losing money for three years. The CEO resigned.' What can be inferred?",options:["The CEO was fired","The CEO quit because of losses","The CEO might have left due to losses","The company is closing"],answer:"C",solution:"<p>We can only infer a possible connection.</p>"}]},
    {title:"20.6 Evaluating Arguments and Identifying Flaws",content:"<p>Flaws are logical errors that undermine the argument. Common flaws: circular reasoning, hasty generalization, false dichotomy, ad hominem.</p><div class='formula-box'><strong>Common Logical Flaws</strong><br/>Circular reasoning: conclusion assumed in premise<br/>Hasty generalization: insufficient evidence<br/>False dichotomy: only two options presented<br/>Ad hominem: attacks the person, not argument</div>",examInsight:"Flaw questions require identifying the weakness in the argument's logic.",practiceProblems:[{question:"'The mayor should not be re-elected because he has been criticized by the media.' What is the flaw?",options:["Circular reasoning","Ad hominem","Hasty generalization","False dichotomy"],answer:"B",solution:"<p>Attacks the mayor based on criticism, not policy. This is ad hominem.</p>"},{question:"'I met two students from that school, and they were both rude. All students from that school are rude.' Flaw?",options:["Circular reasoning","Ad hominem","Hasty generalization","False dichotomy"],answer:"C",solution:"<p>Conclusion based on only two examples. This is hasty generalization.</p>"},{question:"'You are either with us or against us.' Flaw?",options:["Circular reasoning","Ad hominem","Hasty generalization","False dichotomy"],answer:"D",solution:"<p>Presents only two options, ignoring others. This is false dichotomy.</p>"}]},
    {title:"20.7 Application in Reading Comprehension",content:"<p>Critical reasoning skills are directly applicable to reading comprehension. Analyze the author's argument structure, identify assumptions, and evaluate evidence.</p><div class='formula-box'><strong>Reading Connection</strong><br/>Analyze author's argument structure<br/>Identify assumptions and weaknesses<br/>Evaluate strength of evidence</div>",examInsight:"Critical reasoning is woven into reading comprehension questions.",practiceProblems:[{question:"'The new policy is a failure. Employee morale decreased, productivity fell.' What is the conclusion?",options:["The policy is a failure","Morale decreased","Productivity fell","The policy was implemented"],answer:"A",solution:"<p>The main claim is that the policy is a failure.</p>"},{question:"'These changes might be due to the economic downturn.' What weakens the argument?",options:["Morale decreased","Productivity fell","Economic downturn could explain changes","The policy was implemented"],answer:"C",solution:"<p>Alternative explanation weakens the argument.</p>"},{question:"'The study had only 10 participants.' What flaw is identified?",options:["The diet is effective","Participants lost weight","Sample size is too small","The study was one month long"],answer:"C",solution:"<p>Small sample is a hasty generalization.</p>"}]},
    {title:"20.8 Quantitative Comparison with Critical Reasoning",content:"<p>Some questions may involve comparing the strength of two arguments or the validity of two conclusions.</p><div class='formula-box'><strong>Logical Comparison</strong><br/>Compare strength of two arguments<br/>Evaluate which conclusion is better supported<br/>Consider assumptions and evidence</div>",examInsight:"Requires careful logical analysis.",practiceProblems:[{question:"Argument A: All cats have fur. Fluffy is a cat. Fluffy has fur. Argument B: All cats are mammals. Fluffy is a cat. Fluffy is a mammal. Which is stronger?",options:["A is stronger","B is stronger","Equal","Cannot determine"],answer:"C",solution:"<p>Both are valid deductive arguments with true premises.</p>"},{question:"Argument A: The product is great because it has features. Argument B: The product is great because 90% of users recommend it. Which is stronger?",options:["A","B","Equal","Cannot determine"],answer:"B",solution:"<p>User recommendations are more objective than a subjective claim about features.</p>"}]}
  ]
};

fs.writeFileSync(path.resolve(__dirname, '..', '_chapter-data.json'), JSON.stringify(ch20, null, 2), 'utf-8');
console.log('Written Ch20');