const fs = require('fs');
const path = require('path');

const ch21 = {
  chapterNumber: 21,
  title: "Vocabulary Building",
  overview: "Building a strong vocabulary is essential for success on the UEE/SAT verbal section. This chapter covers the most common roots, prefixes, and suffixes that form the foundation of English words.",
  corePoints: ["Roots: the core meaning of a word","Prefixes: added to beginning to modify meaning","Suffixes: added to end to indicate part of speech","Word families: groups of words sharing a common root","Context clues help infer meaning of unfamiliar words","Spaced repetition is the most effective retention strategy","Reading widely is the best way to build vocabulary","Word parts can decode up to 60% of unfamiliar words"],
  examTips: "Vocabulary is tested indirectly through sentence completion, analogies, reading comprehension, and antonym questions. Memorizing roots, prefixes, and suffixes is more efficient than memorizing isolated words.",
  youtubeVideoId: "placeholder",
  videoDuration: "12:45",
  materials: [
    {name:"Root: BENE (good, well)",formula:"",description:"Words: BENEFICIAL, BENEVOLENT, BENIGN."},
    {name:"Root: MAL (bad, evil)",formula:"",description:"Words: MALEVOLENT, MALICIOUS, MALADY."},
    {name:"Root: DICT (say, speak)",formula:"",description:"Words: PREDICT, DICTATE, VERDICT."},
    {name:"Root: SCRIB/SCRIPT (write)",formula:"",description:"Words: DESCRIBE, SCRIPT, TRANSCRIBE."},
    {name:"Prefix: UN- (not)",formula:"",description:"Words: UNHAPPY, UNKIND, UNUSUAL."},
    {name:"Suffix: -TION (noun)",formula:"",description:"Words: ACTION, EDUCATION, REVOLUTION."},
    {name:"Root: AUD (hear)",formula:"",description:"Words: AUDIENCE, AUDIBLE, AUDITORIUM."},
    {name:"Root: SPEC (see, look)",formula:"",description:"Words: INSPECT, SPECTACLE, PERSPECTIVE."}
  ],
  subtopics: [
    {title:"21.1 Common Root Words",content:"<p>A root is the core of a word, carrying its primary meaning. Most English roots come from Latin or Greek.</p><div class='formula-box'><strong>Essential Roots</strong><br/>BENE (good): benefit, benevolent, benign<br/>MAL (bad): malady, malevolent, malicious<br/>DICT (say): predict, dictate, verdict<br/>SCRIB (write): describe, scribble, transcribe<br/>AUD (hear): audience, audible, auditorium<br/>SPEC (see): inspect, spectacle, perspective</div>",examInsight:"Frequently appears in vocabulary-in-context and analogy questions.",practiceProblems:[{question:"'Beneficial' means:",options:["harmful","helpful","neutral","unimportant"],answer:"B",solution:"<p>'Bene' means good. Beneficial means producing good effects.</p>"},{question:"Which word contains the root 'mal'?",options:["benign","malevolent","benevolent","benefactor"],answer:"B",solution:"<p>'Mal' means bad. Malevolent means wishing harm.</p>"},{question:"Which word contains the root 'dict'?",options:["script","describe","predict","inspect"],answer:"C",solution:"<p>'Dict' means to say. Predict means to say beforehand.</p>"}]},
    {title:"21.2 Common Prefixes",content:"<p>Prefixes are added to the beginning of a word to modify its meaning.</p><div class='formula-box'><strong>Essential Prefixes</strong><br/>UN- (not): unhappy, unkind<br/>IN-/IM- (not): inactive, impossible<br/>DIS- (opposite): disagree, disconnect<br/>PRE- (before): preview, predict<br/>POST- (after): postpone, postscript<br/>SUB- (under): submarine, substandard</div>",examInsight:"Frequently tested in antonym questions and sentence completions.",practiceProblems:[{question:"'Inactive' means:",options:["active","not active","very active","active again"],answer:"B",solution:"<p>'In-' means not. Inactive means not active.</p>"},{question:"Which word has the prefix 'pre'?",options:["postpone","predict","submarine","disagree"],answer:"B",solution:"<p>'Pre-' means before. Predict means to say beforehand.</p>"},{question:"The prefix 'dis-' changes meaning to:",options:["same","opposite","more","less"],answer:"B",solution:"<p>'Dis-' indicates opposition or reversal.</p>"}]},
    {title:"21.3 Common Suffixes",content:"<p>Suffixes are added to the end of a word to change its part of speech.</p><div class='formula-box'><strong>Essential Suffixes</strong><br/>-TION (noun): action, education<br/>-MENT (noun): payment, agreement<br/>-FUL (adjective): joyful, helpful<br/>-LESS (adjective): careless, hopeless<br/>-LY (adverb): quickly, happily<br/>-IZE (verb): realize, organize</div>",examInsight:"Identifying suffixes helps determine the correct part of speech.",practiceProblems:[{question:"'Development' is what part of speech?",options:["Noun","Verb","Adjective","Adverb"],answer:"A",solution:"<p>'-ment' is a noun suffix.</p>"},{question:"Which suffix turns 'quick' into an adverb?",options:["-ness","-ly","-ful","-tion"],answer:"B",solution:"<p>'-ly' is the most common adverb suffix.</p>"},{question:"'Harmless' means:",options:["full of harm","without harm","causing harm","harmful"],answer:"B",solution:"<p>'-less' means without. Harmless means without harm.</p>"}]},
    {title:"21.4 Using Word Parts to Decode Unfamiliar Words",content:"<p>When you encounter an unfamiliar word, break it down into prefix, root, and suffix to infer meaning.</p><div class='formula-box'><strong>Decoding Strategy</strong><br/>1. Identify the prefix<br/>2. Identify the root<br/>3. Identify the suffix<br/>4. Combine the meanings<br/>5. Test in context</div>",examInsight:"This strategy can decode up to 60% of unfamiliar words.",practiceProblems:[{question:"'Substandard' most likely means:",options:["above standard","below standard","equal to standard","standard"],answer:"B",solution:"<p>'Sub-' means below. Substandard means below standard.</p>"},{question:"'Malformed' most likely means:",options:["well-formed","badly formed","beautifully formed","not formed"],answer:"B",solution:"<p>'Mal-' means bad. Malformed means badly formed.</p>"},{question:"'Beneficent' most likely means:",options:["doing good","doing harm","neutral","uncaring"],answer:"A",solution:"<p>'Bene-' means good. Beneficent means doing good.</p>"}]},
    {title:"21.5 Word Families",content:"<p>Word families are groups of words sharing a common root. Learning one root unlocks an entire family.</p><div class='formula-box'><strong>Word Family Example</strong><br/>ROOT: SCRIB (write)<br/>Describe (write about)<br/>Scribble (write carelessly)<br/>Script (written text)<br/>Transcribe (write down)</div>",examInsight:"Word families appear in analogies and sentence completions.",practiceProblems:[{question:"Which word is NOT in the same family as 'script'?",options:["describe","scribble","transcribe","inspect"],answer:"D",solution:"<p>'Inspect' comes from 'spec' (see), not 'scrib' (write).</p>"},{question:"Which word is in the same family as 'audible'?",options:["audience","script","spectacle","predict"],answer:"A",solution:"<p>'Audible' and 'audience' both relate to hearing.</p>"},{question:"Which belongs to the 'spec' family?",options:["spectacle","describe","predict","transcribe"],answer:"A",solution:"<p>'Spec' means to see. Spectacle is something seen.</p>"}]},
    {title:"21.6 Building Vocabulary through Reading",content:"<p>Reading widely is the most effective way to build vocabulary naturally. Exposure to words in context helps understand meanings, connotations, and usage.</p><div class='formula-box'><strong>Reading Strategy</strong><br/>1. Read diverse materials<br/>2. Note unfamiliar words<br/>3. Look up definitions<br/>4. Write example sentences<br/>5. Review words regularly</div>",examInsight:"Reading comprehension passages cover a range of topics. Regular reading builds vocabulary.",practiceProblems:[{question:"Which activity is most effective for vocabulary building?",options:["Memorizing word lists","Reading widely","Using flashcards","Taking practice tests"],answer:"B",solution:"<p>Reading exposes you to words in context.</p>"},{question:"When reading, a good strategy for vocabulary is:",options:["Skip unknown words","Look up every word immediately","Try to infer meaning from context","Ignore the passage"],answer:"C",solution:"<p>Inferring from context builds comprehension skills.</p>"},{question:"A vocabulary journal is useful because:",options:["It helps you remember words","It takes little time","It is not necessary","It replaces reading"],answer:"A",solution:"<p>Writing and reviewing words aids retention.</p>"}]},
    {title:"21.7 Advanced Vocabulary Roots and Prefixes",content:"<p>For higher-level vocabulary, learn additional roots and prefixes.</p><div class='formula-box'><strong>Advanced Roots</strong><br/>AMBI (both): ambiguous, ambidextrous<br/>CHRON (time): chronological, chronic<br/>COSM (order, world): cosmic, cosmopolitan<br/>CRED (believe): credible, credulous<br/>FID (faith): confident, fidelity<br/>PHIL (love): philosophy, philanthropy</div>",examInsight:"These roots appear in the most difficult vocabulary questions.",practiceProblems:[{question:"'Chronological' means:",options:["alphabetical","in time order","random","reverse order"],answer:"B",solution:"<p>'Chron' means time. Chronological means in time order.</p>"},{question:"Which word has the root 'cred'?",options:["incredible","chronology","philanthropy","ambidextrous"],answer:"A",solution:"<p>'Cred' means believe. Incredible means unbelievable.</p>"},{question:"'Philanthropy' relates to:",options:["love of humanity","fear of people","hatred of others","indifference"],answer:"A",solution:"<p>'Phil' means love. Anthropy relates to humanity.</p>"}]},
    {title:"21.8 Quantitative Comparison with Vocabulary",content:"<p>Some questions may ask you to compare the strength or frequency of word usage.</p><div class='formula-box'><strong>Word Comparison</strong><br/>Compare intensity (degree)<br/>Compare formality (register)<br/>Compare connotation (positive/negative)</div>",examInsight:"Requires understanding of word nuance.",practiceProblems:[{question:"Quantity A: Intensity of 'enraged'. Quantity B: Intensity of 'annoyed'.",options:["A is greater","B is greater","Equal","Cannot determine"],answer:"A",solution:"<p>'Enraged' is much more intense than 'annoyed'.</p>"},{question:"Quantity A: Formality of 'utilize'. Quantity B: Formality of 'use'.",options:["A is more formal","B is more formal","Equal","Cannot determine"],answer:"A",solution:"<p>'Utilize' is more formal than 'use'.</p>"},{question:"Which word has the most positive connotation?",options:["Thrifty","Stingy","Cheap","Frugal"],answer:"A",solution:"<p>'Thrifty' suggests careful spending in a positive way.</p>"}]}
  ]
};

fs.writeFileSync(path.resolve(__dirname, '..', '_chapter-data.json'), JSON.stringify(ch21, null, 2), 'utf-8');
console.log('Written Ch21');