const fs = require('fs');
const path = require('path');

const ch18 = {
  chapterNumber: 18,
  title: "Language Usage and Sentence Correction",
  overview: "Language usage questions test your knowledge of standard written English grammar, usage, diction, and idioms. Sentence correction questions require you to choose the best version of an underlined section.",
  corePoints: ["Subject-verb agreement: singular subjects take singular verbs","Pronoun agreement: pronouns must agree with their antecedents","Verb tense: maintain consistent and logical tense","Adjectives modify nouns; adverbs modify verbs and adjectives","Parallel structure: items in a list must be in the same form","Dangling modifiers: phrases must have a clear subject to modify","Diction errors: choosing the wrong word","Idiom errors: incorrect preposition or expression"],
  examTips: "Language usage and sentence correction questions typically appear as the last set in the verbal section, often 3-5 items.",
  youtubeVideoId: "placeholder",
  videoDuration: "15:30",
  materials: [
    {name:"Subject-Verb Agreement",formula:"Singular subject = singular verb",description:"The verb must agree in number with its subject."},
    {name:"Pronoun Agreement",formula:"Pronoun must agree with antecedent",description:"A pronoun must refer clearly to its antecedent."},
    {name:"Pronoun Case",formula:"Subjective vs. Objective",description:"Use subjective for subjects, objective for objects."},
    {name:"Verb Tense Consistency",formula:"Maintain logical tense sequence",description:"Shift tense only when meaning requires it."},
    {name:"Adjective vs. Adverb",formula:"Adjective modifies noun; Adverb modifies verb",description:"Use well (adverb) for actions; good (adjective) for nouns."},
    {name:"Parallel Structure",formula:"Items in a series must have same grammatical form",description:"When listing items, use the same part of speech."},
    {name:"Dangling Modifier",formula:"Modifier must have clear subject",description:"Subject of modifier must match subject of main clause."},
    {name:"Diction: Affect/Effect",formula:"Affect (verb) = to influence; Effect (noun) = result",description:"Affect is almost always a verb. Effect is usually a noun."}
  ],
  subtopics: [
    {title:"18.1 Subject-Verb Agreement",content:"<p>The subject and verb must agree in number. Watch for intervening phrases that may distract you.</p><div class='formula-box'><strong>Subject-Verb Agreement Rules</strong><br/>Singular subject = singular verb<br/>Plural subject = plural verb<br/>Intervening phrases don't change agreement<br/>Indefinite pronouns are singular</div>",examInsight:"Subject-verb agreement is the most common error type.",practiceProblems:[{question:"Identify the error: 'The team of players (A) are (B) preparing for the championship (C) game. (D) No error.'",options:["A","B","C","D"],answer:"B",solution:"<p>Subject is 'team' (singular). Verb should be 'is' (singular).</p>"},{question:"Identify the error: 'Everyone (A) in the classes (B) have (C) submitted their assignments. (D) No error.'",options:["A","B","C","D"],answer:"C",solution:"<p>'Everyone' is singular. Verb should be 'has' (singular).</p>"},{question:"Which sentence is correct?",options:["The number of students are increasing.","The number of students is increasing.","A number of students is increasing.","A number of students are increasing."],answer:"B",solution:"<p>'The number of' takes a singular verb.</p>"}]},
    {title:"18.2 Pronoun Agreement and Case",content:"<p>Pronouns must agree with their antecedents in number, gender, and person. Use subjective case for subjects, objective for objects.</p><div class='formula-box'><strong>Pronoun Rules</strong><br/>Agreement: Each student must bring his or her book<br/>Case: Between you and me (objective)<br/>Ambiguous reference is an error</div>",examInsight:"Pronoun questions are common. Words like 'each', 'every' require singular pronouns.",practiceProblems:[{question:"Identify the error: 'Between you and I (A), this situation (B) is (C) difficult. (D) No error.'",options:["A","B","C","D"],answer:"A",solution:"<p>Should be 'Between you and me' (objective case).</p>"},{question:"Identify the error: 'Each of the students (A) must bring (B) their (C) own book. (D) No error.'",options:["A","B","C","D"],answer:"C",solution:"<p>'Each' is singular. Pronoun should be 'his or her'.</p>"},{question:"Which sentence has a pronoun error?",options:["She gave the book to him.","He and I went to the store.","Me and him went to the store.","They helped us."],answer:"C",solution:"<p>'Me and him' uses objective case for subjects. Should be 'He and I'.</p>"}]},
    {title:"18.3 Verb Tense Consistency",content:"<p>Verb tenses must be consistent and logical. Do not shift tenses unnecessarily.</p><div class='formula-box'><strong>Verb Tense Rules</strong><br/>Maintain consistent tense<br/>Shift tense only for meaning<br/>Use past perfect for earlier past actions</div>",examInsight:"Watch for sudden tense shifts in the same sentence.",practiceProblems:[{question:"Identify the error: 'She walked into the room and (A) sits (B) down (C) to rest. (D) No error.'",options:["A","B","C","D"],answer:"B",solution:"<p>'Walked' is past tense. Should be 'sat' (past).</p>"},{question:"Identify the error: 'He said he (A) will (B) come (C) to the party. (D) No error.'",options:["A","B","C","D"],answer:"B",solution:"<p>'Said' is past tense. Reported speech should shift to 'would come'.</p>"},{question:"Which sentence is correct?",options:["I have seen that movie yesterday.","I saw that movie yesterday.","I have seen that movie yesterday.","I had seen that movie yesterday."],answer:"B",solution:"<p>'Yesterday' indicates specific past time. Use simple past: 'saw'.</p>"}]},
    {title:"18.4 Adjective vs. Adverb",content:"<p>Adjectives modify nouns or pronouns. Adverbs modify verbs, adjectives, or other adverbs.</p><div class='formula-box'><strong>Adjective/Adverb Rules</strong><br/>Adjective modifies noun: The quick fox<br/>Adverb modifies verb: The fox ran quickly<br/>Linking verbs take adjectives: She feels good</div>",examInsight:"Common test: choose between 'well' and 'good'.",practiceProblems:[{question:"Identify the error: 'She did (A) real (B) good (C) on the test. (D) No error.'",options:["A","B","C","D"],answer:"B",solution:"<p>'Good' should be 'well' (adverb). Also 'real' should be 'really'.</p>"},{question:"Which sentence is correct?",options:["She feels well.","She feels good.","She feels badly.","She feels well."],answer:"A",solution:"<p>Linking verbs take adjectives: 'She feels good.' or 'well' for health.</p>"},{question:"Identify the error: 'He spoke (A) very (B) clear (C) and confidently. (D) No error.'",options:["A","B","C","D"],answer:"C",solution:"<p>'Clear' should be 'clearly' (adverb) to modify 'spoke'.</p>"}]},
    {title:"18.5 Parallel Structure",content:"<p>When listing items, they must be in the same grammatical form.</p><div class='formula-box'><strong>Parallel Structure Rules</strong><br/>Series: I like swimming, running, and biking<br/>Correlative: Either you go or I go<br/>Not only...but also requires parallel elements</div>",examInsight:"Parallelism is a frequent error type. Look for lists and correlative conjunctions.",practiceProblems:[{question:"Identify the error: 'She enjoys (A) swimming, (B) running, and (C) to bike. (D) No error.'",options:["A","B","C","D"],answer:"C",solution:"<p>'To bike' should be 'biking' (gerund) for parallelism.</p>"},{question:"Identify the error: 'He is (A) not only smart (B) but also (C) he is kind. (D) No error.'",options:["A","B","C","D"],answer:"C",solution:"<p>'He is kind' breaks parallelism. Should be just 'kind'.</p>"},{question:"Which sentence is correct?",options:["She likes to swim, run, and biking.","She likes swimming, running, and biking.","She likes to swim, to run, and biking.","She likes swim, run, and bike."],answer:"B",solution:"<p>All gerunds: swimming, running, biking.</p>"}]},
    {title:"18.6 Dangling Modifiers",content:"<p>A dangling modifier is a phrase that does not have a clear subject to modify.</p><div class='formula-box'><strong>Dangling Modifier Rules</strong><br/>Modifier must have clear noun to modify<br/>Noun should appear immediately after modifier<br/>Example: Walking to school, I saw the rain</div>",examInsight:"Dangling modifiers are a common error.",practiceProblems:[{question:"Identify the error: 'Walking (A) to school, the rain (B) started (C) to fall. (D) No error.'",options:["A","B","C","D"],answer:"B",solution:"<p>Rain cannot walk. Subject mismatch: 'Walking to school, I felt the rain start.'</p>"},{question:"Which sentence is correct?",options:["Having finished the test, the bell rang.","Having finished the test, the students heard the bell.","Having finished the test, it was time for lunch.","Having finished the test, the bell was heard."],answer:"B",solution:"<p>'Students' can finish a test. Others have dangling modifiers.</p>"},{question:"Identify the error: 'To succeed (A) in business, (B) hard work (C) is necessary. (D) No error.'",options:["A","B","C","D"],answer:"C",solution:"<p>'Hard work' cannot succeed in business. Should be 'To succeed, you need hard work.'</p>"}]},
    {title:"18.7 Diction and Idiom Errors",content:"<p>Diction errors involve choosing the wrong word. Idiom errors involve incorrect prepositions or fixed expressions.</p><div class='formula-box'><strong>Common Errors</strong><br/>Affect (verb) vs. Effect (noun)<br/>Lie (intransitive) vs. Lay (transitive)<br/>Between (two) vs. Among (three+)<br/>Capable of (not to)<br/>Different from (not than)</div>",examInsight:"Diction and idiom errors require memorizing correct usages.",practiceProblems:[{question:"Identify the error: 'The new policy will (A) effect (B) all (C) employees. (D) No error.'",options:["A","B","C","D"],answer:"B",solution:"<p>Should be 'affect' (verb) not 'effect' (noun).</p>"},{question:"Identify the error: 'She is (A) capable to (B) complete (C) the task. (D) No error.'",options:["A","B","C","D"],answer:"B",solution:"<p>Should be 'capable of completing'.</p>"},{question:"Which sentence uses the correct word?",options:["The effect of the medicine was positive.","The affect of the medicine was positive.","The medicine effected him.","The medicine effected him."],answer:"A",solution:"<p>'Effect' is a noun meaning result. Correct.</p>"}]},
    {title:"18.8 Sentence Correction: Choosing the Best Version",content:"<p>Sentence correction questions require you to choose the best version of an underlined section. The correct answer must be grammatically correct, clear, and concise.</p><div class='formula-box'><strong>Correction Strategies</strong><br/>1. Identify the error in the underlined section<br/>2. Look for the answer that corrects all errors<br/>3. Prefer concise and clear wording<br/>4. Don't change the original meaning</div>",examInsight:"Pay attention to the overall structure and logic of the sentence.",practiceProblems:[{question:"Choose the best version: 'The team, along with the coach, are traveling to the championship.'",options:["are traveling","is traveling","were traveling","have been traveling"],answer:"B",solution:"<p>Subject is 'team' (singular). Should be 'is traveling'.</p>"},{question:"Choose the best version: 'Between you and I, this situation is difficult.'",options:["you and I","you and me","I and you","me and you"],answer:"B",solution:"<p>'Between' requires objective case: 'you and me'.</p>"},{question:"Choose the best version: 'She likes swimming, running, and to bike.'",options:["and to bike","and biking","and bike","and to biking"],answer:"B",solution:"<p>Parallel: 'swimming, running, and biking'.</p>"}]}
  ]
};

fs.writeFileSync(path.resolve(__dirname, '..', '_chapter-data.json'), JSON.stringify(ch18, null, 2), 'utf-8');
console.log('Written Ch18');