const fs = require('fs');
const path = require('path');

const ch17 = {
  chapterNumber: 17,
  title: "Sentence Completion",
  overview: "Sentence completion questions test your vocabulary, grammar, and logical reasoning. You are given a sentence with one or two missing words and must choose the best word(s) to complete it.",
  corePoints: ["Read the entire sentence first","Look for context clues: definitions, examples, contrasts","Watch for signal words: but, although, because, therefore","For double-blank questions, test the first word first","Eliminate answer choices that do not fit grammatically","Use word parts (prefixes, roots) to infer meaning","The correct answer must make logical and grammatical sense"],
  examTips: "Sentence completion questions typically appear as 3-5 questions per verbal section. The most common trap is choosing a word that fits grammatically but not logically.",
  youtubeVideoId: "placeholder",
  videoDuration: "13:45",
  materials: [
    {name:"Context Clues",formula:"",description:"Words or phrases that hint at the missing word's meaning."},
    {name:"Signal Words: Contrast",formula:"",description:"Words like but, although, however, despite indicate contrast."},
    {name:"Signal Words: Cause/Effect",formula:"",description:"Words like because, since, therefore indicate cause-and-effect."},
    {name:"Signal Words: Continuation",formula:"",description:"Words like and, moreover, furthermore indicate continuation."},
    {name:"Double-Blank Strategy",formula:"",description:"Test the first word of each answer choice, then test the second."},
    {name:"Word Parts Analysis",formula:"",description:"Break down unfamiliar words into prefixes, roots, and suffixes."}
  ],
  subtopics: [
    {title:"17.1 Basic Strategies for Sentence Completion",content:"<p>Read the entire sentence carefully. Think of a word that makes sense in the blank. Then test each answer choice.</p><div class='formula-box'><strong>Basic Strategy Steps</strong><br/>1. Read the sentence for meaning<br/>2. Think of a word that fits<br/>3. Eliminate choices that don't fit<br/>4. Test remaining choices in context</div>",examInsight:"This is the foundational approach for all sentence completion questions.",practiceProblems:[{question:"My ______ were ______ when I heard his explanation; I was convinced he was telling the truth.",options:["doubts ... dispelled","suspicions ... confirmed","fears ... distracted","misgivings ... aroused"],answer:"A",solution:"<p>If convinced, doubts must have been removed. 'Doubts dispelled' is the best fit.</p>"},{question:"The owners of the spa advertised that their ______ were especially ______ for the arthritic.",options:["waters ... healthful","mountains ... beneficial","water ... deleterious","springs ... toxic"],answer:"A",solution:"<p>A spa is associated with waters. 'Healthful' means beneficial.</p>"},{question:"Although the candidate had a strong record, his ______ comments ______ many voters.",options:["insightful ... impressed","inflammatory ... alienated","thoughtful ... engaged","conciliatory ... united"],answer:"B",solution:"<p>'Although' signals contrast. 'Inflammatory' comments would alienate voters.</p>"}]},
    {title:"17.2 Using Context Clues",content:"<p>Context clues hint at the missing word's meaning. Four common types: definition, example, contrast, and restatement.</p><div class='formula-box'><strong>Context Clue Types</strong><br/>Definition, Example, Contrast, Restatement</div>",examInsight:"Recognizing context clues is essential for vocabulary questions.",practiceProblems:[{question:"The ______ storm, with its howling winds and torrential rain, caused widespread damage.",options:["gentle","violent","mild","brief"],answer:"B",solution:"<p>'Howling winds and torrential rain' describe a violent storm.</p>"},{question:"His argument was so ______ that even his opponents had to admit he was right.",options:["weak","flawed","compelling","doubtful"],answer:"C",solution:"<p>Opponents admitting he was right means the argument was compelling.</p>"},{question:"The scientist was known for his ______ attention to detail, which made his experiments exceptionally accurate.",options:["careless","meticulous","hasty","superficial"],answer:"B",solution:"<p>Meticulous means showing great attention to detail.</p>"}]},
    {title:"17.3 Signal Words: Contrast and Comparison",content:"<p>Signal words indicate the relationship between parts of the sentence. Contrast words (but, although, however) indicate the missing word will be opposite.</p><div class='formula-box'><strong>Common Signal Words</strong><br/>Contrast: but, although, however, despite, yet<br/>Comparison: similarly, likewise, also<br/>Cause/Effect: because, since, therefore</div>",examInsight:"Recognizing contrast signals can help you find the correct answer quickly.",practiceProblems:[{question:"She was usually ______, but today she seemed unusually animated.",options:["quiet","talkative","energetic","enthusiastic"],answer:"A",solution:"<p>'But' signals contrast. Opposite of 'animated' is 'quiet'.</p>"},{question:"Despite his ______ performance in practice, he played brilliantly in the game.",options:["stellar","mediocre","excellent","outstanding"],answer:"B",solution:"<p>'Despite' signals contrast. Opposite of 'brilliantly' is 'mediocre'.</p>"},{question:"The team was ______, and they were also well-prepared.",options:["unorganized","motivated","confused","disjointed"],answer:"B",solution:"<p>'And' signals continuation. Positive quality like 'well-prepared' is 'motivated'.</p>"}]},
    {title:"17.4 Signal Words: Cause and Effect",content:"<p>Cause/effect signal words indicate one part of the sentence causes or results from another.</p><div class='formula-box'><strong>Cause/Effect Signals</strong><br/>Because, Since = cause<br/>Therefore, Thus, Consequently = effect</div>",examInsight:"This pattern appears frequently.",practiceProblems:[{question:"Since the weather was ______, the picnic was postponed.",options:["sunny","clear","inclement","warm"],answer:"C",solution:"<p>'Since' signals cause. 'Inclement' means stormy or severe.</p>"},{question:"He studied diligently for weeks; ______, he passed the exam with flying colors.",options:["consequently","however","nevertheless","despite"],answer:"A",solution:"<p>'Consequently' means as a result.</p>"},{question:"The bridge collapsed because the ______ structure could not support the heavy load.",options:["sturdy","reinforced","fragile","robust"],answer:"C",solution:"<p>'Because' signals cause. 'Fragile' means weak or easily broken.</p>"}]},
    {title:"17.5 Double-Blank Questions",content:"<p>For double-blank questions, test the first word of each answer choice. Eliminate any that don't fit. Then test the second word.</p><div class='formula-box'><strong>Double-Blank Strategy</strong><br/>1. Read the sentence with both blanks<br/>2. Test the first word of each choice<br/>3. Eliminate where first word doesn't fit<br/>4. Test second word in remaining choices</div>",examInsight:"Double-blank questions are common. Testing one blank at a time is highly effective.",practiceProblems:[{question:"The governor's ______ of the budget was ______, leading to widespread criticism.",options:["handling ... praised","management ... criticized","approval ... praised","rejection ... criticized"],answer:"B",solution:"<p>The action led to criticism, so 'management' and 'criticized' fit.</p>"},{question:"The ______ of the painting was ______; even experts could not agree on its authenticity.",options:["beauty ... debated","origin ... unknown","value ... clear","subject ... obvious"],answer:"B",solution:"<p>Experts could not agree, so 'origin' being 'unknown' fits.</p>"},{question:"Her ______ attitude toward the project was ______; she was indifferent to its success.",options:["enthusiastic ... infectious","apathetic ... obvious","curious ... surprising","negative ... clear"],answer:"B",solution:"<p>She was indifferent, so 'apathetic' and 'obvious' fit.</p>"}]},
    {title:"17.6 Advanced Strategies and Vocabulary",content:"<p>For difficult questions, rely on advanced vocabulary and logical reasoning. Look for subtle clues like tone and degree. Use word parts to infer meanings.</p><div class='formula-box'><strong>Advanced Strategies</strong><br/>Identify tone: positive, negative, neutral<br/>Consider degree: mild, moderate, extreme<br/>Use roots: e.g., bene = good, mal = bad</div>",examInsight:"These questions challenge high-scoring students.",practiceProblems:[{question:"The ______ nature of the disease made it difficult to contain.",options:["virulent","benign","mild","dormant"],answer:"A",solution:"<p>'Virulent' means extremely severe or harmful.</p>"},{question:"Her ______ demeanor, maintained even under pressure, earned her respect.",options:["anxious","flustered","composed","chaotic"],answer:"C",solution:"<p>'Composed' means calm and in control under pressure.</p>"},{question:"The professor's lecture was so ______ that many students fell asleep.",options:["engaging","dull","exciting","informative"],answer:"B",solution:"<p>Students falling asleep means the lecture was dull.</p>"}]},
    {title:"17.7 Eliminating Wrong Answers",content:"<p>Use elimination to narrow choices. Look for words that are grammatically incorrect, don't fit context, or create contradictory meanings.</p><div class='formula-box'><strong>Elimination Criteria</strong><br/>1. Grammatically incorrect<br/>2. Logically inconsistent<br/>3. Too vague or too specific<br/>4. Opposite of required meaning</div>",examInsight:"Elimination is a powerful tool for difficult questions.",practiceProblems:[{question:"The new policy was met with ______; employees were angry.",options:["enthusiasm","apathy","hostility","indifference"],answer:"C",solution:"<p>'Hostility' means active opposition or anger.</p>"},{question:"The architect's design was ______, incorporating both modern and traditional elements.",options:["eclectic","uniform","conventional","antiquated"],answer:"A",solution:"<p>'Eclectic' means composed of elements from various sources.</p>"},{question:"Despite his ______, he was able to ______ the challenging task.",options:["inexperience ... complete","ability ... fail","confidence ... avoid","enthusiasm ... ignore"],answer:"A",solution:"<p>'Despite' signals contrast. 'Inexperience' is a weakness; 'complete' shows success.</p>"}]},
    {title:"17.8 Application in Reading Comprehension",content:"<p>Sentence completion skills are directly applicable to reading comprehension. Context clues, signal words, and logical reasoning help you understand passages.</p><div class='formula-box'><strong>Reading Connection</strong><br/>Use context to infer word meanings<br/>Identify signal words for passage structure<br/>Apply logical reasoning to understand arguments</div>",examInsight:"While sentence completion is a standalone type, the skills are foundational for the entire verbal section.",practiceProblems:[{question:"'The new regulations were draconian, leading to widespread protests.' What does 'draconian' mean?",options:["lenient","severe","flexible","unclear"],answer:"B",solution:"<p>Protests suggest the regulations were severe.</p>"},{question:"'The scientist's theory, once considered heretical, is now widely accepted.' What does 'heretical' mean?",options:["accepted","controversial","traditional","proven"],answer:"B",solution:"<p>'Once considered' suggests it was controversial.</p>"},{question:"'The executive's behavior was egregious, so the board terminated his employment.' What does 'egregious' mean?",options:["outstanding","exceptional","outrageous","minor"],answer:"C",solution:"<p>Termination suggests the behavior was outrageous.</p>"}]},
    {title:"17.9 Quantitative Comparison with Sentence Completion",content:"<p>Some questions ask you to compare the strength or logical fit of two potential answers.</p><div class='formula-box'><strong>Evaluating Answer Choices</strong><br/>Compare shades of meaning<br/>Consider tone and degree<br/>Look for the most precise word</div>",examInsight:"This type separates strong students from average ones.",practiceProblems:[{question:"Which word best completes: 'The ______ of the painting was breathtaking.'",options:["beauty","size","color","age"],answer:"A",solution:"<p>'Breathtaking' suggests beauty.</p>"},{question:"Which word best completes: 'The student's ______ behavior led to his detention.'",options:["disruptive","quiet","studious","polite"],answer:"A",solution:"<p>Detention is a punishment for disruptive behavior.</p>"},{question:"Quantity A: Strength of 'enraged'. Quantity B: Strength of 'annoyed'.",options:["A is greater","B is greater","Equal","Cannot determine"],answer:"A",solution:"<p>'Enraged' is much stronger than 'annoyed'.</p>"}]}
  ]
};

fs.writeFileSync(path.resolve(__dirname, '..', '_chapter-data.json'), JSON.stringify(ch17, null, 2), 'utf-8');
console.log('Written Ch17');